import type { WordPair } from "../protocol.js";

export const DE_WORD_PAIRS: WordPair[] = [
  // ─── Essen (20) ───
  { id: "de-food-pizza-flammkuchen", civilWord: "Pizza", undercoverWord: "Flammkuchen", difficulty: "normal", category: "Essen" },
  { id: "de-food-sushi-sashimi", civilWord: "Sushi", undercoverWord: "Sashimi", difficulty: "hard", category: "Essen" },
  { id: "de-food-burger-sandwich", civilWord: "Burger", undercoverWord: "Sandwich", difficulty: "easy", category: "Essen" },
  { id: "de-food-bretzel-croissant", civilWord: "Brezel", undercoverWord: "Croissant", difficulty: "normal", category: "Essen" },
  { id: "de-food-wurst-bratwurst", civilWord: "Wurst", undercoverWord: "Bratwurst", difficulty: "hard", category: "Essen" },
  { id: "de-food-kuchen-torte", civilWord: "Kuchen", undercoverWord: "Torte", difficulty: "hard", category: "Essen" },
  { id: "de-food-eis-sorbet", civilWord: "Eis", undercoverWord: "Sorbet", difficulty: "normal", category: "Essen" },
  { id: "de-food-pommes-kartoffel", civilWord: "Pommes", undercoverWord: "Kartoffelpuffer", difficulty: "normal", category: "Essen" },
  { id: "de-food-kaese-butter", civilWord: "Käse", undercoverWord: "Butter", difficulty: "normal", category: "Essen" },
  { id: "de-food-brot-toast", civilWord: "Brot", undercoverWord: "Toast", difficulty: "easy", category: "Essen" },
  { id: "de-food-bonbon-schokolade", civilWord: "Bonbon", undercoverWord: "Schokolade", difficulty: "easy", category: "Essen" },
  { id: "de-food-nudeln-spaghetti", civilWord: "Nudeln", undercoverWord: "Spaghetti", difficulty: "hard", category: "Essen" },
  { id: "de-food-donut-krapfen", civilWord: "Donut", undercoverWord: "Krapfen", difficulty: "normal", category: "Essen" },
  { id: "de-food-suppe-eintopf", civilWord: "Suppe", undercoverWord: "Eintopf", difficulty: "hard", category: "Essen" },
  { id: "de-food-schnitzel-cordon-bleu", civilWord: "Schnitzel", undercoverWord: "Cordon bleu", difficulty: "hard", category: "Essen" },
  { id: "de-food-pfannkuchen-waffel", civilWord: "Pfannkuchen", undercoverWord: "Waffel", difficulty: "normal", category: "Essen" },
  { id: "de-food-apfel-birne", civilWord: "Apfel", undercoverWord: "Birne", difficulty: "normal", category: "Essen" },
  { id: "de-food-traube-kirsche", civilWord: "Traube", undercoverWord: "Kirsche", difficulty: "normal", category: "Essen" },
  { id: "de-food-ei-omelette", civilWord: "Ei", undercoverWord: "Omelette", difficulty: "normal", category: "Essen" },
  { id: "de-food-taco-burrito", civilWord: "Taco", undercoverWord: "Burrito", difficulty: "normal", category: "Essen" },

  // ─── Getränke (15) ───
  { id: "de-drink-kaffee-tee", civilWord: "Kaffee", undercoverWord: "Tee", difficulty: "easy", category: "Getränke" },
  { id: "de-drink-saft-smoothie", civilWord: "Saft", undercoverWord: "Smoothie", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-cola-fanta", civilWord: "Cola", undercoverWord: "Fanta", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-milch-joghurt", civilWord: "Milch", undercoverWord: "Joghurt", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-wasser-eis", civilWord: "Wasser", undercoverWord: "Eiswürfel", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-kakao-latte", civilWord: "Kakao", undercoverWord: "Latte", difficulty: "hard", category: "Getränke" },
  { id: "de-drink-limonade-sprudel", civilWord: "Limonade", undercoverWord: "Sprudel", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-bier-apfelwein", civilWord: "Bier", undercoverWord: "Apfelwein", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-gluehwein-punsch", civilWord: "Glühwein", undercoverWord: "Punsch", difficulty: "hard", category: "Getränke" },
  { id: "de-drink-milchshake-eiskaffee", civilWord: "Milchshake", undercoverWord: "Eiskaffee", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-espresso-mokka", civilWord: "Espresso", undercoverWord: "Mokka", difficulty: "hard", category: "Getränke" },
  { id: "de-drink-wein-sekt", civilWord: "Wein", undercoverWord: "Sekt", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-eistee-kraeutertee", civilWord: "Eistee", undercoverWord: "Kräutertee", difficulty: "normal", category: "Getränke" },
  { id: "de-drink-cappuccino-latte-macchiato", civilWord: "Cappuccino", undercoverWord: "Latte Macchiato", difficulty: "hard", category: "Getränke" },
  { id: "de-drink-trinkschokolade-kakao", civilWord: "Trinkschokolade", undercoverWord: "Kakao", difficulty: "hard", category: "Getränke" },

  // ─── Tiere (20) ───
  { id: "de-animal-katze-tiger", civilWord: "Katze", undercoverWord: "Tiger", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-hund-wolf", civilWord: "Hund", undercoverWord: "Wolf", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-pferd-zebra", civilWord: "Pferd", undercoverWord: "Zebra", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-hase-kaninchen", civilWord: "Hase", undercoverWord: "Kaninchen", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-delfin-wal", civilWord: "Delfin", undercoverWord: "Wal", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-adler-falke", civilWord: "Adler", undercoverWord: "Falke", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-frosch-kroete", civilWord: "Frosch", undercoverWord: "Kröte", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-affe-gorilla", civilWord: "Affe", undercoverWord: "Gorilla", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-maus-ratte", civilWord: "Maus", undercoverWord: "Ratte", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-loewe-leopard", civilWord: "Löwe", undercoverWord: "Leopard", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-hai-schwertfisch", civilWord: "Hai", undercoverWord: "Schwertfisch", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-schmetterling-motte", civilWord: "Schmetterling", undercoverWord: "Motte", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-pinguin-ente", civilWord: "Pinguin", undercoverWord: "Ente", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-schlange-wurm", civilWord: "Schlange", undercoverWord: "Wurm", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-schildkroete-schnecke", civilWord: "Schildkröte", undercoverWord: "Schnecke", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-baer-panda", civilWord: "Bär", undercoverWord: "Panda", difficulty: "easy", category: "Tiere" },
  { id: "de-animal-krokodil-eidechse", civilWord: "Krokodil", undercoverWord: "Eidechse", difficulty: "normal", category: "Tiere" },
  { id: "de-animal-papagei-wellensittich", civilWord: "Papagei", undercoverWord: "Wellensittich", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-eule-uhu", civilWord: "Eule", undercoverWord: "Uhu", difficulty: "hard", category: "Tiere" },
  { id: "de-animal-krabbe-hummer", civilWord: "Krabbe", undercoverWord: "Hummer", difficulty: "normal", category: "Tiere" },

  // ─── Gegenstände (15) ───
  { id: "de-obj-handy-tablet", civilWord: "Handy", undercoverWord: "Tablet", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-schluessel-schloss", civilWord: "Schlüssel", undercoverWord: "Schloss", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-buch-zeitschrift", civilWord: "Buch", undercoverWord: "Zeitschrift", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-brille-lupe", civilWord: "Brille", undercoverWord: "Lupe", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-regenschirm-sonnenschirm", civilWord: "Regenschirm", undercoverWord: "Sonnenschirm", difficulty: "hard", category: "Gegenstände" },
  { id: "de-obj-kerze-lampe", civilWord: "Kerze", undercoverWord: "Lampe", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-uhr-wecker", civilWord: "Uhr", undercoverWord: "Wecker", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-messer-schwert", civilWord: "Messer", undercoverWord: "Schwert", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-gitarre-geige", civilWord: "Gitarre", undercoverWord: "Geige", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-kamera-fernglas", civilWord: "Kamera", undercoverWord: "Fernglas", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-koffer-rucksack", civilWord: "Koffer", undercoverWord: "Rucksack", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-spiegel-fenster", civilWord: "Spiegel", undercoverWord: "Fenster", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-schere-zange", civilWord: "Schere", undercoverWord: "Zange", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-geldbeutel-handtasche", civilWord: "Geldbeutel", undercoverWord: "Handtasche", difficulty: "normal", category: "Gegenstände" },
  { id: "de-obj-taschenlampe-laterne", civilWord: "Taschenlampe", undercoverWord: "Laterne", difficulty: "normal", category: "Gegenstände" },

  // ─── Sport (15) ───
  { id: "de-sport-fussball-rugby", civilWord: "Fußball", undercoverWord: "Rugby", difficulty: "normal", category: "Sport" },
  { id: "de-sport-basketball-volleyball", civilWord: "Basketball", undercoverWord: "Volleyball", difficulty: "normal", category: "Sport" },
  { id: "de-sport-tennis-badminton", civilWord: "Tennis", undercoverWord: "Badminton", difficulty: "hard", category: "Sport" },
  { id: "de-sport-schwimmen-tauchen", civilWord: "Schwimmen", undercoverWord: "Tauchen", difficulty: "normal", category: "Sport" },
  { id: "de-sport-skifahren-snowboard", civilWord: "Skifahren", undercoverWord: "Snowboarden", difficulty: "normal", category: "Sport" },
  { id: "de-sport-boxen-ringen", civilWord: "Boxen", undercoverWord: "Ringen", difficulty: "normal", category: "Sport" },
  { id: "de-sport-surfen-kajak", civilWord: "Surfen", undercoverWord: "Kajakfahren", difficulty: "normal", category: "Sport" },
  { id: "de-sport-golf-kegeln", civilWord: "Golf", undercoverWord: "Kegeln", difficulty: "normal", category: "Sport" },
  { id: "de-sport-radfahren-rollschuh", civilWord: "Radfahren", undercoverWord: "Rollschuhlaufen", difficulty: "normal", category: "Sport" },
  { id: "de-sport-klettern-wandern", civilWord: "Klettern", undercoverWord: "Wandern", difficulty: "hard", category: "Sport" },
  { id: "de-sport-eishockey-feldhockey", civilWord: "Eishockey", undercoverWord: "Feldhockey", difficulty: "hard", category: "Sport" },
  { id: "de-sport-bogenschiessen-darts", civilWord: "Bogenschießen", undercoverWord: "Darts", difficulty: "normal", category: "Sport" },
  { id: "de-sport-segeln-rudern", civilWord: "Segeln", undercoverWord: "Rudern", difficulty: "normal", category: "Sport" },
  { id: "de-sport-skateboard-roller", civilWord: "Skateboard", undercoverWord: "Roller", difficulty: "normal", category: "Sport" },
  { id: "de-sport-fechten-karate", civilWord: "Fechten", undercoverWord: "Karate", difficulty: "normal", category: "Sport" },

  // ─── Popkultur (15) ───
  { id: "de-pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Popkultur" },
  { id: "de-pop-batman-spiderman", civilWord: "Batman", undercoverWord: "Spider-Man", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-pikachu-eevee", civilWord: "Pikachu", undercoverWord: "Evoli", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-elsa-rapunzel", civilWord: "Elsa", undercoverWord: "Rapunzel", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-goku-naruto", civilWord: "Goku", undercoverWord: "Naruto", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-spongebob-patrick", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "easy", category: "Popkultur" },
  { id: "de-pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-amongus-werwolf", civilWord: "Among Us", undercoverWord: "Werwolf", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-harry-frodo", civilWord: "Harry Potter", undercoverWord: "Frodo", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-ironman-captain", civilWord: "Iron Man", undercoverWord: "Captain America", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-darth-vader-voldemort", civilWord: "Darth Vader", undercoverWord: "Voldemort", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-yoda-gandalf", civilWord: "Yoda", undercoverWord: "Gandalf", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-hulk-shrek", civilWord: "Hulk", undercoverWord: "Shrek", difficulty: "easy", category: "Popkultur" },
  { id: "de-pop-simpsons-griffins", civilWord: "Simpsons", undercoverWord: "Griffins", difficulty: "normal", category: "Popkultur" },
  { id: "de-pop-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "hard", category: "Popkultur" },

  // ─── Orte (20) ───
  { id: "de-place-schloss-burg", civilWord: "Schloss", undercoverWord: "Burg", difficulty: "hard", category: "Orte" },
  { id: "de-place-kirche-moschee", civilWord: "Kirche", undercoverWord: "Moschee", difficulty: "normal", category: "Orte" },
  { id: "de-place-strand-wueste", civilWord: "Strand", undercoverWord: "Wüste", difficulty: "normal", category: "Orte" },
  { id: "de-place-berg-vulkan", civilWord: "Berg", undercoverWord: "Vulkan", difficulty: "normal", category: "Orte" },
  { id: "de-place-see-meer", civilWord: "See", undercoverWord: "Meer", difficulty: "hard", category: "Orte" },
  { id: "de-place-park-wald", civilWord: "Park", undercoverWord: "Wald", difficulty: "normal", category: "Orte" },
  { id: "de-place-bauernhof-zoo", civilWord: "Bauernhof", undercoverWord: "Zoo", difficulty: "normal", category: "Orte" },
  { id: "de-place-schule-universitaet", civilWord: "Schule", undercoverWord: "Universität", difficulty: "hard", category: "Orte" },
  { id: "de-place-krankenhaus-apotheke", civilWord: "Krankenhaus", undercoverWord: "Apotheke", difficulty: "normal", category: "Orte" },
  { id: "de-place-flughafen-bahnhof", civilWord: "Flughafen", undercoverWord: "Bahnhof", difficulty: "normal", category: "Orte" },
  { id: "de-place-restaurant-kantine", civilWord: "Restaurant", undercoverWord: "Kantine", difficulty: "normal", category: "Orte" },
  { id: "de-place-supermarkt-kiosk", civilWord: "Supermarkt", undercoverWord: "Kiosk", difficulty: "normal", category: "Orte" },
  { id: "de-place-bibliothek-buchhandlung", civilWord: "Bibliothek", undercoverWord: "Buchhandlung", difficulty: "hard", category: "Orte" },
  { id: "de-place-bruecke-tunnel", civilWord: "Brücke", undercoverWord: "Tunnel", difficulty: "normal", category: "Orte" },
  { id: "de-place-leuchtturm-windmuehle", civilWord: "Leuchtturm", undercoverWord: "Windmühle", difficulty: "normal", category: "Orte" },
  { id: "de-place-friedhof-ruine", civilWord: "Friedhof", undercoverWord: "Ruine", difficulty: "normal", category: "Orte" },
  { id: "de-place-hoehle-stollen", civilWord: "Höhle", undercoverWord: "Stollen", difficulty: "hard", category: "Orte" },
  { id: "de-place-stadion-arena", civilWord: "Stadion", undercoverWord: "Arena", difficulty: "hard", category: "Orte" },
  { id: "de-place-spielplatz-rummelplatz", civilWord: "Spielplatz", undercoverWord: "Rummelplatz", difficulty: "normal", category: "Orte" },
  { id: "de-place-insel-halbinsel", civilWord: "Insel", undercoverWord: "Halbinsel", difficulty: "hard", category: "Orte" },

  // ─── Natur (20) ───
  { id: "de-nature-baum-busch", civilWord: "Baum", undercoverWord: "Busch", difficulty: "normal", category: "Natur" },
  { id: "de-nature-blume-kaktus", civilWord: "Blume", undercoverWord: "Kaktus", difficulty: "normal", category: "Natur" },
  { id: "de-nature-sonne-mond", civilWord: "Sonne", undercoverWord: "Mond", difficulty: "easy", category: "Natur" },
  { id: "de-nature-wolke-nebel", civilWord: "Wolke", undercoverWord: "Nebel", difficulty: "hard", category: "Natur" },
  { id: "de-nature-fluss-bach", civilWord: "Fluss", undercoverWord: "Bach", difficulty: "hard", category: "Natur" },
  { id: "de-nature-wasserfall-fontaene", civilWord: "Wasserfall", undercoverWord: "Fontäne", difficulty: "normal", category: "Natur" },
  { id: "de-nature-regenbogen-nordlicht", civilWord: "Regenbogen", undercoverWord: "Nordlicht", difficulty: "normal", category: "Natur" },
  { id: "de-nature-pilz-moos", civilWord: "Pilz", undercoverWord: "Moos", difficulty: "normal", category: "Natur" },
  { id: "de-nature-rose-tulpe", civilWord: "Rose", undercoverWord: "Tulpe", difficulty: "normal", category: "Natur" },
  { id: "de-nature-sonnenblume-gaensebluemchen", civilWord: "Sonnenblume", undercoverWord: "Gänseblümchen", difficulty: "normal", category: "Natur" },
  { id: "de-nature-felsen-stein", civilWord: "Felsen", undercoverWord: "Stein", difficulty: "hard", category: "Natur" },
  { id: "de-nature-eiszapfen-schneeflocke", civilWord: "Eiszapfen", undercoverWord: "Schneeflocke", difficulty: "normal", category: "Natur" },
  { id: "de-nature-muschel-koralle", civilWord: "Muschel", undercoverWord: "Koralle", difficulty: "normal", category: "Natur" },
  { id: "de-nature-lava-magma", civilWord: "Lava", undercoverWord: "Feuer", difficulty: "normal", category: "Natur" },
  { id: "de-nature-kleeblatt-efeu", civilWord: "Kleeblatt", undercoverWord: "Efeu", difficulty: "normal", category: "Natur" },
  { id: "de-nature-tannenzapfen-kastanie", civilWord: "Tannenzapfen", undercoverWord: "Kastanie", difficulty: "normal", category: "Natur" },
  { id: "de-nature-palme-tanne", civilWord: "Palme", undercoverWord: "Tanne", difficulty: "normal", category: "Natur" },
  { id: "de-nature-blitz-donner", civilWord: "Blitz", undercoverWord: "Donner", difficulty: "hard", category: "Natur" },
  { id: "de-nature-welle-brandung", civilWord: "Welle", undercoverWord: "Brandung", difficulty: "hard", category: "Natur" },
  { id: "de-nature-korallenriff-seegras", civilWord: "Korallenriff", undercoverWord: "Seegras", difficulty: "normal", category: "Natur" },

  // ─── Körper (18) ───
  { id: "de-body-auge-brille", civilWord: "Auge", undercoverWord: "Brille", difficulty: "normal", category: "Körper" },
  { id: "de-body-hand-faust", civilWord: "Hand", undercoverWord: "Faust", difficulty: "hard", category: "Körper" },
  { id: "de-body-fuss-schuh", civilWord: "Fuß", undercoverWord: "Schuh", difficulty: "normal", category: "Körper" },
  { id: "de-body-nase-mund", civilWord: "Nase", undercoverWord: "Mund", difficulty: "easy", category: "Körper" },
  { id: "de-body-ohr-kopfhoerer", civilWord: "Ohr", undercoverWord: "Kopfhörer", difficulty: "normal", category: "Körper" },
  { id: "de-body-zahn-gebiss", civilWord: "Zahn", undercoverWord: "Gebiss", difficulty: "hard", category: "Körper" },
  { id: "de-body-finger-daumen", civilWord: "Finger", undercoverWord: "Daumen", difficulty: "hard", category: "Körper" },
  { id: "de-body-herz-lunge", civilWord: "Herz", undercoverWord: "Lunge", difficulty: "normal", category: "Körper" },
  { id: "de-body-knochen-skelett", civilWord: "Knochen", undercoverWord: "Skelett", difficulty: "hard", category: "Körper" },
  { id: "de-body-muskel-bizeps", civilWord: "Muskel", undercoverWord: "Bizeps", difficulty: "hard", category: "Körper" },
  { id: "de-body-gehirn-schaedel", civilWord: "Gehirn", undercoverWord: "Schädel", difficulty: "normal", category: "Körper" },
  { id: "de-body-bart-schnurrbart", civilWord: "Bart", undercoverWord: "Schnurrbart", difficulty: "hard", category: "Körper" },
  { id: "de-body-zunge-lippe", civilWord: "Zunge", undercoverWord: "Lippe", difficulty: "normal", category: "Körper" },
  { id: "de-body-knie-ellenbogen", civilWord: "Knie", undercoverWord: "Ellenbogen", difficulty: "normal", category: "Körper" },
  { id: "de-body-ruecken-wirbelsaeule", civilWord: "Rücken", undercoverWord: "Wirbelsäule", difficulty: "hard", category: "Körper" },
  { id: "de-body-augenbraue-wimper", civilWord: "Augenbraue", undercoverWord: "Wimper", difficulty: "hard", category: "Körper" },
  { id: "de-body-haare-peruecke", civilWord: "Haare", undercoverWord: "Perücke", difficulty: "normal", category: "Körper" },
  { id: "de-body-traene-schweiss", civilWord: "Träne", undercoverWord: "Schweiß", difficulty: "hard", category: "Körper" },

  // ─── Kleidung (18) ───
  { id: "de-cloth-hut-muetze", civilWord: "Hut", undercoverWord: "Mütze", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-jacke-mantel", civilWord: "Jacke", undercoverWord: "Mantel", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-schuh-stiefel", civilWord: "Schuh", undercoverWord: "Stiefel", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-socke-strumpf", civilWord: "Socke", undercoverWord: "Strumpf", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-hemd-bluse", civilWord: "Hemd", undercoverWord: "Bluse", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-hose-rock", civilWord: "Hose", undercoverWord: "Rock", difficulty: "easy", category: "Kleidung" },
  { id: "de-cloth-handschuh-faeustling", civilWord: "Handschuh", undercoverWord: "Fäustling", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-krawatte-fliege", civilWord: "Krawatte", undercoverWord: "Fliege", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-pullover-hoodie", civilWord: "Pullover", undercoverWord: "Hoodie", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-kleid-abendkleid", civilWord: "Kleid", undercoverWord: "Abendkleid", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-sandale-flipflop", civilWord: "Sandale", undercoverWord: "Flipflop", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-schal-halstuch", civilWord: "Schal", undercoverWord: "Halstuch", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-guertel-hosentraeger", civilWord: "Gürtel", undercoverWord: "Hosenträger", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-bikini-badeanzug", civilWord: "Bikini", undercoverWord: "Badeanzug", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-pyjama-bademantel", civilWord: "Pyjama", undercoverWord: "Bademantel", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-krone-tiara", civilWord: "Krone", undercoverWord: "Tiara", difficulty: "hard", category: "Kleidung" },
  { id: "de-cloth-sonnenbrille-skibrille", civilWord: "Sonnenbrille", undercoverWord: "Skibrille", difficulty: "normal", category: "Kleidung" },
  { id: "de-cloth-turnschuh-wanderschuh", civilWord: "Turnschuh", undercoverWord: "Wanderschuh", difficulty: "hard", category: "Kleidung" },

  // ─── Fahrzeuge (18) ───
  { id: "de-vehicle-auto-bus", civilWord: "Auto", undercoverWord: "Bus", difficulty: "easy", category: "Fahrzeuge" },
  { id: "de-vehicle-zug-strassenbahn", civilWord: "Zug", undercoverWord: "Straßenbahn", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-fahrrad-motorrad", civilWord: "Fahrrad", undercoverWord: "Motorrad", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-flugzeug-hubschrauber", civilWord: "Flugzeug", undercoverWord: "Hubschrauber", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-schiff-boot", civilWord: "Schiff", undercoverWord: "Boot", difficulty: "hard", category: "Fahrzeuge" },
  { id: "de-vehicle-uboot-tauchboot", civilWord: "U-Boot", undercoverWord: "Tauchboot", difficulty: "hard", category: "Fahrzeuge" },
  { id: "de-vehicle-traktor-bagger", civilWord: "Traktor", undercoverWord: "Bagger", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-krankenwagen-feuerwehr", civilWord: "Krankenwagen", undercoverWord: "Feuerwehr", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-taxi-limousine", civilWord: "Taxi", undercoverWord: "Limousine", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-segelboot-kanu", civilWord: "Segelboot", undercoverWord: "Kanu", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-skateboard-longboard", civilWord: "Skateboard", undercoverWord: "Longboard", difficulty: "hard", category: "Fahrzeuge" },
  { id: "de-vehicle-heissluftballon-zeppelin", civilWord: "Heißluftballon", undercoverWord: "Zeppelin", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-kutsche-schlitten", civilWord: "Kutsche", undercoverWord: "Schlitten", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-rakete-duesenjet", civilWord: "Rakete", undercoverWord: "Düsenjet", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-lkw-transporter", civilWord: "LKW", undercoverWord: "Transporter", difficulty: "hard", category: "Fahrzeuge" },
  { id: "de-vehicle-einrad-dreirad", civilWord: "Einrad", undercoverWord: "Dreirad", difficulty: "normal", category: "Fahrzeuge" },
  { id: "de-vehicle-gondel-seilbahn", civilWord: "Gondel", undercoverWord: "Seilbahn", difficulty: "hard", category: "Fahrzeuge" },
  { id: "de-vehicle-floß-kajak", civilWord: "Floß", undercoverWord: "Kajak", difficulty: "normal", category: "Fahrzeuge" },

  // ─── Berufe (18) ───
  { id: "de-job-arzt-krankenschwester", civilWord: "Arzt", undercoverWord: "Krankenschwester", difficulty: "normal", category: "Berufe" },
  { id: "de-job-polizist-detektiv", civilWord: "Polizist", undercoverWord: "Detektiv", difficulty: "normal", category: "Berufe" },
  { id: "de-job-koch-baecker", civilWord: "Koch", undercoverWord: "Bäcker", difficulty: "normal", category: "Berufe" },
  { id: "de-job-lehrer-professor", civilWord: "Lehrer", undercoverWord: "Professor", difficulty: "hard", category: "Berufe" },
  { id: "de-job-feuerwehrmann-rettungssanitaeter", civilWord: "Feuerwehrmann", undercoverWord: "Rettungssanitäter", difficulty: "normal", category: "Berufe" },
  { id: "de-job-pilot-astronaut", civilWord: "Pilot", undercoverWord: "Astronaut", difficulty: "normal", category: "Berufe" },
  { id: "de-job-maler-bildhauer", civilWord: "Maler", undercoverWord: "Bildhauer", difficulty: "normal", category: "Berufe" },
  { id: "de-job-zauberer-clown", civilWord: "Zauberer", undercoverWord: "Clown", difficulty: "easy", category: "Berufe" },
  { id: "de-job-pirat-ritter", civilWord: "Pirat", undercoverWord: "Ritter", difficulty: "easy", category: "Berufe" },
  { id: "de-job-gaertner-bauer", civilWord: "Gärtner", undercoverWord: "Bauer", difficulty: "normal", category: "Berufe" },
  { id: "de-job-fotograf-kameramann", civilWord: "Fotograf", undercoverWord: "Kameramann", difficulty: "hard", category: "Berufe" },
  { id: "de-job-brieftraeger-kurier", civilWord: "Briefträger", undercoverWord: "Kurier", difficulty: "hard", category: "Berufe" },
  { id: "de-job-richter-anwalt", civilWord: "Richter", undercoverWord: "Anwalt", difficulty: "normal", category: "Berufe" },
  { id: "de-job-tischler-zimmermann", civilWord: "Tischler", undercoverWord: "Zimmermann", difficulty: "hard", category: "Berufe" },
  { id: "de-job-mechaniker-elektriker", civilWord: "Mechaniker", undercoverWord: "Elektriker", difficulty: "normal", category: "Berufe" },
  { id: "de-job-friseur-barbier", civilWord: "Friseur", undercoverWord: "Barbier", difficulty: "hard", category: "Berufe" },
  { id: "de-job-matrose-kapitaen", civilWord: "Matrose", undercoverWord: "Kapitän", difficulty: "normal", category: "Berufe" },
  { id: "de-job-ninja-samurai", civilWord: "Ninja", undercoverWord: "Samurai", difficulty: "normal", category: "Berufe" },

  // ─── Instrumente (16) ───
  { id: "de-instr-gitarre-bass", civilWord: "Gitarre", undercoverWord: "Bass", difficulty: "hard", category: "Instrumente" },
  { id: "de-instr-klavier-keyboard", civilWord: "Klavier", undercoverWord: "Keyboard", difficulty: "hard", category: "Instrumente" },
  { id: "de-instr-trommel-bongo", civilWord: "Trommel", undercoverWord: "Bongo", difficulty: "hard", category: "Instrumente" },
  { id: "de-instr-trompete-posaune", civilWord: "Trompete", undercoverWord: "Posaune", difficulty: "hard", category: "Instrumente" },
  { id: "de-instr-floete-klarinette", civilWord: "Flöte", undercoverWord: "Klarinette", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-geige-cello", civilWord: "Geige", undercoverWord: "Cello", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-harfe-zither", civilWord: "Harfe", undercoverWord: "Zither", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-xylophon-glockenspiel", civilWord: "Xylophon", undercoverWord: "Glockenspiel", difficulty: "hard", category: "Instrumente" },
  { id: "de-instr-akkordeon-harmonika", civilWord: "Akkordeon", undercoverWord: "Mundharmonika", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-dudelsack-floete", civilWord: "Dudelsack", undercoverWord: "Panflöte", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-saxophon-oboe", civilWord: "Saxophon", undercoverWord: "Oboe", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-tamburin-triangel", civilWord: "Tamburin", undercoverWord: "Triangel", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-orgel-synthesizer", civilWord: "Orgel", undercoverWord: "Synthesizer", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-banjo-ukulele", civilWord: "Banjo", undercoverWord: "Ukulele", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-becken-gong", civilWord: "Becken", undercoverWord: "Gong", difficulty: "normal", category: "Instrumente" },
  { id: "de-instr-maracas-rassel", civilWord: "Maracas", undercoverWord: "Rassel", difficulty: "hard", category: "Instrumente" },

  // ─── Technik (16) ───
  { id: "de-tech-laptop-computer", civilWord: "Laptop", undercoverWord: "Computer", difficulty: "hard", category: "Technik" },
  { id: "de-tech-fernseher-monitor", civilWord: "Fernseher", undercoverWord: "Monitor", difficulty: "hard", category: "Technik" },
  { id: "de-tech-kopfhoerer-lautsprecher", civilWord: "Kopfhörer", undercoverWord: "Lautsprecher", difficulty: "normal", category: "Technik" },
  { id: "de-tech-maus-trackpad", civilWord: "Maus", undercoverWord: "Trackpad", difficulty: "normal", category: "Technik" },
  { id: "de-tech-drucker-scanner", civilWord: "Drucker", undercoverWord: "Scanner", difficulty: "normal", category: "Technik" },
  { id: "de-tech-mikrofon-megafon", civilWord: "Mikrofon", undercoverWord: "Megafon", difficulty: "normal", category: "Technik" },
  { id: "de-tech-usb-stick-festplatte", civilWord: "USB-Stick", undercoverWord: "Festplatte", difficulty: "normal", category: "Technik" },
  { id: "de-tech-smartwatch-armbanduhr", civilWord: "Smartwatch", undercoverWord: "Armbanduhr", difficulty: "hard", category: "Technik" },
  { id: "de-tech-drohne-fernsteuerung", civilWord: "Drohne", undercoverWord: "Fernsteuerung", difficulty: "normal", category: "Technik" },
  { id: "de-tech-roboter-androide", civilWord: "Roboter", undercoverWord: "Androide", difficulty: "hard", category: "Technik" },
  { id: "de-tech-beamer-projektor", civilWord: "Beamer", undercoverWord: "Leinwand", difficulty: "normal", category: "Technik" },
  { id: "de-tech-webcam-ueberwachungskamera", civilWord: "Webcam", undercoverWord: "Überwachungskamera", difficulty: "normal", category: "Technik" },
  { id: "de-tech-konsole-gamepad", civilWord: "Konsole", undercoverWord: "Gamepad", difficulty: "normal", category: "Technik" },
  { id: "de-tech-satellit-antenne", civilWord: "Satellit", undercoverWord: "Antenne", difficulty: "normal", category: "Technik" },
  { id: "de-tech-taschenrechner-abakus", civilWord: "Taschenrechner", undercoverWord: "Abakus", difficulty: "normal", category: "Technik" },
  { id: "de-tech-batterie-steckdose", civilWord: "Batterie", undercoverWord: "Steckdose", difficulty: "normal", category: "Technik" },

  // ─── Schule (16) ───
  { id: "de-school-bleistift-kugelschreiber", civilWord: "Bleistift", undercoverWord: "Kugelschreiber", difficulty: "normal", category: "Schule" },
  { id: "de-school-radiergummi-tintenkiller", civilWord: "Radiergummi", undercoverWord: "Tintenkiller", difficulty: "hard", category: "Schule" },
  { id: "de-school-lineal-geodreieck", civilWord: "Lineal", undercoverWord: "Geodreieck", difficulty: "normal", category: "Schule" },
  { id: "de-school-heft-block", civilWord: "Heft", undercoverWord: "Block", difficulty: "hard", category: "Schule" },
  { id: "de-school-tafel-whiteboard", civilWord: "Tafel", undercoverWord: "Whiteboard", difficulty: "hard", category: "Schule" },
  { id: "de-school-kreide-marker", civilWord: "Kreide", undercoverWord: "Marker", difficulty: "normal", category: "Schule" },
  { id: "de-school-ranzen-schultuete", civilWord: "Ranzen", undercoverWord: "Schultüte", difficulty: "normal", category: "Schule" },
  { id: "de-school-globus-landkarte", civilWord: "Globus", undercoverWord: "Landkarte", difficulty: "normal", category: "Schule" },
  { id: "de-school-pinsel-farbkasten", civilWord: "Pinsel", undercoverWord: "Farbkasten", difficulty: "normal", category: "Schule" },
  { id: "de-school-zirkel-winkelmesser", civilWord: "Zirkel", undercoverWord: "Winkelmesser", difficulty: "normal", category: "Schule" },
  { id: "de-school-schere-kleber", civilWord: "Schere", undercoverWord: "Kleber", difficulty: "easy", category: "Schule" },
  { id: "de-school-maeppchen-federmaeppchen", civilWord: "Mäppchen", undercoverWord: "Federmäppchen", difficulty: "hard", category: "Schule" },
  { id: "de-school-spitzer-anspitzer", civilWord: "Spitzer", undercoverWord: "Anspitzer", difficulty: "hard", category: "Schule" },
  { id: "de-school-schulbank-stuhl", civilWord: "Schulbank", undercoverWord: "Stuhl", difficulty: "normal", category: "Schule" },
  { id: "de-school-buecherei-klassenzimmer", civilWord: "Bücherei", undercoverWord: "Klassenzimmer", difficulty: "normal", category: "Schule" },
  { id: "de-school-zeugnis-urkunde", civilWord: "Zeugnis", undercoverWord: "Urkunde", difficulty: "hard", category: "Schule" },

  // ─── Zuhause (18) ───
  { id: "de-home-bett-sofa", civilWord: "Bett", undercoverWord: "Sofa", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-stuhl-hocker", civilWord: "Stuhl", undercoverWord: "Hocker", difficulty: "hard", category: "Zuhause" },
  { id: "de-home-tisch-schreibtisch", civilWord: "Tisch", undercoverWord: "Schreibtisch", difficulty: "hard", category: "Zuhause" },
  { id: "de-home-tuer-tor", civilWord: "Tür", undercoverWord: "Tor", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-treppe-leiter", civilWord: "Treppe", undercoverWord: "Leiter", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-badewanne-dusche", civilWord: "Badewanne", undercoverWord: "Dusche", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-kissen-decke", civilWord: "Kissen", undercoverWord: "Decke", difficulty: "easy", category: "Zuhause" },
  { id: "de-home-teppich-fliese", civilWord: "Teppich", undercoverWord: "Fliese", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-vorhang-jalousie", civilWord: "Vorhang", undercoverWord: "Jalousie", difficulty: "hard", category: "Zuhause" },
  { id: "de-home-regal-schrank", civilWord: "Regal", undercoverWord: "Schrank", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-kamin-ofen", civilWord: "Kamin", undercoverWord: "Ofen", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-briefkasten-paket", civilWord: "Briefkasten", undercoverWord: "Paket", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-zaun-hecke", civilWord: "Zaun", undercoverWord: "Hecke", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-garage-carport", civilWord: "Garage", undercoverWord: "Carport", difficulty: "hard", category: "Zuhause" },
  { id: "de-home-dach-dachboden", civilWord: "Dach", undercoverWord: "Dachboden", difficulty: "hard", category: "Zuhause" },
  { id: "de-home-schaukel-haengematte", civilWord: "Schaukel", undercoverWord: "Hängematte", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-staubsauger-besen", civilWord: "Staubsauger", undercoverWord: "Besen", difficulty: "normal", category: "Zuhause" },
  { id: "de-home-waschmaschine-trockner", civilWord: "Waschmaschine", undercoverWord: "Trockner", difficulty: "hard", category: "Zuhause" },

  // ─── Wetter (15) ───
  { id: "de-weather-regen-hagel", civilWord: "Regen", undercoverWord: "Hagel", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-schnee-frost", civilWord: "Schnee", undercoverWord: "Frost", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-tornado-hurrikan", civilWord: "Tornado", undercoverWord: "Hurrikan", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-sonnenschein-hitze", civilWord: "Sonnenschein", undercoverWord: "Hitze", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-gewitter-blitz", civilWord: "Gewitter", undercoverWord: "Blitz", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-regenbogen-sonne", civilWord: "Regenbogen", undercoverWord: "Sonne", difficulty: "easy", category: "Wetter" },
  { id: "de-weather-wind-sturm", civilWord: "Wind", undercoverWord: "Sturm", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-nebel-dunst", civilWord: "Nebel", undercoverWord: "Dunst", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-eiszapfen-schnee", civilWord: "Eiszapfen", undercoverWord: "Schnee", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-pfuetze-see", civilWord: "Pfütze", undercoverWord: "See", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-schneemann-iglu", civilWord: "Schneemann", undercoverWord: "Iglu", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-wolke-rauch", civilWord: "Wolke", undercoverWord: "Rauch", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-tau-reif", civilWord: "Tau", undercoverWord: "Reif", difficulty: "hard", category: "Wetter" },
  { id: "de-weather-lawine-erdrutsch", civilWord: "Lawine", undercoverWord: "Erdrutsch", difficulty: "normal", category: "Wetter" },
  { id: "de-weather-ueberschwemmung-tsunami", civilWord: "Überschwemmung", undercoverWord: "Tsunami", difficulty: "normal", category: "Wetter" },

  // ─── Fantasie (18) ───
  { id: "de-fantasy-drache-dinosaurier", civilWord: "Drache", undercoverWord: "Dinosaurier", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-einhorn-pegasus", civilWord: "Einhorn", undercoverWord: "Pegasus", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-hexe-zauberer", civilWord: "Hexe", undercoverWord: "Zauberer", difficulty: "easy", category: "Fantasie" },
  { id: "de-fantasy-vampir-werwolf", civilWord: "Vampir", undercoverWord: "Werwolf", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-geist-mumie", civilWord: "Geist", undercoverWord: "Mumie", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-fee-elfe", civilWord: "Fee", undercoverWord: "Elfe", difficulty: "hard", category: "Fantasie" },
  { id: "de-fantasy-riese-troll", civilWord: "Riese", undercoverWord: "Troll", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-meerjungfrau-nixe", civilWord: "Meerjungfrau", undercoverWord: "Nixe", difficulty: "hard", category: "Fantasie" },
  { id: "de-fantasy-kobold-zwerg", civilWord: "Kobold", undercoverWord: "Zwerg", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-skelett-zombie", civilWord: "Skelett", undercoverWord: "Zombie", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-zauberstab-schwert", civilWord: "Zauberstab", undercoverWord: "Zepter", difficulty: "hard", category: "Fantasie" },
  { id: "de-fantasy-schatztruhe-goldmuenzen", civilWord: "Schatztruhe", undercoverWord: "Goldmünzen", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-pheonix-greif", civilWord: "Phönix", undercoverWord: "Greif", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-krake-seemonster", civilWord: "Krake", undercoverWord: "Seemonster", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-zaubertrank-kessel", civilWord: "Zaubertrank", undercoverWord: "Kessel", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-kristallkugel-spiegel", civilWord: "Kristallkugel", undercoverWord: "Zauberspiegel", difficulty: "hard", category: "Fantasie" },
  { id: "de-fantasy-fliegender-teppich-besen", civilWord: "Fliegender Teppich", undercoverWord: "Hexenbesen", difficulty: "normal", category: "Fantasie" },
  { id: "de-fantasy-spinne-skorpion", civilWord: "Spinne", undercoverWord: "Skorpion", difficulty: "normal", category: "Fantasie" },

  // ─── Weltraum (16) ───
  { id: "de-space-stern-planet", civilWord: "Stern", undercoverWord: "Planet", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-mond-asteroid", civilWord: "Mond", undercoverWord: "Asteroid", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-rakete-raumschiff", civilWord: "Rakete", undercoverWord: "Raumschiff", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-astronaut-alien", civilWord: "Astronaut", undercoverWord: "Alien", difficulty: "easy", category: "Weltraum" },
  { id: "de-space-ufo-satellit", civilWord: "UFO", undercoverWord: "Satellit", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-komet-sternschnuppe", civilWord: "Komet", undercoverWord: "Sternschnuppe", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-galaxie-nebel", civilWord: "Galaxie", undercoverWord: "Nebel", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-schwarzes-loch-wurmloch", civilWord: "Schwarzes Loch", undercoverWord: "Wurmloch", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-teleskop-fernglas", civilWord: "Teleskop", undercoverWord: "Fernglas", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-raumstation-raumfaehre", civilWord: "Raumstation", undercoverWord: "Raumfähre", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-mars-jupiter", civilWord: "Mars", undercoverWord: "Jupiter", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-saturn-uranus", civilWord: "Saturn", undercoverWord: "Uranus", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-sonne-supernova", civilWord: "Sonne", undercoverWord: "Supernova", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-mondfinsternis-sonnenfinsternis", civilWord: "Mondfinsternis", undercoverWord: "Sonnenfinsternis", difficulty: "hard", category: "Weltraum" },
  { id: "de-space-meteorit-krater", civilWord: "Meteorit", undercoverWord: "Krater", difficulty: "normal", category: "Weltraum" },
  { id: "de-space-raumanzug-helm", civilWord: "Raumanzug", undercoverWord: "Helm", difficulty: "normal", category: "Weltraum" },

  // ─── Küche (16) ───
  { id: "de-kitchen-topf-pfanne", civilWord: "Topf", undercoverWord: "Pfanne", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-gabel-loeffel", civilWord: "Gabel", undercoverWord: "Löffel", difficulty: "easy", category: "Küche" },
  { id: "de-kitchen-tasse-becher", civilWord: "Tasse", undercoverWord: "Becher", difficulty: "hard", category: "Küche" },
  { id: "de-kitchen-teller-schuessel", civilWord: "Teller", undercoverWord: "Schüssel", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-ofen-mikrowelle", civilWord: "Ofen", undercoverWord: "Mikrowelle", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-kuehlschrank-gefriertruhe", civilWord: "Kühlschrank", undercoverWord: "Gefriertruhe", difficulty: "hard", category: "Küche" },
  { id: "de-kitchen-wasserkocher-teekanne", civilWord: "Wasserkocher", undercoverWord: "Teekanne", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-mixer-ruehrgeraet", civilWord: "Mixer", undercoverWord: "Rührgerät", difficulty: "hard", category: "Küche" },
  { id: "de-kitchen-schneidebrett-messer", civilWord: "Schneidebrett", undercoverWord: "Messer", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-sieb-reibe", civilWord: "Sieb", undercoverWord: "Reibe", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-nudelholz-kochloefel", civilWord: "Nudelholz", undercoverWord: "Kochlöffel", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-toaster-sandwichmaker", civilWord: "Toaster", undercoverWord: "Sandwichmaker", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-spuele-geschirrspueler", civilWord: "Spüle", undercoverWord: "Geschirrspüler", difficulty: "hard", category: "Küche" },
  { id: "de-kitchen-schuerze-topflappen", civilWord: "Schürze", undercoverWord: "Topflappen", difficulty: "normal", category: "Küche" },
  { id: "de-kitchen-gewuerzmuehle-salzstreuer", civilWord: "Gewürzmühle", undercoverWord: "Salzstreuer", difficulty: "hard", category: "Küche" },
  { id: "de-kitchen-karaffe-flasche", civilWord: "Karaffe", undercoverWord: "Flasche", difficulty: "normal", category: "Küche" },

  // ─── Garten (16) ───
  { id: "de-garden-blume-unkraut", civilWord: "Blume", undercoverWord: "Unkraut", difficulty: "normal", category: "Garten" },
  { id: "de-garden-schaufel-spaten", civilWord: "Schaufel", undercoverWord: "Spaten", difficulty: "hard", category: "Garten" },
  { id: "de-garden-giesskanne-schlauch", civilWord: "Gießkanne", undercoverWord: "Gartenschlauch", difficulty: "normal", category: "Garten" },
  { id: "de-garden-rasen-wiese", civilWord: "Rasen", undercoverWord: "Wiese", difficulty: "hard", category: "Garten" },
  { id: "de-garden-beet-blumenkasten", civilWord: "Beet", undercoverWord: "Blumenkasten", difficulty: "normal", category: "Garten" },
  { id: "de-garden-vogelhaus-nistkasten", civilWord: "Vogelhaus", undercoverWord: "Nistkasten", difficulty: "hard", category: "Garten" },
  { id: "de-garden-schubkarre-handwagen", civilWord: "Schubkarre", undercoverWord: "Handwagen", difficulty: "normal", category: "Garten" },
  { id: "de-garden-zaun-mauer", civilWord: "Zaun", undercoverWord: "Mauer", difficulty: "normal", category: "Garten" },
  { id: "de-garden-brunnen-teich", civilWord: "Brunnen", undercoverWord: "Teich", difficulty: "normal", category: "Garten" },
  { id: "de-garden-laub-kompost", civilWord: "Laub", undercoverWord: "Kompost", difficulty: "normal", category: "Garten" },
  { id: "de-garden-rasenmaeher-heckenschere", civilWord: "Rasenmäher", undercoverWord: "Heckenschere", difficulty: "normal", category: "Garten" },
  { id: "de-garden-gewaechshaus-pavillon", civilWord: "Gewächshaus", undercoverWord: "Pavillon", difficulty: "normal", category: "Garten" },
  { id: "de-garden-sandkasten-planschbecken", civilWord: "Sandkasten", undercoverWord: "Planschbecken", difficulty: "normal", category: "Garten" },
  { id: "de-garden-sonnenschirm-markise", civilWord: "Sonnenschirm", undercoverWord: "Markise", difficulty: "hard", category: "Garten" },
  { id: "de-garden-grill-feuerstelle", civilWord: "Grill", undercoverWord: "Feuerstelle", difficulty: "normal", category: "Garten" },
  { id: "de-garden-regenwurm-marienkaefer", civilWord: "Regenwurm", undercoverWord: "Marienkäfer", difficulty: "easy", category: "Garten" },

  // ─── Spielzeug (16) ───
  { id: "de-toy-puppe-teddy", civilWord: "Puppe", undercoverWord: "Teddybär", difficulty: "easy", category: "Spielzeug" },
  { id: "de-toy-lego-baustein", civilWord: "Lego", undercoverWord: "Baustein", difficulty: "hard", category: "Spielzeug" },
  { id: "de-toy-puzzle-domino", civilWord: "Puzzle", undercoverWord: "Domino", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-drachen-frisbee", civilWord: "Drachen", undercoverWord: "Frisbee", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-wuerfel-karte", civilWord: "Würfel", undercoverWord: "Spielkarte", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-kreisel-jojo", civilWord: "Kreisel", undercoverWord: "Jo-Jo", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-murmeln-ballons", civilWord: "Murmeln", undercoverWord: "Ballons", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-schaukelpferd-rutsche", civilWord: "Schaukelpferd", undercoverWord: "Rutsche", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-seifenblasen-luftschlange", civilWord: "Seifenblasen", undercoverWord: "Luftschlangen", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-spielzeugauto-eisenbahn", civilWord: "Spielzeugauto", undercoverWord: "Eisenbahn", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-trommel-rassel", civilWord: "Trommel", undercoverWord: "Rassel", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-sandburg-schneeburg", civilWord: "Sandburg", undercoverWord: "Schneeburg", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-puppenhaus-baumhaus", civilWord: "Puppenhaus", undercoverWord: "Baumhaus", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-wasserpistole-nerf", civilWord: "Wasserpistole", undercoverWord: "Nerf-Blaster", difficulty: "normal", category: "Spielzeug" },
  { id: "de-toy-knete-ton", civilWord: "Knete", undercoverWord: "Ton", difficulty: "hard", category: "Spielzeug" },
  { id: "de-toy-trampolin-huepfburg", civilWord: "Trampolin", undercoverWord: "Hüpfburg", difficulty: "normal", category: "Spielzeug" },

  // ─── Party (15) ───
  { id: "de-party-kuchen-muffin", civilWord: "Kuchen", undercoverWord: "Muffin", difficulty: "normal", category: "Party" },
  { id: "de-party-ballon-girlande", civilWord: "Ballon", undercoverWord: "Girlande", difficulty: "normal", category: "Party" },
  { id: "de-party-konfetti-luftschlange", civilWord: "Konfetti", undercoverWord: "Luftschlange", difficulty: "normal", category: "Party" },
  { id: "de-party-geschenk-ueberraschung", civilWord: "Geschenk", undercoverWord: "Überraschung", difficulty: "normal", category: "Party" },
  { id: "de-party-maske-kostuem", civilWord: "Maske", undercoverWord: "Kostüm", difficulty: "normal", category: "Party" },
  { id: "de-party-disco-kugel-stroboskop", civilWord: "Discokugel", undercoverWord: "Stroboskop", difficulty: "normal", category: "Party" },
  { id: "de-party-wunderkerze-feuerwerk", civilWord: "Wunderkerze", undercoverWord: "Feuerwerk", difficulty: "normal", category: "Party" },
  { id: "de-party-pinata-bonbontasche", civilWord: "Piñata", undercoverWord: "Süßigkeitentüte", difficulty: "normal", category: "Party" },
  { id: "de-party-krone-partyhut", civilWord: "Krone", undercoverWord: "Partyhut", difficulty: "normal", category: "Party" },
  { id: "de-party-dj-band", civilWord: "DJ", undercoverWord: "Band", difficulty: "easy", category: "Party" },
  { id: "de-party-kerze-fackel", civilWord: "Kerze", undercoverWord: "Fackel", difficulty: "normal", category: "Party" },
  { id: "de-party-tanzen-singen", civilWord: "Tanzen", undercoverWord: "Singen", difficulty: "easy", category: "Party" },
  { id: "de-party-einladung-postkarte", civilWord: "Einladung", undercoverWord: "Postkarte", difficulty: "hard", category: "Party" },
  { id: "de-party-hut-peruecke", civilWord: "Hut", undercoverWord: "Perücke", difficulty: "normal", category: "Party" },
  { id: "de-party-bowle-punsch", civilWord: "Bowle", undercoverWord: "Punsch", difficulty: "hard", category: "Party" },

  // ─── Strand (15) ───
  { id: "de-beach-sandburg-sandkuchen", civilWord: "Sandburg", undercoverWord: "Sandkuchen", difficulty: "hard", category: "Strand" },
  { id: "de-beach-muschel-seestern", civilWord: "Muschel", undercoverWord: "Seestern", difficulty: "normal", category: "Strand" },
  { id: "de-beach-palme-kokospalme", civilWord: "Palme", undercoverWord: "Kokospalme", difficulty: "hard", category: "Strand" },
  { id: "de-beach-surfbrett-bodyboard", civilWord: "Surfbrett", undercoverWord: "Bodyboard", difficulty: "hard", category: "Strand" },
  { id: "de-beach-sonnenschirm-strandkorb", civilWord: "Sonnenschirm", undercoverWord: "Strandkorb", difficulty: "normal", category: "Strand" },
  { id: "de-beach-taucherbrille-schnorchel", civilWord: "Taucherbrille", undercoverWord: "Schnorchel", difficulty: "normal", category: "Strand" },
  { id: "de-beach-schwimmring-luftmatratze", civilWord: "Schwimmring", undercoverWord: "Luftmatratze", difficulty: "normal", category: "Strand" },
  { id: "de-beach-leuchtturm-boje", civilWord: "Leuchtturm", undercoverWord: "Boje", difficulty: "normal", category: "Strand" },
  { id: "de-beach-krebs-qualle", civilWord: "Krebs", undercoverWord: "Qualle", difficulty: "normal", category: "Strand" },
  { id: "de-beach-anker-seil", civilWord: "Anker", undercoverWord: "Seil", difficulty: "normal", category: "Strand" },
  { id: "de-beach-sonnencreme-sonnenhut", civilWord: "Sonnencreme", undercoverWord: "Sonnenhut", difficulty: "normal", category: "Strand" },
  { id: "de-beach-sandalen-badeschuhe", civilWord: "Sandalen", undercoverWord: "Badeschuhe", difficulty: "hard", category: "Strand" },
  { id: "de-beach-rettungsring-rettungsboot", civilWord: "Rettungsring", undercoverWord: "Rettungsboot", difficulty: "hard", category: "Strand" },
  { id: "de-beach-strandtuch-handtuch", civilWord: "Strandtuch", undercoverWord: "Handtuch", difficulty: "hard", category: "Strand" },
  { id: "de-beach-eimer-schaufel", civilWord: "Eimer", undercoverWord: "Schaufel", difficulty: "easy", category: "Strand" }
];

export const DE_WORD_CATEGORIES = [
  "Alle",
  "Essen",
  "Getränke",
  "Tiere",
  "Gegenstände",
  "Sport",
  "Popkultur",
  "Orte",
  "Natur",
  "Körper",
  "Kleidung",
  "Fahrzeuge",
  "Berufe",
  "Instrumente",
  "Technik",
  "Schule",
  "Zuhause",
  "Wetter",
  "Fantasie",
  "Weltraum",
  "Küche",
  "Garten",
  "Spielzeug",
  "Party",
  "Strand"
];
