import type { WordPair } from "../protocol.js";

export const EN_WORD_PAIRS: WordPair[] = [
  // ─── Food (30) ───
  { id: "en-food-pizza-pie", civilWord: "Pizza", undercoverWord: "Pie", difficulty: "normal", category: "Food" },
  { id: "en-food-sushi-sashimi", civilWord: "Sushi", undercoverWord: "Sashimi", difficulty: "hard", category: "Food" },
  { id: "en-food-burger-sandwich", civilWord: "Burger", undercoverWord: "Sandwich", difficulty: "easy", category: "Food" },
  { id: "en-food-donut-bagel", civilWord: "Donut", undercoverWord: "Bagel", difficulty: "normal", category: "Food" },
  { id: "en-food-pancake-waffle", civilWord: "Pancake", undercoverWord: "Waffle", difficulty: "hard", category: "Food" },
  { id: "en-food-fries-chips", civilWord: "Fries", undercoverWord: "Chips", difficulty: "hard", category: "Food" },
  { id: "en-food-taco-burrito", civilWord: "Taco", undercoverWord: "Burrito", difficulty: "hard", category: "Food" },
  { id: "en-food-cookie-brownie", civilWord: "Cookie", undercoverWord: "Brownie", difficulty: "normal", category: "Food" },
  { id: "en-food-cake-cupcake", civilWord: "Cake", undercoverWord: "Cupcake", difficulty: "normal", category: "Food" },
  { id: "en-food-icecream-gelato", civilWord: "Ice cream", undercoverWord: "Gelato", difficulty: "hard", category: "Food" },
  { id: "en-food-hotdog-corndog", civilWord: "Hot dog", undercoverWord: "Corn dog", difficulty: "normal", category: "Food" },
  { id: "en-food-popcorn-pretzel", civilWord: "Popcorn", undercoverWord: "Pretzel", difficulty: "normal", category: "Food" },
  { id: "en-food-steak-chop", civilWord: "Steak", undercoverWord: "Pork chop", difficulty: "normal", category: "Food" },
  { id: "en-food-pasta-noodles", civilWord: "Pasta", undercoverWord: "Noodles", difficulty: "easy", category: "Food" },
  { id: "en-food-bread-toast", civilWord: "Bread", undercoverWord: "Toast", difficulty: "easy", category: "Food" },
  { id: "en-food-cheese-butter", civilWord: "Cheese", undercoverWord: "Butter", difficulty: "normal", category: "Food" },
  { id: "en-food-candy-chocolate", civilWord: "Candy", undercoverWord: "Chocolate", difficulty: "easy", category: "Food" },
  { id: "en-food-croissant-muffin", civilWord: "Croissant", undercoverWord: "Muffin", difficulty: "normal", category: "Food" },
  { id: "en-food-nuggets-wings", civilWord: "Nuggets", undercoverWord: "Wings", difficulty: "normal", category: "Food" },
  { id: "en-food-soup-stew", civilWord: "Soup", undercoverWord: "Stew", difficulty: "hard", category: "Food" },
  { id: "en-food-egg-avocado", civilWord: "Fried egg", undercoverWord: "Avocado", difficulty: "normal", category: "Food" },
  { id: "en-food-apple-peach", civilWord: "Apple", undercoverWord: "Peach", difficulty: "hard", category: "Food" },
  { id: "en-food-banana-corn", civilWord: "Banana", undercoverWord: "Corn", difficulty: "normal", category: "Food" },
  { id: "en-food-watermelon-coconut", civilWord: "Watermelon", undercoverWord: "Coconut", difficulty: "normal", category: "Food" },
  { id: "en-food-onion-garlic", civilWord: "Onion", undercoverWord: "Garlic", difficulty: "hard", category: "Food" },
  { id: "en-food-cherry-grape", civilWord: "Cherry", undercoverWord: "Grape", difficulty: "hard", category: "Food" },
  { id: "en-food-carrot-pepper", civilWord: "Carrot", undercoverWord: "Chili pepper", difficulty: "normal", category: "Food" },
  { id: "en-food-dumpling-ravioli", civilWord: "Dumpling", undercoverWord: "Ravioli", difficulty: "hard", category: "Food" },
  { id: "en-food-popsicle-lollipop", civilWord: "Popsicle", undercoverWord: "Lollipop", difficulty: "normal", category: "Food" },
  { id: "en-food-spring-roll-egg-roll", civilWord: "Spring roll", undercoverWord: "Egg roll", difficulty: "hard", category: "Food" },

  // ─── Drinks (18) ───
  { id: "en-drink-coffee-tea", civilWord: "Coffee", undercoverWord: "Tea", difficulty: "easy", category: "Drinks" },
  { id: "en-drink-juice-smoothie", civilWord: "Juice", undercoverWord: "Smoothie", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-coke-pepsi", civilWord: "Coke", undercoverWord: "Pepsi", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-milk-yogurt", civilWord: "Milk", undercoverWord: "Yogurt", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-water-icecube", civilWord: "Water", undercoverWord: "Ice cube", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-hotchoco-latte", civilWord: "Hot chocolate", undercoverWord: "Latte", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-lemonade-iced", civilWord: "Lemonade", undercoverWord: "Iced tea", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-milkshake-frappuccino", civilWord: "Milkshake", undercoverWord: "Frappuccino", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-soda-sparkle", civilWord: "Soda", undercoverWord: "Sparkling water", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-beer-cider", civilWord: "Beer", undercoverWord: "Cider", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-bubbletea-boba", civilWord: "Bubble tea", undercoverWord: "Slushie", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-wine-grape", civilWord: "Wine", undercoverWord: "Grape juice", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-espresso-americano", civilWord: "Espresso", undercoverWord: "Americano", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-cocktail-mocktail", civilWord: "Cocktail", undercoverWord: "Mocktail", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-cappuccino-macchiato", civilWord: "Cappuccino", undercoverWord: "Macchiato", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-matcha-greentea", civilWord: "Matcha", undercoverWord: "Green tea", difficulty: "hard", category: "Drinks" },
  { id: "en-drink-coconutwater-aloedrink", civilWord: "Coconut water", undercoverWord: "Aloe drink", difficulty: "normal", category: "Drinks" },
  { id: "en-drink-champagne-prosecco", civilWord: "Champagne", undercoverWord: "Prosecco", difficulty: "hard", category: "Drinks" },

  // ─── Animals (28) ───
  { id: "en-animal-cat-tiger", civilWord: "Cat", undercoverWord: "Tiger", difficulty: "normal", category: "Animals" },
  { id: "en-animal-dog-wolf", civilWord: "Dog", undercoverWord: "Wolf", difficulty: "normal", category: "Animals" },
  { id: "en-animal-horse-zebra", civilWord: "Horse", undercoverWord: "Zebra", difficulty: "normal", category: "Animals" },
  { id: "en-animal-rabbit-hare", civilWord: "Rabbit", undercoverWord: "Hare", difficulty: "hard", category: "Animals" },
  { id: "en-animal-dolphin-whale", civilWord: "Dolphin", undercoverWord: "Whale", difficulty: "normal", category: "Animals" },
  { id: "en-animal-eagle-hawk", civilWord: "Eagle", undercoverWord: "Hawk", difficulty: "hard", category: "Animals" },
  { id: "en-animal-frog-toad", civilWord: "Frog", undercoverWord: "Toad", difficulty: "hard", category: "Animals" },
  { id: "en-animal-monkey-gorilla", civilWord: "Monkey", undercoverWord: "Gorilla", difficulty: "normal", category: "Animals" },
  { id: "en-animal-mouse-rat", civilWord: "Mouse", undercoverWord: "Rat", difficulty: "hard", category: "Animals" },
  { id: "en-animal-lion-leopard", civilWord: "Lion", undercoverWord: "Leopard", difficulty: "normal", category: "Animals" },
  { id: "en-animal-shark-dolphin", civilWord: "Shark", undercoverWord: "Swordfish", difficulty: "normal", category: "Animals" },
  { id: "en-animal-butterfly-moth", civilWord: "Butterfly", undercoverWord: "Moth", difficulty: "hard", category: "Animals" },
  { id: "en-animal-penguin-duck", civilWord: "Penguin", undercoverWord: "Duck", difficulty: "normal", category: "Animals" },
  { id: "en-animal-snake-worm", civilWord: "Snake", undercoverWord: "Worm", difficulty: "normal", category: "Animals" },
  { id: "en-animal-turtle-snail", civilWord: "Turtle", undercoverWord: "Snail", difficulty: "normal", category: "Animals" },
  { id: "en-animal-bear-panda", civilWord: "Bear", undercoverWord: "Panda", difficulty: "easy", category: "Animals" },
  { id: "en-animal-crocodile-lizard", civilWord: "Crocodile", undercoverWord: "Lizard", difficulty: "normal", category: "Animals" },
  { id: "en-animal-bee-wasp", civilWord: "Bee", undercoverWord: "Wasp", difficulty: "hard", category: "Animals" },
  { id: "en-animal-owl-parrot", civilWord: "Owl", undercoverWord: "Parrot", difficulty: "normal", category: "Animals" },
  { id: "en-animal-spider-ant", civilWord: "Spider", undercoverWord: "Ant", difficulty: "normal", category: "Animals" },
  { id: "en-animal-camel-llama", civilWord: "Camel", undercoverWord: "Llama", difficulty: "normal", category: "Animals" },
  { id: "en-animal-seal-otter", civilWord: "Seal", undercoverWord: "Otter", difficulty: "hard", category: "Animals" },
  { id: "en-animal-flamingo-crane", civilWord: "Flamingo", undercoverWord: "Crane", difficulty: "hard", category: "Animals" },
  { id: "en-animal-hedgehog-porcupine", civilWord: "Hedgehog", undercoverWord: "Porcupine", difficulty: "hard", category: "Animals" },
  { id: "en-animal-squid-octopus", civilWord: "Squid", undercoverWord: "Octopus", difficulty: "normal", category: "Animals" },
  { id: "en-animal-deer-moose", civilWord: "Deer", undercoverWord: "Moose", difficulty: "normal", category: "Animals" },
  { id: "en-animal-peacock-turkey", civilWord: "Peacock", undercoverWord: "Turkey", difficulty: "normal", category: "Animals" },
  { id: "en-animal-fox-coyote", civilWord: "Fox", undercoverWord: "Coyote", difficulty: "hard", category: "Animals" },

  // ─── Objects (24) ───
  { id: "en-obj-phone-tablet", civilWord: "Phone", undercoverWord: "Tablet", difficulty: "normal", category: "Objects" },
  { id: "en-obj-key-lock", civilWord: "Key", undercoverWord: "Lock", difficulty: "normal", category: "Objects" },
  { id: "en-obj-book-magazine", civilWord: "Book", undercoverWord: "Magazine", difficulty: "normal", category: "Objects" },
  { id: "en-obj-glasses-monocle", civilWord: "Glasses", undercoverWord: "Monocle", difficulty: "hard", category: "Objects" },
  { id: "en-obj-umbrella-parasol", civilWord: "Umbrella", undercoverWord: "Parasol", difficulty: "hard", category: "Objects" },
  { id: "en-obj-candle-lamp", civilWord: "Candle", undercoverWord: "Lamp", difficulty: "normal", category: "Objects" },
  { id: "en-obj-watch-clock", civilWord: "Watch", undercoverWord: "Clock", difficulty: "easy", category: "Objects" },
  { id: "en-obj-chair-stool", civilWord: "Chair", undercoverWord: "Stool", difficulty: "hard", category: "Objects" },
  { id: "en-obj-knife-sword", civilWord: "Knife", undercoverWord: "Sword", difficulty: "normal", category: "Objects" },
  { id: "en-obj-mirror-window", civilWord: "Mirror", undercoverWord: "Window", difficulty: "normal", category: "Objects" },
  { id: "en-obj-pillow-blanket", civilWord: "Pillow", undercoverWord: "Blanket", difficulty: "normal", category: "Objects" },
  { id: "en-obj-cup-mug", civilWord: "Cup", undercoverWord: "Mug", difficulty: "hard", category: "Objects" },
  { id: "en-obj-pencil-pen", civilWord: "Pencil", undercoverWord: "Pen", difficulty: "hard", category: "Objects" },
  { id: "en-obj-bag-backpack", civilWord: "Bag", undercoverWord: "Backpack", difficulty: "normal", category: "Objects" },
  { id: "en-obj-guitar-violin", civilWord: "Guitar", undercoverWord: "Violin", difficulty: "normal", category: "Objects" },
  { id: "en-obj-camera-binoculars", civilWord: "Camera", undercoverWord: "Binoculars", difficulty: "normal", category: "Objects" },
  { id: "en-obj-scissors-pliers", civilWord: "Scissors", undercoverWord: "Pliers", difficulty: "normal", category: "Objects" },
  { id: "en-obj-hammer-gavel", civilWord: "Hammer", undercoverWord: "Gavel", difficulty: "hard", category: "Objects" },
  { id: "en-obj-ladder-stairs", civilWord: "Ladder", undercoverWord: "Stairs", difficulty: "normal", category: "Objects" },
  { id: "en-obj-broom-mop", civilWord: "Broom", undercoverWord: "Mop", difficulty: "hard", category: "Objects" },
  { id: "en-obj-compass-protractor", civilWord: "Compass", undercoverWord: "Protractor", difficulty: "normal", category: "Objects" },
  { id: "en-obj-trophy-medal", civilWord: "Trophy", undercoverWord: "Medal", difficulty: "normal", category: "Objects" },
  { id: "en-obj-balloon-bubble", civilWord: "Balloon", undercoverWord: "Bubble", difficulty: "hard", category: "Objects" },
  { id: "en-obj-rope-chain", civilWord: "Rope", undercoverWord: "Chain", difficulty: "normal", category: "Objects" },

  // ─── Places (20) ───
  { id: "en-place-beach-pool", civilWord: "Beach", undercoverWord: "Pool", difficulty: "normal", category: "Places" },
  { id: "en-place-mountain-hill", civilWord: "Mountain", undercoverWord: "Hill", difficulty: "hard", category: "Places" },
  { id: "en-place-castle-palace", civilWord: "Castle", undercoverWord: "Palace", difficulty: "hard", category: "Places" },
  { id: "en-place-school-library", civilWord: "School", undercoverWord: "Library", difficulty: "normal", category: "Places" },
  { id: "en-place-hospital-pharmacy", civilWord: "Hospital", undercoverWord: "Pharmacy", difficulty: "normal", category: "Places" },
  { id: "en-place-park-garden", civilWord: "Park", undercoverWord: "Garden", difficulty: "hard", category: "Places" },
  { id: "en-place-cinema-theater", civilWord: "Cinema", undercoverWord: "Theater", difficulty: "hard", category: "Places" },
  { id: "en-place-gym-stadium", civilWord: "Gym", undercoverWord: "Stadium", difficulty: "normal", category: "Places" },
  { id: "en-place-airport-station", civilWord: "Airport", undercoverWord: "Train station", difficulty: "normal", category: "Places" },
  { id: "en-place-restaurant-cafe", civilWord: "Restaurant", undercoverWord: "Café", difficulty: "normal", category: "Places" },
  { id: "en-place-museum-gallery", civilWord: "Museum", undercoverWord: "Art gallery", difficulty: "hard", category: "Places" },
  { id: "en-place-forest-jungle", civilWord: "Forest", undercoverWord: "Jungle", difficulty: "normal", category: "Places" },
  { id: "en-place-island-peninsula", civilWord: "Island", undercoverWord: "Peninsula", difficulty: "hard", category: "Places" },
  { id: "en-place-volcano-geyser", civilWord: "Volcano", undercoverWord: "Geyser", difficulty: "hard", category: "Places" },
  { id: "en-place-lighthouse-watchtower", civilWord: "Lighthouse", undercoverWord: "Watchtower", difficulty: "hard", category: "Places" },
  { id: "en-place-barn-shed", civilWord: "Barn", undercoverWord: "Shed", difficulty: "hard", category: "Places" },
  { id: "en-place-igloo-tent", civilWord: "Igloo", undercoverWord: "Tent", difficulty: "normal", category: "Places" },
  { id: "en-place-bridge-tunnel", civilWord: "Bridge", undercoverWord: "Tunnel", difficulty: "normal", category: "Places" },
  { id: "en-place-pyramid-temple", civilWord: "Pyramid", undercoverWord: "Temple", difficulty: "normal", category: "Places" },
  { id: "en-place-zoo-aquarium", civilWord: "Zoo", undercoverWord: "Aquarium", difficulty: "normal", category: "Places" },

  // ─── Sports (20) ───
  { id: "en-sport-football-rugby", civilWord: "Football", undercoverWord: "Rugby", difficulty: "normal", category: "Sports" },
  { id: "en-sport-basketball-volleyball", civilWord: "Basketball", undercoverWord: "Volleyball", difficulty: "normal", category: "Sports" },
  { id: "en-sport-tennis-badminton", civilWord: "Tennis", undercoverWord: "Badminton", difficulty: "hard", category: "Sports" },
  { id: "en-sport-swimming-diving", civilWord: "Swimming", undercoverWord: "Diving", difficulty: "normal", category: "Sports" },
  { id: "en-sport-skiing-snowboard", civilWord: "Skiing", undercoverWord: "Snowboarding", difficulty: "normal", category: "Sports" },
  { id: "en-sport-boxing-wrestling", civilWord: "Boxing", undercoverWord: "Wrestling", difficulty: "normal", category: "Sports" },
  { id: "en-sport-soccer-hockey", civilWord: "Soccer", undercoverWord: "Hockey", difficulty: "normal", category: "Sports" },
  { id: "en-sport-skateboard-rollerblading", civilWord: "Skateboard", undercoverWord: "Roller skates", difficulty: "normal", category: "Sports" },
  { id: "en-sport-surfing-kayak", civilWord: "Surfing", undercoverWord: "Kayaking", difficulty: "normal", category: "Sports" },
  { id: "en-sport-golf-bowling", civilWord: "Golf", undercoverWord: "Bowling", difficulty: "normal", category: "Sports" },
  { id: "en-sport-archery-darts", civilWord: "Archery", undercoverWord: "Darts", difficulty: "normal", category: "Sports" },
  { id: "en-sport-cycling-scooting", civilWord: "Cycling", undercoverWord: "Scooter", difficulty: "normal", category: "Sports" },
  { id: "en-sport-fencing-karate", civilWord: "Fencing", undercoverWord: "Karate", difficulty: "normal", category: "Sports" },
  { id: "en-sport-climbing-hiking", civilWord: "Climbing", undercoverWord: "Hiking", difficulty: "hard", category: "Sports" },
  { id: "en-sport-baseball-cricket", civilWord: "Baseball", undercoverWord: "Cricket", difficulty: "hard", category: "Sports" },
  { id: "en-sport-pingpong-squash", civilWord: "Ping pong", undercoverWord: "Squash", difficulty: "hard", category: "Sports" },
  { id: "en-sport-trampoline-gymnastics", civilWord: "Trampoline", undercoverWord: "Gymnastics", difficulty: "normal", category: "Sports" },
  { id: "en-sport-polo-lacrosse", civilWord: "Polo", undercoverWord: "Lacrosse", difficulty: "normal", category: "Sports" },
  { id: "en-sport-judo-sumo", civilWord: "Judo", undercoverWord: "Sumo", difficulty: "normal", category: "Sports" },
  { id: "en-sport-rowing-canoeing", civilWord: "Rowing", undercoverWord: "Canoeing", difficulty: "hard", category: "Sports" },

  // ─── Jobs (20) ───
  { id: "en-job-doctor-nurse", civilWord: "Doctor", undercoverWord: "Nurse", difficulty: "normal", category: "Jobs" },
  { id: "en-job-chef-baker", civilWord: "Chef", undercoverWord: "Baker", difficulty: "hard", category: "Jobs" },
  { id: "en-job-teacher-professor", civilWord: "Teacher", undercoverWord: "Professor", difficulty: "hard", category: "Jobs" },
  { id: "en-job-pilot-captain", civilWord: "Pilot", undercoverWord: "Captain", difficulty: "normal", category: "Jobs" },
  { id: "en-job-police-detective", civilWord: "Police", undercoverWord: "Detective", difficulty: "normal", category: "Jobs" },
  { id: "en-job-firefighter-paramedic", civilWord: "Firefighter", undercoverWord: "Paramedic", difficulty: "normal", category: "Jobs" },
  { id: "en-job-painter-sculptor", civilWord: "Painter", undercoverWord: "Sculptor", difficulty: "normal", category: "Jobs" },
  { id: "en-job-astronaut-diver", civilWord: "Astronaut", undercoverWord: "Diver", difficulty: "normal", category: "Jobs" },
  { id: "en-job-farmer-gardener", civilWord: "Farmer", undercoverWord: "Gardener", difficulty: "normal", category: "Jobs" },
  { id: "en-job-musician-singer", civilWord: "Musician", undercoverWord: "Singer", difficulty: "hard", category: "Jobs" },
  { id: "en-job-wizard-witch", civilWord: "Wizard", undercoverWord: "Witch", difficulty: "easy", category: "Jobs" },
  { id: "en-job-pirate-viking", civilWord: "Pirate", undercoverWord: "Viking", difficulty: "normal", category: "Jobs" },
  { id: "en-job-ninja-samurai", civilWord: "Ninja", undercoverWord: "Samurai", difficulty: "normal", category: "Jobs" },
  { id: "en-job-king-emperor", civilWord: "King", undercoverWord: "Emperor", difficulty: "hard", category: "Jobs" },
  { id: "en-job-dentist-surgeon", civilWord: "Dentist", undercoverWord: "Surgeon", difficulty: "normal", category: "Jobs" },
  { id: "en-job-clown-jester", civilWord: "Clown", undercoverWord: "Jester", difficulty: "hard", category: "Jobs" },
  { id: "en-job-mailman-deliveryman", civilWord: "Mailman", undercoverWord: "Delivery driver", difficulty: "normal", category: "Jobs" },
  { id: "en-job-waiter-bartender", civilWord: "Waiter", undercoverWord: "Bartender", difficulty: "normal", category: "Jobs" },
  { id: "en-job-carpenter-blacksmith", civilWord: "Carpenter", undercoverWord: "Blacksmith", difficulty: "normal", category: "Jobs" },
  { id: "en-job-lifeguard-swimmer", civilWord: "Lifeguard", undercoverWord: "Swimmer", difficulty: "hard", category: "Jobs" },

  // ─── Transport (16) ───
  { id: "en-trans-car-truck", civilWord: "Car", undercoverWord: "Truck", difficulty: "normal", category: "Transport" },
  { id: "en-trans-train-metro", civilWord: "Train", undercoverWord: "Metro", difficulty: "hard", category: "Transport" },
  { id: "en-trans-bicycle-scooter", civilWord: "Bicycle", undercoverWord: "Scooter", difficulty: "normal", category: "Transport" },
  { id: "en-trans-plane-helicopter", civilWord: "Plane", undercoverWord: "Helicopter", difficulty: "normal", category: "Transport" },
  { id: "en-trans-boat-yacht", civilWord: "Boat", undercoverWord: "Yacht", difficulty: "normal", category: "Transport" },
  { id: "en-trans-bus-trolley", civilWord: "Bus", undercoverWord: "Trolley", difficulty: "hard", category: "Transport" },
  { id: "en-trans-rocket-shuttle", civilWord: "Rocket", undercoverWord: "Space shuttle", difficulty: "hard", category: "Transport" },
  { id: "en-trans-skateboard-rollerblade", civilWord: "Skateboard", undercoverWord: "Rollerblades", difficulty: "normal", category: "Transport" },
  { id: "en-trans-submarine-bathyscaphe", civilWord: "Submarine", undercoverWord: "Bathyscaphe", difficulty: "hard", category: "Transport" },
  { id: "en-trans-motorcycle-moped", civilWord: "Motorcycle", undercoverWord: "Moped", difficulty: "hard", category: "Transport" },
  { id: "en-trans-ambulance-firetruck", civilWord: "Ambulance", undercoverWord: "Fire truck", difficulty: "normal", category: "Transport" },
  { id: "en-trans-sled-toboggan", civilWord: "Sled", undercoverWord: "Toboggan", difficulty: "hard", category: "Transport" },
  { id: "en-trans-canoe-kayak", civilWord: "Canoe", undercoverWord: "Kayak", difficulty: "hard", category: "Transport" },
  { id: "en-trans-hotairballoon-blimp", civilWord: "Hot air balloon", undercoverWord: "Blimp", difficulty: "normal", category: "Transport" },
  { id: "en-trans-wagon-carriage", civilWord: "Wagon", undercoverWord: "Carriage", difficulty: "hard", category: "Transport" },
  { id: "en-trans-segway-hoverboard", civilWord: "Segway", undercoverWord: "Hoverboard", difficulty: "normal", category: "Transport" },

  // ─── Nature (18) ───
  { id: "en-nature-sun-moon", civilWord: "Sun", undercoverWord: "Moon", difficulty: "easy", category: "Nature" },
  { id: "en-nature-tree-bush", civilWord: "Tree", undercoverWord: "Bush", difficulty: "normal", category: "Nature" },
  { id: "en-nature-river-lake", civilWord: "River", undercoverWord: "Lake", difficulty: "hard", category: "Nature" },
  { id: "en-nature-rainbow-aurora", civilWord: "Rainbow", undercoverWord: "Aurora", difficulty: "hard", category: "Nature" },
  { id: "en-nature-star-planet", civilWord: "Star", undercoverWord: "Planet", difficulty: "normal", category: "Nature" },
  { id: "en-nature-rain-snow", civilWord: "Rain", undercoverWord: "Snow", difficulty: "easy", category: "Nature" },
  { id: "en-nature-flower-mushroom", civilWord: "Flower", undercoverWord: "Mushroom", difficulty: "normal", category: "Nature" },
  { id: "en-nature-volcano-mountain", civilWord: "Volcano", undercoverWord: "Mountain", difficulty: "normal", category: "Nature" },
  { id: "en-nature-tornado-hurricane", civilWord: "Tornado", undercoverWord: "Hurricane", difficulty: "hard", category: "Nature" },
  { id: "en-nature-desert-tundra", civilWord: "Desert", undercoverWord: "Tundra", difficulty: "hard", category: "Nature" },
  { id: "en-nature-cloud-fog", civilWord: "Cloud", undercoverWord: "Fog", difficulty: "hard", category: "Nature" },
  { id: "en-nature-wave-waterfall", civilWord: "Wave", undercoverWord: "Waterfall", difficulty: "normal", category: "Nature" },
  { id: "en-nature-cactus-palm", civilWord: "Cactus", undercoverWord: "Palm tree", difficulty: "normal", category: "Nature" },
  { id: "en-nature-rose-tulip", civilWord: "Rose", undercoverWord: "Tulip", difficulty: "hard", category: "Nature" },
  { id: "en-nature-stalactite-stalagmite", civilWord: "Stalactite", undercoverWord: "Stalagmite", difficulty: "hard", category: "Nature" },
  { id: "en-nature-lightning-thunder", civilWord: "Lightning", undercoverWord: "Thunder cloud", difficulty: "normal", category: "Nature" },
  { id: "en-nature-coral-seaweed", civilWord: "Coral", undercoverWord: "Seaweed", difficulty: "normal", category: "Nature" },
  { id: "en-nature-iceberg-glacier", civilWord: "Iceberg", undercoverWord: "Glacier", difficulty: "hard", category: "Nature" },

  // ─── Pop Culture (20) ───
  { id: "en-pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Pop Culture" },
  { id: "en-pop-batman-spiderman", civilWord: "Batman", undercoverWord: "Spider-Man", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-pikachu-eevee", civilWord: "Pikachu", undercoverWord: "Eevee", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-elsa-rapunzel", civilWord: "Elsa", undercoverWord: "Rapunzel", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-shrek-hulk", civilWord: "Shrek", undercoverWord: "Hulk", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-darth-vader-voldemort", civilWord: "Darth Vader", undercoverWord: "Voldemort", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-goku-naruto", civilWord: "Goku", undercoverWord: "Naruto", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-spongebob-patrick", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "easy", category: "Pop Culture" },
  { id: "en-pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-amongus-werewolf", civilWord: "Among Us", undercoverWord: "Werewolf", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-harry-frodo", civilWord: "Harry Potter", undercoverWord: "Frodo", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-yoda-gandalf", civilWord: "Yoda", undercoverWord: "Gandalf", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-ironman-captain", civilWord: "Iron Man", undercoverWord: "Captain America", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-totoro-stitch", civilWord: "Totoro", undercoverWord: "Stitch", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-superman-thor", civilWord: "Superman", undercoverWord: "Thor", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-mickey-bugs", civilWord: "Mickey Mouse", undercoverWord: "Bugs Bunny", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-kirby-jigglypuff", civilWord: "Kirby", undercoverWord: "Jigglypuff", difficulty: "hard", category: "Pop Culture" },
  { id: "en-pop-link-zelda", civilWord: "Link", undercoverWord: "Zelda", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-r2d2-walle", civilWord: "R2-D2", undercoverWord: "WALL-E", difficulty: "normal", category: "Pop Culture" },
  { id: "en-pop-pacman-ghost", civilWord: "Pac-Man", undercoverWord: "Ghost", difficulty: "easy", category: "Pop Culture" },

  // ─── Technology (16) ───
  { id: "en-tech-robot-cyborg", civilWord: "Robot", undercoverWord: "Cyborg", difficulty: "hard", category: "Technology" },
  { id: "en-tech-laptop-desktop", civilWord: "Laptop", undercoverWord: "Desktop", difficulty: "hard", category: "Technology" },
  { id: "en-tech-keyboard-piano", civilWord: "Keyboard", undercoverWord: "Piano", difficulty: "normal", category: "Technology" },
  { id: "en-tech-tv-monitor", civilWord: "TV", undercoverWord: "Monitor", difficulty: "hard", category: "Technology" },
  { id: "en-tech-headphones-earbuds", civilWord: "Headphones", undercoverWord: "Earbuds", difficulty: "hard", category: "Technology" },
  { id: "en-tech-controller-joystick", civilWord: "Controller", undercoverWord: "Joystick", difficulty: "normal", category: "Technology" },
  { id: "en-tech-printer-scanner", civilWord: "Printer", undercoverWord: "Scanner", difficulty: "hard", category: "Technology" },
  { id: "en-tech-wifi-bluetooth", civilWord: "Wi-Fi", undercoverWord: "Bluetooth", difficulty: "hard", category: "Technology" },
  { id: "en-tech-drone-helicopter", civilWord: "Drone", undercoverWord: "RC helicopter", difficulty: "normal", category: "Technology" },
  { id: "en-tech-vr-3dglasses", civilWord: "VR headset", undercoverWord: "3D glasses", difficulty: "normal", category: "Technology" },
  { id: "en-tech-smartwatch-fitnesstracker", civilWord: "Smartwatch", undercoverWord: "Fitness tracker", difficulty: "hard", category: "Technology" },
  { id: "en-tech-projector-screen", civilWord: "Projector", undercoverWord: "TV screen", difficulty: "normal", category: "Technology" },
  { id: "en-tech-usb-charger", civilWord: "USB stick", undercoverWord: "Charger", difficulty: "normal", category: "Technology" },
  { id: "en-tech-speaker-microphone", civilWord: "Speaker", undercoverWord: "Microphone", difficulty: "normal", category: "Technology" },
  { id: "en-tech-webcam-securitycam", civilWord: "Webcam", undercoverWord: "Security camera", difficulty: "hard", category: "Technology" },
  { id: "en-tech-satellite-antenna", civilWord: "Satellite dish", undercoverWord: "Antenna", difficulty: "normal", category: "Technology" },

  // ─── Clothing (20) ───
  { id: "en-clothing-hat-cap", civilWord: "Hat", undercoverWord: "Cap", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-boots-shoes", civilWord: "Boots", undercoverWord: "Shoes", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-scarf-tie", civilWord: "Scarf", undercoverWord: "Tie", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-jacket-coat", civilWord: "Jacket", undercoverWord: "Coat", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-gloves-mittens", civilWord: "Gloves", undercoverWord: "Mittens", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-dress-skirt", civilWord: "Dress", undercoverWord: "Skirt", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-sandals-flipflops", civilWord: "Sandals", undercoverWord: "Flip-flops", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-hoodie-sweater", civilWord: "Hoodie", undercoverWord: "Sweater", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-vest-tanktop", civilWord: "Vest", undercoverWord: "Tank top", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-crown-tiara", civilWord: "Crown", undercoverWord: "Tiara", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-belt-suspenders", civilWord: "Belt", undercoverWord: "Suspenders", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-sunglasses-goggles", civilWord: "Sunglasses", undercoverWord: "Goggles", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-shorts-pants", civilWord: "Shorts", undercoverWord: "Pants", difficulty: "easy", category: "Clothing" },
  { id: "en-clothing-raincoat-poncho", civilWord: "Raincoat", undercoverWord: "Poncho", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-socks-stockings", civilWord: "Socks", undercoverWord: "Stockings", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-helmet-hardhat", civilWord: "Helmet", undercoverWord: "Hard hat", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-tuxedo-suit", civilWord: "Tuxedo", undercoverWord: "Suit", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-kimono-bathrobe", civilWord: "Kimono", undercoverWord: "Bathrobe", difficulty: "normal", category: "Clothing" },
  { id: "en-clothing-beanie-beret", civilWord: "Beanie", undercoverWord: "Beret", difficulty: "hard", category: "Clothing" },
  { id: "en-clothing-necklace-choker", civilWord: "Necklace", undercoverWord: "Choker", difficulty: "hard", category: "Clothing" },

  // ─── Music (18) ───
  { id: "en-music-piano-organ", civilWord: "Piano", undercoverWord: "Organ", difficulty: "normal", category: "Music" },
  { id: "en-music-drums-bongos", civilWord: "Drums", undercoverWord: "Bongos", difficulty: "normal", category: "Music" },
  { id: "en-music-trumpet-trombone", civilWord: "Trumpet", undercoverWord: "Trombone", difficulty: "hard", category: "Music" },
  { id: "en-music-flute-clarinet", civilWord: "Flute", undercoverWord: "Clarinet", difficulty: "hard", category: "Music" },
  { id: "en-music-harp-lyre", civilWord: "Harp", undercoverWord: "Lyre", difficulty: "hard", category: "Music" },
  { id: "en-music-ukulele-banjo", civilWord: "Ukulele", undercoverWord: "Banjo", difficulty: "hard", category: "Music" },
  { id: "en-music-accordion-harmonica", civilWord: "Accordion", undercoverWord: "Harmonica", difficulty: "normal", category: "Music" },
  { id: "en-music-cello-doublebass", civilWord: "Cello", undercoverWord: "Double bass", difficulty: "hard", category: "Music" },
  { id: "en-music-tambourine-maracas", civilWord: "Tambourine", undercoverWord: "Maracas", difficulty: "normal", category: "Music" },
  { id: "en-music-saxophone-oboe", civilWord: "Saxophone", undercoverWord: "Oboe", difficulty: "hard", category: "Music" },
  { id: "en-music-xylophone-glockenspiel", civilWord: "Xylophone", undercoverWord: "Glockenspiel", difficulty: "hard", category: "Music" },
  { id: "en-music-violin-viola", civilWord: "Violin", undercoverWord: "Viola", difficulty: "hard", category: "Music" },
  { id: "en-music-electricguitar-bass", civilWord: "Electric guitar", undercoverWord: "Bass guitar", difficulty: "hard", category: "Music" },
  { id: "en-music-bagpipes-didgeridoo", civilWord: "Bagpipes", undercoverWord: "Didgeridoo", difficulty: "normal", category: "Music" },
  { id: "en-music-triangle-cowbell", civilWord: "Triangle", undercoverWord: "Cowbell", difficulty: "normal", category: "Music" },
  { id: "en-music-vinyl-cd", civilWord: "Vinyl record", undercoverWord: "CD", difficulty: "normal", category: "Music" },
  { id: "en-music-headphones-speakers", civilWord: "Headphones", undercoverWord: "Speakers", difficulty: "normal", category: "Music" },
  { id: "en-music-microphone-megaphone", civilWord: "Microphone", undercoverWord: "Megaphone", difficulty: "normal", category: "Music" },

  // ─── Home (20) ───
  { id: "en-home-bed-couch", civilWord: "Bed", undercoverWord: "Couch", difficulty: "normal", category: "Home" },
  { id: "en-home-bathtub-shower", civilWord: "Bathtub", undercoverWord: "Shower", difficulty: "normal", category: "Home" },
  { id: "en-home-oven-microwave", civilWord: "Oven", undercoverWord: "Microwave", difficulty: "normal", category: "Home" },
  { id: "en-home-fridge-freezer", civilWord: "Fridge", undercoverWord: "Freezer", difficulty: "hard", category: "Home" },
  { id: "en-home-sofa-armchair", civilWord: "Sofa", undercoverWord: "Armchair", difficulty: "hard", category: "Home" },
  { id: "en-home-curtain-blinds", civilWord: "Curtain", undercoverWord: "Blinds", difficulty: "hard", category: "Home" },
  { id: "en-home-sink-toilet", civilWord: "Sink", undercoverWord: "Toilet", difficulty: "normal", category: "Home" },
  { id: "en-home-closet-drawer", civilWord: "Closet", undercoverWord: "Drawer", difficulty: "normal", category: "Home" },
  { id: "en-home-shelf-cabinet", civilWord: "Shelf", undercoverWord: "Cabinet", difficulty: "hard", category: "Home" },
  { id: "en-home-chandelier-lampshade", civilWord: "Chandelier", undercoverWord: "Lamp shade", difficulty: "normal", category: "Home" },
  { id: "en-home-doorbell-knocker", civilWord: "Doorbell", undercoverWord: "Door knocker", difficulty: "normal", category: "Home" },
  { id: "en-home-chimney-vent", civilWord: "Chimney", undercoverWord: "Vent", difficulty: "normal", category: "Home" },
  { id: "en-home-fence-wall", civilWord: "Fence", undercoverWord: "Wall", difficulty: "hard", category: "Home" },
  { id: "en-home-fireplace-radiator", civilWord: "Fireplace", undercoverWord: "Radiator", difficulty: "normal", category: "Home" },
  { id: "en-home-doormat-carpet", civilWord: "Doormat", undercoverWord: "Carpet", difficulty: "hard", category: "Home" },
  { id: "en-home-teapot-kettle", civilWord: "Teapot", undercoverWord: "Kettle", difficulty: "hard", category: "Home" },
  { id: "en-home-fork-spoon", civilWord: "Fork", undercoverWord: "Spoon", difficulty: "easy", category: "Home" },
  { id: "en-home-plate-bowl", civilWord: "Plate", undercoverWord: "Bowl", difficulty: "normal", category: "Home" },
  { id: "en-home-vase-flowerpot", civilWord: "Vase", undercoverWord: "Flower pot", difficulty: "hard", category: "Home" },
  { id: "en-home-toaster-waffle-iron", civilWord: "Toaster", undercoverWord: "Waffle iron", difficulty: "normal", category: "Home" },

  // ─── Holidays (20) ───
  { id: "en-holiday-santa-snowman", civilWord: "Santa", undercoverWord: "Snowman", difficulty: "easy", category: "Holidays" },
  { id: "en-holiday-christmas-tree-palm-tree", civilWord: "Christmas tree", undercoverWord: "Palm tree", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-pumpkin-lantern", civilWord: "Pumpkin", undercoverWord: "Jack-o-lantern", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-ghost-skeleton", civilWord: "Ghost", undercoverWord: "Skeleton", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-egg-bunny", civilWord: "Easter egg", undercoverWord: "Easter bunny", difficulty: "easy", category: "Holidays" },
  { id: "en-holiday-fireworks-sparkler", civilWord: "Fireworks", undercoverWord: "Sparkler", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-wreath-garland", civilWord: "Wreath", undercoverWord: "Garland", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-candy-cane-stick", civilWord: "Candy cane", undercoverWord: "Walking stick", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-reindeer-elk", civilWord: "Reindeer", undercoverWord: "Elk", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-stocking-sock", civilWord: "Christmas stocking", undercoverWord: "Sock", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-present-box", civilWord: "Gift", undercoverWord: "Box", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-vampire-dracula", civilWord: "Vampire", undercoverWord: "Bat", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-witch-wizard", civilWord: "Witch hat", undercoverWord: "Wizard hat", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-menorah-candelabra", civilWord: "Menorah", undercoverWord: "Candelabra", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-turkey-chicken", civilWord: "Roast turkey", undercoverWord: "Roast chicken", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-snowflake-star", civilWord: "Snowflake", undercoverWord: "Star", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-sleigh-sled", civilWord: "Sleigh", undercoverWord: "Sled", difficulty: "hard", category: "Holidays" },
  { id: "en-holiday-angel-fairy", civilWord: "Angel", undercoverWord: "Fairy", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-mummy-zombie", civilWord: "Mummy", undercoverWord: "Zombie", difficulty: "normal", category: "Holidays" },
  { id: "en-holiday-gingerbread-cookie", civilWord: "Gingerbread man", undercoverWord: "Cookie", difficulty: "normal", category: "Holidays" }
];

export const EN_WORD_CATEGORIES = [
  "All",
  "Food",
  "Drinks",
  "Animals",
  "Objects",
  "Places",
  "Sports",
  "Jobs",
  "Transport",
  "Nature",
  "Pop Culture",
  "Technology",
  "Clothing",
  "Music",
  "Home",
  "Holidays"
];
