import type { WordPair } from "../protocol.js";

export const ES_WORD_PAIRS: WordPair[] = [
  // ─── Comida (30) ───
  { id: "es-food-pizza-empanada", civilWord: "Pizza", undercoverWord: "Empanada", difficulty: "normal", category: "Comida" },
  { id: "es-food-sushi-ceviche", civilWord: "Sushi", undercoverWord: "Ceviche", difficulty: "hard", category: "Comida" },
  { id: "es-food-hamburguesa-bocadillo", civilWord: "Hamburguesa", undercoverWord: "Bocadillo", difficulty: "easy", category: "Comida" },
  { id: "es-food-churros-donut", civilWord: "Churros", undercoverWord: "Donut", difficulty: "normal", category: "Comida" },
  { id: "es-food-tortilla-crepe", civilWord: "Tortilla", undercoverWord: "Crêpe", difficulty: "normal", category: "Comida" },
  { id: "es-food-paella-risotto", civilWord: "Paella", undercoverWord: "Risotto", difficulty: "hard", category: "Comida" },
  { id: "es-food-taco-burrito", civilWord: "Taco", undercoverWord: "Burrito", difficulty: "hard", category: "Comida" },
  { id: "es-food-galleta-brownie", civilWord: "Galleta", undercoverWord: "Brownie", difficulty: "normal", category: "Comida" },
  { id: "es-food-pastel-cupcake", civilWord: "Pastel", undercoverWord: "Cupcake", difficulty: "normal", category: "Comida" },
  { id: "es-food-helado-sorbete", civilWord: "Helado", undercoverWord: "Sorbete", difficulty: "hard", category: "Comida" },
  { id: "es-food-patatas-nachos", civilWord: "Patatas fritas", undercoverWord: "Nachos", difficulty: "normal", category: "Comida" },
  { id: "es-food-queso-mantequilla", civilWord: "Queso", undercoverWord: "Mantequilla", difficulty: "normal", category: "Comida" },
  { id: "es-food-pan-tostada", civilWord: "Pan", undercoverWord: "Tostada", difficulty: "easy", category: "Comida" },
  { id: "es-food-caramelo-chocolate", civilWord: "Caramelo", undercoverWord: "Chocolate", difficulty: "easy", category: "Comida" },
  { id: "es-food-sopa-caldo", civilWord: "Sopa", undercoverWord: "Caldo", difficulty: "hard", category: "Comida" },
  { id: "es-food-pasta-fideos", civilWord: "Pasta", undercoverWord: "Fideos", difficulty: "hard", category: "Comida" },
  { id: "es-food-pollo-pavo", civilWord: "Pollo asado", undercoverWord: "Pavo", difficulty: "normal", category: "Comida" },
  { id: "es-food-croissant-magdalena", civilWord: "Croissant", undercoverWord: "Magdalena", difficulty: "normal", category: "Comida" },
  { id: "es-food-arepa-pupusa", civilWord: "Arepa", undercoverWord: "Pupusa", difficulty: "hard", category: "Comida" },
  { id: "es-food-tamales-humita", civilWord: "Tamales", undercoverWord: "Humita", difficulty: "hard", category: "Comida" },
  { id: "es-food-enchilada-quesadilla", civilWord: "Enchilada", undercoverWord: "Quesadilla", difficulty: "normal", category: "Comida" },
  { id: "es-food-flan-natilla", civilWord: "Flan", undercoverWord: "Natilla", difficulty: "hard", category: "Comida" },
  { id: "es-food-jamon-salchichon", civilWord: "Jamón", undercoverWord: "Salchichón", difficulty: "normal", category: "Comida" },
  { id: "es-food-tortilla-espanola-frittata", civilWord: "Tortilla española", undercoverWord: "Frittata", difficulty: "hard", category: "Comida" },
  { id: "es-food-croqueta-nugget", civilWord: "Croqueta", undercoverWord: "Nugget", difficulty: "normal", category: "Comida" },
  { id: "es-food-gazpacho-salmorejo", civilWord: "Gazpacho", undercoverWord: "Salmorejo", difficulty: "hard", category: "Comida" },
  { id: "es-food-empanada-calzone", civilWord: "Empanada gallega", undercoverWord: "Calzone", difficulty: "normal", category: "Comida" },
  { id: "es-food-asado-barbacoa", civilWord: "Asado", undercoverWord: "Barbacoa", difficulty: "hard", category: "Comida" },
  { id: "es-food-manzana-pera", civilWord: "Manzana", undercoverWord: "Pera", difficulty: "hard", category: "Comida" },
  { id: "es-food-sandia-melon", civilWord: "Sandía", undercoverWord: "Melón", difficulty: "hard", category: "Comida" },

  // ─── Bebidas (20) ───
  { id: "es-drink-cafe-te", civilWord: "Café", undercoverWord: "Té", difficulty: "easy", category: "Bebidas" },
  { id: "es-drink-zumo-batido", civilWord: "Zumo", undercoverWord: "Batido", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-coca-fanta", civilWord: "Coca-Cola", undercoverWord: "Fanta", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-leche-yogur", civilWord: "Leche", undercoverWord: "Yogur", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-agua-hielo", civilWord: "Agua", undercoverWord: "Hielo", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-chocolate-cafe-latte", civilWord: "Chocolate caliente", undercoverWord: "Café con leche", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-limonada-naranjada", civilWord: "Limonada", undercoverWord: "Naranjada", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-cerveza-sidra", civilWord: "Cerveza", undercoverWord: "Sidra", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-sangria-tinto", civilWord: "Sangría", undercoverWord: "Tinto de verano", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-horchata-granizado", civilWord: "Horchata", undercoverWord: "Granizado", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-mate-te-verde", civilWord: "Mate", undercoverWord: "Té verde", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-mojito-caipirinha", civilWord: "Mojito", undercoverWord: "Caipiriña", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-agua-mineral-tonica", civilWord: "Agua mineral", undercoverWord: "Tónica", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-cappuccino-cortado", civilWord: "Cappuccino", undercoverWord: "Cortado", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-smoothie-licuado", civilWord: "Smoothie", undercoverWord: "Licuado", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-vino-champan", civilWord: "Vino", undercoverWord: "Champán", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-refresco-gaseosa", civilWord: "Refresco", undercoverWord: "Gaseosa", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-margarita-pina-colada", civilWord: "Margarita", undercoverWord: "Piña colada", difficulty: "normal", category: "Bebidas" },
  { id: "es-drink-cafe-espresso-americano", civilWord: "Espresso", undercoverWord: "Americano", difficulty: "hard", category: "Bebidas" },
  { id: "es-drink-chicha-pulque", civilWord: "Chicha", undercoverWord: "Pulque", difficulty: "hard", category: "Bebidas" },

  // ─── Animales (30) ───
  { id: "es-animal-gato-tigre", civilWord: "Gato", undercoverWord: "Tigre", difficulty: "normal", category: "Animales" },
  { id: "es-animal-perro-lobo", civilWord: "Perro", undercoverWord: "Lobo", difficulty: "normal", category: "Animales" },
  { id: "es-animal-caballo-cebra", civilWord: "Caballo", undercoverWord: "Cebra", difficulty: "normal", category: "Animales" },
  { id: "es-animal-conejo-liebre", civilWord: "Conejo", undercoverWord: "Liebre", difficulty: "hard", category: "Animales" },
  { id: "es-animal-delfin-ballena", civilWord: "Delfín", undercoverWord: "Ballena", difficulty: "normal", category: "Animales" },
  { id: "es-animal-aguila-halcon", civilWord: "Águila", undercoverWord: "Halcón", difficulty: "hard", category: "Animales" },
  { id: "es-animal-rana-sapo", civilWord: "Rana", undercoverWord: "Sapo", difficulty: "hard", category: "Animales" },
  { id: "es-animal-mono-gorila", civilWord: "Mono", undercoverWord: "Gorila", difficulty: "normal", category: "Animales" },
  { id: "es-animal-raton-rata", civilWord: "Ratón", undercoverWord: "Rata", difficulty: "hard", category: "Animales" },
  { id: "es-animal-leon-leopardo", civilWord: "León", undercoverWord: "Leopardo", difficulty: "normal", category: "Animales" },
  { id: "es-animal-tiburon-pez-espada", civilWord: "Tiburón", undercoverWord: "Pez espada", difficulty: "normal", category: "Animales" },
  { id: "es-animal-mariposa-polilla", civilWord: "Mariposa", undercoverWord: "Polilla", difficulty: "hard", category: "Animales" },
  { id: "es-animal-pinguino-pato", civilWord: "Pingüino", undercoverWord: "Pato", difficulty: "normal", category: "Animales" },
  { id: "es-animal-serpiente-gusano", civilWord: "Serpiente", undercoverWord: "Gusano", difficulty: "normal", category: "Animales" },
  { id: "es-animal-tortuga-caracol", civilWord: "Tortuga", undercoverWord: "Caracol", difficulty: "normal", category: "Animales" },
  { id: "es-animal-oso-panda", civilWord: "Oso", undercoverWord: "Panda", difficulty: "easy", category: "Animales" },
  { id: "es-animal-abeja-avispa", civilWord: "Abeja", undercoverWord: "Avispa", difficulty: "hard", category: "Animales" },
  { id: "es-animal-buho-loro", civilWord: "Búho", undercoverWord: "Loro", difficulty: "normal", category: "Animales" },
  { id: "es-animal-llama-alpaca", civilWord: "Llama", undercoverWord: "Alpaca", difficulty: "hard", category: "Animales" },
  { id: "es-animal-cocodrilo-lagarto", civilWord: "Cocodrilo", undercoverWord: "Lagarto", difficulty: "normal", category: "Animales" },
  { id: "es-animal-flamenco-garza", civilWord: "Flamenco", undercoverWord: "Garza", difficulty: "hard", category: "Animales" },
  { id: "es-animal-cangrejo-langosta", civilWord: "Cangrejo", undercoverWord: "Langosta", difficulty: "normal", category: "Animales" },
  { id: "es-animal-jirafa-avestruz", civilWord: "Jirafa", undercoverWord: "Avestruz", difficulty: "easy", category: "Animales" },
  { id: "es-animal-cabra-oveja", civilWord: "Cabra", undercoverWord: "Oveja", difficulty: "hard", category: "Animales" },
  { id: "es-animal-pulpo-medusa", civilWord: "Pulpo", undercoverWord: "Medusa", difficulty: "normal", category: "Animales" },
  { id: "es-animal-tucan-papagayo", civilWord: "Tucán", undercoverWord: "Papagayo", difficulty: "hard", category: "Animales" },
  { id: "es-animal-murcielago-golondrina", civilWord: "Murciélago", undercoverWord: "Golondrina", difficulty: "normal", category: "Animales" },
  { id: "es-animal-hipopotamo-rinoceronte", civilWord: "Hipopótamo", undercoverWord: "Rinoceronte", difficulty: "normal", category: "Animales" },
  { id: "es-animal-iguana-camaleon", civilWord: "Iguana", undercoverWord: "Camaleón", difficulty: "hard", category: "Animales" },
  { id: "es-animal-hormiga-escarabajo", civilWord: "Hormiga", undercoverWord: "Escarabajo", difficulty: "normal", category: "Animales" },

  // ─── Objetos (25) ───
  { id: "es-obj-telefono-tablet", civilWord: "Teléfono", undercoverWord: "Tablet", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-llave-candado", civilWord: "Llave", undercoverWord: "Candado", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-libro-revista", civilWord: "Libro", undercoverWord: "Revista", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-gafas-lupa", civilWord: "Gafas", undercoverWord: "Lupa", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-paraguas-sombrilla", civilWord: "Paraguas", undercoverWord: "Sombrilla", difficulty: "hard", category: "Objetos" },
  { id: "es-obj-vela-lampara", civilWord: "Vela", undercoverWord: "Lámpara", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-reloj-despertador", civilWord: "Reloj", undercoverWord: "Despertador", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-cuchillo-espada", civilWord: "Cuchillo", undercoverWord: "Espada", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-espejo-ventana", civilWord: "Espejo", undercoverWord: "Ventana", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-almohada-manta", civilWord: "Almohada", undercoverWord: "Manta", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-guitarra-violin", civilWord: "Guitarra", undercoverWord: "Violín", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-camara-prismaticos", civilWord: "Cámara", undercoverWord: "Prismáticos", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-tijeras-navaja", civilWord: "Tijeras", undercoverWord: "Navaja", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-billetera-monedero", civilWord: "Billetera", undercoverWord: "Monedero", difficulty: "hard", category: "Objetos" },
  { id: "es-obj-escoba-fregona", civilWord: "Escoba", undercoverWord: "Fregona", difficulty: "hard", category: "Objetos" },
  { id: "es-obj-maleta-mochila", civilWord: "Maleta", undercoverWord: "Mochila", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-cuchara-tenedor", civilWord: "Cuchara", undercoverWord: "Tenedor", difficulty: "easy", category: "Objetos" },
  { id: "es-obj-sarten-olla", civilWord: "Sartén", undercoverWord: "Olla", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-corona-sombrero", civilWord: "Corona", undercoverWord: "Sombrero", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-mapa-brujula", civilWord: "Mapa", undercoverWord: "Brújula", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-dado-ficha", civilWord: "Dado", undercoverWord: "Ficha", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-lapiz-boligrafo", civilWord: "Lápiz", undercoverWord: "Bolígrafo", difficulty: "hard", category: "Objetos" },
  { id: "es-obj-regla-compas", civilWord: "Regla", undercoverWord: "Compás", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-abanico-ventilador", civilWord: "Abanico", undercoverWord: "Ventilador", difficulty: "normal", category: "Objetos" },
  { id: "es-obj-peine-cepillo", civilWord: "Peine", undercoverWord: "Cepillo", difficulty: "hard", category: "Objetos" },

  // ─── Lugares (25) ───
  { id: "es-lugar-playa-piscina", civilWord: "Playa", undercoverWord: "Piscina", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-castillo-palacio", civilWord: "Castillo", undercoverWord: "Palacio", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-iglesia-catedral", civilWord: "Iglesia", undercoverWord: "Catedral", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-parque-jardin", civilWord: "Parque", undercoverWord: "Jardín", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-montaña-volcan", civilWord: "Montaña", undercoverWord: "Volcán", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-rio-lago", civilWord: "Río", undercoverWord: "Lago", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-estadio-coliseo", civilWord: "Estadio", undercoverWord: "Coliseo", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-mercado-supermercado", civilWord: "Mercado", undercoverWord: "Supermercado", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-hospital-farmacia", civilWord: "Hospital", undercoverWord: "Farmacia", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-escuela-universidad", civilWord: "Escuela", undercoverWord: "Universidad", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-museo-galeria", civilWord: "Museo", undercoverWord: "Galería de arte", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-cine-teatro", civilWord: "Cine", undercoverWord: "Teatro", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-aeropuerto-estacion", civilWord: "Aeropuerto", undercoverWord: "Estación de tren", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-biblioteca-libreria", civilWord: "Biblioteca", undercoverWord: "Librería", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-zoo-acuario", civilWord: "Zoológico", undercoverWord: "Acuario", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-faro-torre", civilWord: "Faro", undercoverWord: "Torre", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-cueva-tunel", civilWord: "Cueva", undercoverWord: "Túnel", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-isla-peninsula", civilWord: "Isla", undercoverWord: "Península", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-plaza-rotonda", civilWord: "Plaza", undercoverWord: "Rotonda", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-puente-acueducto", civilWord: "Puente", undercoverWord: "Acueducto", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-cascada-fuente", civilWord: "Cascada", undercoverWord: "Fuente", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-desierto-sabana", civilWord: "Desierto", undercoverWord: "Sabana", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-selva-bosque", civilWord: "Selva", undercoverWord: "Bosque", difficulty: "hard", category: "Lugares" },
  { id: "es-lugar-piramide-templo", civilWord: "Pirámide", undercoverWord: "Templo", difficulty: "normal", category: "Lugares" },
  { id: "es-lugar-granero-establo", civilWord: "Granero", undercoverWord: "Establo", difficulty: "hard", category: "Lugares" },

  // ─── Deportes (20) ───
  { id: "es-sport-futbol-rugby", civilWord: "Fútbol", undercoverWord: "Rugby", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-baloncesto-voley", civilWord: "Baloncesto", undercoverWord: "Voleibol", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-tenis-padel", civilWord: "Tenis", undercoverWord: "Pádel", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-natacion-buceo", civilWord: "Natación", undercoverWord: "Buceo", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-esqui-snowboard", civilWord: "Esquí", undercoverWord: "Snowboard", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-boxeo-lucha", civilWord: "Boxeo", undercoverWord: "Lucha libre", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-surf-kayak", civilWord: "Surf", undercoverWord: "Kayak", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-golf-bolos", civilWord: "Golf", undercoverWord: "Bolos", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-ciclismo-patinaje", civilWord: "Ciclismo", undercoverWord: "Patinaje", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-escalada-senderismo", civilWord: "Escalada", undercoverWord: "Senderismo", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-beisbol-cricket", civilWord: "Béisbol", undercoverWord: "Cricket", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-esgrima-kendo", civilWord: "Esgrima", undercoverWord: "Kendo", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-gimnasia-yoga", civilWord: "Gimnasia", undercoverWord: "Yoga", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-polo-hipica", civilWord: "Polo", undercoverWord: "Hípica", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-waterpolo-natacion", civilWord: "Waterpolo", undercoverWord: "Natación sincronizada", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-skateboard-longboard", civilWord: "Skateboard", undercoverWord: "Longboard", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-karate-taekwondo", civilWord: "Karate", undercoverWord: "Taekwondo", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-hockey-curling", civilWord: "Hockey sobre hielo", undercoverWord: "Curling", difficulty: "normal", category: "Deportes" },
  { id: "es-sport-balonmano-futbolsala", civilWord: "Balonmano", undercoverWord: "Fútbol sala", difficulty: "hard", category: "Deportes" },
  { id: "es-sport-salto-trampolinismo", civilWord: "Salto de longitud", undercoverWord: "Trampolín", difficulty: "normal", category: "Deportes" },

  // ─── Trabajos (20) ───
  { id: "es-trabajo-chef-panadero", civilWord: "Chef", undercoverWord: "Panadero", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-doctor-enfermero", civilWord: "Doctor", undercoverWord: "Enfermero", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-policia-bombero", civilWord: "Policía", undercoverWord: "Bombero", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-piloto-astronauta", civilWord: "Piloto", undercoverWord: "Astronauta", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-maestro-profesor", civilWord: "Maestro", undercoverWord: "Profesor universitario", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-pintor-escultor", civilWord: "Pintor", undercoverWord: "Escultor", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-cartero-repartidor", civilWord: "Cartero", undercoverWord: "Repartidor", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-carpintero-albanil", civilWord: "Carpintero", undercoverWord: "Albañil", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-fotografo-camarografo", civilWord: "Fotógrafo", undercoverWord: "Camarógrafo", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-veterinario-biologo", civilWord: "Veterinario", undercoverWord: "Biólogo", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-payaso-mago", civilWord: "Payaso", undercoverWord: "Mago", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-torero-domador", civilWord: "Torero", undercoverWord: "Domador", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-pescador-marinero", civilWord: "Pescador", undercoverWord: "Marinero", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-granjero-jardinero", civilWord: "Granjero", undercoverWord: "Jardinero", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-mecanico-electricista", civilWord: "Mecánico", undercoverWord: "Electricista", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-dentista-cirujano", civilWord: "Dentista", undercoverWord: "Cirujano", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-musico-cantante", civilWord: "Músico", undercoverWord: "Cantante", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-detective-espia", civilWord: "Detective", undercoverWord: "Espía", difficulty: "normal", category: "Trabajos" },
  { id: "es-trabajo-peluquero-barbero", civilWord: "Peluquero", undercoverWord: "Barbero", difficulty: "hard", category: "Trabajos" },
  { id: "es-trabajo-arqueologo-paleontolgo", civilWord: "Arqueólogo", undercoverWord: "Paleontólogo", difficulty: "hard", category: "Trabajos" },

  // ─── Transporte (20) ───
  { id: "es-transporte-coche-camioneta", civilWord: "Coche", undercoverWord: "Camioneta", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-avion-helicoptero", civilWord: "Avión", undercoverWord: "Helicóptero", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-barco-velero", civilWord: "Barco", undercoverWord: "Velero", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-tren-metro", civilWord: "Tren", undercoverWord: "Metro", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-bicicleta-triciclo", civilWord: "Bicicleta", undercoverWord: "Triciclo", difficulty: "easy", category: "Transporte" },
  { id: "es-transporte-moto-scooter", civilWord: "Moto", undercoverWord: "Scooter", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-autobus-tranvia", civilWord: "Autobús", undercoverWord: "Tranvía", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-ambulancia-camion-bomberos", civilWord: "Ambulancia", undercoverWord: "Camión de bomberos", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-taxi-uber", civilWord: "Taxi", undercoverWord: "Coche particular", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-canoa-lancha", civilWord: "Canoa", undercoverWord: "Lancha", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-globo-dirigible", civilWord: "Globo aerostático", undercoverWord: "Dirigible", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-patineta-monopatin", civilWord: "Patineta", undercoverWord: "Monopatín eléctrico", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-submarino-batiscafo", civilWord: "Submarino", undercoverWord: "Barco", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-cohete-nave-espacial", civilWord: "Cohete", undercoverWord: "Nave espacial", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-camion-furgoneta", civilWord: "Camión", undercoverWord: "Furgoneta", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-telesferico-funicular", civilWord: "Teleférico", undercoverWord: "Funicular", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-carreta-carruaje", civilWord: "Carreta", undercoverWord: "Carruaje", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-trineo-esquis", civilWord: "Trineo", undercoverWord: "Esquís", difficulty: "normal", category: "Transporte" },
  { id: "es-transporte-patines-rollers", civilWord: "Patines de hielo", undercoverWord: "Patines en línea", difficulty: "hard", category: "Transporte" },
  { id: "es-transporte-yate-crucero", civilWord: "Yate", undercoverWord: "Crucero", difficulty: "normal", category: "Transporte" },

  // ─── Naturaleza (25) ───
  { id: "es-natura-sol-luna", civilWord: "Sol", undercoverWord: "Luna", difficulty: "easy", category: "Naturaleza" },
  { id: "es-natura-arbol-arbusto", civilWord: "Árbol", undercoverWord: "Arbusto", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-rosa-tulipan", civilWord: "Rosa", undercoverWord: "Tulipán", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-cactus-palmera", civilWord: "Cactus", undercoverWord: "Palmera", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-nube-niebla", civilWord: "Nube", undercoverWord: "Niebla", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-rayo-relampago", civilWord: "Rayo", undercoverWord: "Relámpago", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-lluvia-granizo", civilWord: "Lluvia", undercoverWord: "Granizo", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-arcoiris-aurora", civilWord: "Arcoíris", undercoverWord: "Aurora boreal", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-volcán-geiser", civilWord: "Volcán", undercoverWord: "Géiser", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-estrella-cometa", civilWord: "Estrella", undercoverWord: "Cometa", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-girasol-margarita", civilWord: "Girasol", undercoverWord: "Margarita", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-hongo-seta", civilWord: "Hongo", undercoverWord: "Seta", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-piedra-cristal", civilWord: "Piedra", undercoverWord: "Cristal", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-tornado-huracan", civilWord: "Tornado", undercoverWord: "Huracán", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-ola-maremoto", civilWord: "Ola", undercoverWord: "Maremoto", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-nieve-escarcha", civilWord: "Nieve", undercoverWord: "Escarcha", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-hoja-pluma", civilWord: "Hoja", undercoverWord: "Pluma", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-coral-esponja", civilWord: "Coral", undercoverWord: "Esponja de mar", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-trebol-helecho", civilWord: "Trébol", undercoverWord: "Helecho", difficulty: "normal", category: "Naturaleza" },
  { id: "es-natura-amanecer-atardecer", civilWord: "Amanecer", undercoverWord: "Atardecer", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-cueva-gruta", civilWord: "Cueva", undercoverWord: "Gruta", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-pantano-laguna", civilWord: "Pantano", undercoverWord: "Laguna", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-liana-enredadera", civilWord: "Liana", undercoverWord: "Enredadera", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-acantilado-barranco", civilWord: "Acantilado", undercoverWord: "Barranco", difficulty: "hard", category: "Naturaleza" },
  { id: "es-natura-orquidea-lirio", civilWord: "Orquídea", undercoverWord: "Lirio", difficulty: "hard", category: "Naturaleza" },

  // ─── Cultura Pop (20) ───
  { id: "es-pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Cultura Pop" },
  { id: "es-pop-batman-spiderman", civilWord: "Batman", undercoverWord: "Spider-Man", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-pikachu-eevee", civilWord: "Pikachu", undercoverWord: "Eevee", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-elsa-rapunzel", civilWord: "Elsa", undercoverWord: "Rapunzel", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-goku-naruto", civilWord: "Goku", undercoverWord: "Naruto", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-bob-esponja-patrick", civilWord: "Bob Esponja", undercoverWord: "Patricio", difficulty: "easy", category: "Cultura Pop" },
  { id: "es-pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-amongus-lobo", civilWord: "Among Us", undercoverWord: "Hombre Lobo", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-harry-frodo", civilWord: "Harry Potter", undercoverWord: "Frodo", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-ironman-captain", civilWord: "Iron Man", undercoverWord: "Capitán América", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-darth-vader-thanos", civilWord: "Darth Vader", undercoverWord: "Thanos", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-shrek-sulley", civilWord: "Shrek", undercoverWord: "Sulley", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-woody-buzz", civilWord: "Woody", undercoverWord: "Buzz Lightyear", difficulty: "easy", category: "Cultura Pop" },
  { id: "es-pop-nemo-dory", civilWord: "Nemo", undercoverWord: "Dory", difficulty: "easy", category: "Cultura Pop" },
  { id: "es-pop-homer-peter", civilWord: "Homer Simpson", undercoverWord: "Peter Griffin", difficulty: "hard", category: "Cultura Pop" },
  { id: "es-pop-link-zelda", civilWord: "Link", undercoverWord: "Zelda", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-totoro-snorlax", civilWord: "Totoro", undercoverWord: "Snorlax", difficulty: "hard", category: "Cultura Pop" },
  { id: "es-pop-r2d2-walle", civilWord: "R2-D2", undercoverWord: "WALL-E", difficulty: "normal", category: "Cultura Pop" },
  { id: "es-pop-superman-homelander", civilWord: "Superman", undercoverWord: "Homelander", difficulty: "hard", category: "Cultura Pop" },
  { id: "es-pop-garfield-snoopy", civilWord: "Garfield", undercoverWord: "Snoopy", difficulty: "easy", category: "Cultura Pop" },

  // ─── Tecnología (20) ───
  { id: "es-tech-laptop-desktop", civilWord: "Portátil", undercoverWord: "Ordenador de mesa", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-auriculares-altavoz", civilWord: "Auriculares", undercoverWord: "Altavoz", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-raton-trackpad", civilWord: "Ratón", undercoverWord: "Trackpad", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-pendrive-disco-duro", civilWord: "Pendrive", undercoverWord: "Disco duro", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-router-antena", civilWord: "Router", undercoverWord: "Antena", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-smartwatch-reloj-digital", civilWord: "Smartwatch", undercoverWord: "Reloj digital", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-drone-helicoptero-rc", civilWord: "Drone", undercoverWord: "Helicóptero RC", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-impresora-escaner", civilWord: "Impresora", undercoverWord: "Escáner", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-videoconsola-gameboy", civilWord: "Videoconsola", undercoverWord: "Game Boy", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-webcam-camara-seguridad", civilWord: "Webcam", undercoverWord: "Cámara de seguridad", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-robot-android", civilWord: "Robot", undercoverWord: "Androide", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-proyector-television", civilWord: "Proyector", undercoverWord: "Televisión", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-teclado-piano-electrico", civilWord: "Teclado", undercoverWord: "Piano eléctrico", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-micro-grabadora", civilWord: "Micrófono", undercoverWord: "Grabadora", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-gafas-vr-casco", civilWord: "Gafas VR", undercoverWord: "Casco de realidad virtual", difficulty: "hard", category: "Tecnología" },
  { id: "es-tech-cargador-pila", civilWord: "Cargador", undercoverWord: "Pila", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-satelite-estacion-espacial", civilWord: "Satélite", undercoverWord: "Estación espacial", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-semaforo-farola", civilWord: "Semáforo", undercoverWord: "Farola", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-calculadora-abaco", civilWord: "Calculadora", undercoverWord: "Ábaco", difficulty: "normal", category: "Tecnología" },
  { id: "es-tech-control-remoto-mando", civilWord: "Control remoto", undercoverWord: "Mando de consola", difficulty: "hard", category: "Tecnología" },

  // ─── Ropa (20) ───
  { id: "es-ropa-camiseta-polo", civilWord: "Camiseta", undercoverWord: "Polo", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-zapatillas-botas", civilWord: "Zapatillas", undercoverWord: "Botas", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-gorra-sombrero", civilWord: "Gorra", undercoverWord: "Sombrero", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-bufanda-panuelo", civilWord: "Bufanda", undercoverWord: "Pañuelo", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-guantes-manoplas", civilWord: "Guantes", undercoverWord: "Manoplas", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-vestido-falda", civilWord: "Vestido", undercoverWord: "Falda", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-chaqueta-abrigo", civilWord: "Chaqueta", undercoverWord: "Abrigo", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-pantalon-bermudas", civilWord: "Pantalón", undercoverWord: "Bermudas", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-corbata-pajarita", civilWord: "Corbata", undercoverWord: "Pajarita", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-bikini-banador", civilWord: "Bikini", undercoverWord: "Bañador", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-chanclas-sandalias", civilWord: "Chanclas", undercoverWord: "Sandalias", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-pijama-bata", civilWord: "Pijama", undercoverWord: "Bata", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-chaleco-jersey", civilWord: "Chaleco", undercoverWord: "Jersey", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-cinturon-tirantes", civilWord: "Cinturón", undercoverWord: "Tirantes", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-capa-poncho", civilWord: "Capa", undercoverWord: "Poncho", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-boina-casco", civilWord: "Boina", undercoverWord: "Casco", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-tacones-plataformas", civilWord: "Tacones", undercoverWord: "Plataformas", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-delantal-babi", civilWord: "Delantal", undercoverWord: "Babero", difficulty: "normal", category: "Ropa" },
  { id: "es-ropa-sudadera-hoodie", civilWord: "Sudadera", undercoverWord: "Hoodie con capucha", difficulty: "hard", category: "Ropa" },
  { id: "es-ropa-tunica-toga", civilWord: "Túnica", undercoverWord: "Toga", difficulty: "hard", category: "Ropa" },

  // ─── Música (15) ───
  { id: "es-musica-guitarra-ukelele", civilWord: "Guitarra", undercoverWord: "Ukelele", difficulty: "normal", category: "Música" },
  { id: "es-musica-bateria-bongo", civilWord: "Batería", undercoverWord: "Bongó", difficulty: "normal", category: "Música" },
  { id: "es-musica-piano-organo", civilWord: "Piano", undercoverWord: "Órgano", difficulty: "normal", category: "Música" },
  { id: "es-musica-flauta-clarinete", civilWord: "Flauta", undercoverWord: "Clarinete", difficulty: "hard", category: "Música" },
  { id: "es-musica-trompeta-trombon", civilWord: "Trompeta", undercoverWord: "Trombón", difficulty: "hard", category: "Música" },
  { id: "es-musica-arpa-lira", civilWord: "Arpa", undercoverWord: "Lira", difficulty: "normal", category: "Música" },
  { id: "es-musica-violin-chelo", civilWord: "Violín", undercoverWord: "Violonchelo", difficulty: "normal", category: "Música" },
  { id: "es-musica-maraca-pandereta", civilWord: "Maraca", undercoverWord: "Pandereta", difficulty: "normal", category: "Música" },
  { id: "es-musica-saxofon-tuba", civilWord: "Saxofón", undercoverWord: "Tuba", difficulty: "normal", category: "Música" },
  { id: "es-musica-acordeon-bandoneon", civilWord: "Acordeón", undercoverWord: "Bandoneón", difficulty: "hard", category: "Música" },
  { id: "es-musica-castanuelas-claves", civilWord: "Castañuelas", undercoverWord: "Claves", difficulty: "hard", category: "Música" },
  { id: "es-musica-xilofono-metalofono", civilWord: "Xilófono", undercoverWord: "Metalófono", difficulty: "hard", category: "Música" },
  { id: "es-musica-gaita-flauta-pan", civilWord: "Gaita", undercoverWord: "Flauta de Pan", difficulty: "normal", category: "Música" },
  { id: "es-musica-tambor-timbal", civilWord: "Tambor", undercoverWord: "Timbal", difficulty: "hard", category: "Música" },
  { id: "es-musica-contrabajo-bajo", civilWord: "Contrabajo", undercoverWord: "Bajo eléctrico", difficulty: "normal", category: "Música" },

  // ─── Hogar (20) ───
  { id: "es-hogar-silla-taburete", civilWord: "Silla", undercoverWord: "Taburete", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-sofa-sillon", civilWord: "Sofá", undercoverWord: "Sillón", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-mesa-escritorio", civilWord: "Mesa", undercoverWord: "Escritorio", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-cama-hamaca", civilWord: "Cama", undercoverWord: "Hamaca", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-banera-ducha", civilWord: "Bañera", undercoverWord: "Ducha", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-armario-estanteria", civilWord: "Armario", undercoverWord: "Estantería", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-chimenea-estufa", civilWord: "Chimenea", undercoverWord: "Estufa", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-cortina-persiana", civilWord: "Cortina", undercoverWord: "Persiana", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-alfombra-tapete", civilWord: "Alfombra", undercoverWord: "Tapete", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-florero-maceta", civilWord: "Florero", undercoverWord: "Maceta", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-lavadora-secadora", civilWord: "Lavadora", undercoverWord: "Secadora", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-nevera-congelador", civilWord: "Nevera", undercoverWord: "Congelador", difficulty: "hard", category: "Hogar" },
  { id: "es-hogar-horno-microondas", civilWord: "Horno", undercoverWord: "Microondas", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-taza-vaso", civilWord: "Taza", undercoverWord: "Vaso", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-plato-cuenco", civilWord: "Plato", undercoverWord: "Cuenco", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-lampara-farol", civilWord: "Lámpara de pie", undercoverWord: "Farol", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-cajon-cesta", civilWord: "Cajón", undercoverWord: "Cesta", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-escalera-ascensor", civilWord: "Escalera", undercoverWord: "Ascensor", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-mecedora-columpio", civilWord: "Mecedora", undercoverWord: "Columpio", difficulty: "normal", category: "Hogar" },
  { id: "es-hogar-perchero-gancho", civilWord: "Perchero", undercoverWord: "Gancho", difficulty: "normal", category: "Hogar" },

  // ─── Fiestas (20) ───
  { id: "es-fiesta-globo-pinata", civilWord: "Globo", undercoverWord: "Piñata", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-pastel-tarta", civilWord: "Pastel de cumpleaños", undercoverWord: "Tarta nupcial", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-confeti-serpentina", civilWord: "Confeti", undercoverWord: "Serpentina", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-mascara-antifaz", civilWord: "Máscara", undercoverWord: "Antifaz", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-corona-tiara", civilWord: "Corona de rey", undercoverWord: "Tiara", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-fuegos-artificiales-bengala", civilWord: "Fuegos artificiales", undercoverWord: "Bengala", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-vela-velita", civilWord: "Vela de cumpleaños", undercoverWord: "Velita de iglesia", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-regalo-sorpresa", civilWord: "Regalo envuelto", undercoverWord: "Caja sorpresa", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-payaso-mimo", civilWord: "Payaso", undercoverWord: "Mimo", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-disfraz-uniforme", civilWord: "Disfraz", undercoverWord: "Uniforme", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-arbol-navidad-belen", civilWord: "Árbol de Navidad", undercoverWord: "Belén", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-papa-noel-reyes-magos", civilWord: "Papá Noel", undercoverWord: "Rey Mago", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-calabaza-fantasma", civilWord: "Calabaza", undercoverWord: "Fantasma", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-calavera-esqueleto", civilWord: "Calavera", undercoverWord: "Esqueleto", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-castillo-hinchable-tobogan", civilWord: "Castillo hinchable", undercoverWord: "Tobogán", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-guirnalda-banderines", civilWord: "Guirnalda", undercoverWord: "Banderines", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-cotillon-gorro", civilWord: "Cotillón", undercoverWord: "Gorro de fiesta", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-trono-silla-decorada", civilWord: "Trono", undercoverWord: "Silla decorada", difficulty: "hard", category: "Fiestas" },
  { id: "es-fiesta-careta-maquillaje", civilWord: "Careta", undercoverWord: "Maquillaje artístico", difficulty: "normal", category: "Fiestas" },
  { id: "es-fiesta-carroza-desfile", civilWord: "Carroza", undercoverWord: "Desfile", difficulty: "normal", category: "Fiestas" },

  // ─── Extra pairs across categories (10) ───
  { id: "es-food-empanada-samosa", civilWord: "Empanada", undercoverWord: "Samosa", difficulty: "hard", category: "Comida" },
  { id: "es-food-churro-porras", civilWord: "Churro", undercoverWord: "Porra", difficulty: "hard", category: "Comida" },
  { id: "es-animal-condor-buitre", civilWord: "Cóndor", undercoverWord: "Buitre", difficulty: "hard", category: "Animales" },
  { id: "es-animal-piraña-pez-payaso", civilWord: "Piraña", undercoverWord: "Pez payaso", difficulty: "normal", category: "Animales" },
  { id: "es-lugar-hacienda-rancho", civilWord: "Hacienda", undercoverWord: "Rancho", difficulty: "hard", category: "Lugares" },
  { id: "es-obj-ajedrez-damas", civilWord: "Ajedrez", undercoverWord: "Damas", difficulty: "hard", category: "Objetos" },
  { id: "es-obj-bola-disco-cristal", civilWord: "Bola de cristal", undercoverWord: "Bola de discoteca", difficulty: "normal", category: "Objetos" },
  { id: "es-drink-agua-coco-jugo-cana", civilWord: "Agua de coco", undercoverWord: "Jugo de caña", difficulty: "normal", category: "Bebidas" },
  { id: "es-natura-copo-nieve-cristal-hielo", civilWord: "Copo de nieve", undercoverWord: "Cristal de hielo", difficulty: "hard", category: "Naturaleza" },
  { id: "es-transporte-tabla-surf-windsurf", civilWord: "Tabla de surf", undercoverWord: "Windsurf", difficulty: "hard", category: "Transporte" },
];

export const ES_WORD_CATEGORIES = [
  "Todo",
  "Comida",
  "Bebidas",
  "Animales",
  "Objetos",
  "Lugares",
  "Deportes",
  "Trabajos",
  "Transporte",
  "Naturaleza",
  "Cultura Pop",
  "Tecnología",
  "Ropa",
  "Música",
  "Hogar",
  "Fiestas"
];
