import type { WordPair } from "../protocol.js";

export const PT_WORD_PAIRS: WordPair[] = [
  // ─── Comida (20) ───
  { id: "pt-food-pizza-pastel", civilWord: "Pizza", undercoverWord: "Pastel", difficulty: "normal", category: "Comida" },
  { id: "pt-food-sushi-temaki", civilWord: "Sushi", undercoverWord: "Temaki", difficulty: "hard", category: "Comida" },
  { id: "pt-food-hamburguer-sanduiche", civilWord: "Hambúrguer", undercoverWord: "Sanduíche", difficulty: "easy", category: "Comida" },
  { id: "pt-food-coxinha-bolinho", civilWord: "Coxinha", undercoverWord: "Bolinho", difficulty: "normal", category: "Comida" },
  { id: "pt-food-pao-torrada", civilWord: "Pão", undercoverWord: "Torrada", difficulty: "easy", category: "Comida" },
  { id: "pt-food-bolo-cupcake", civilWord: "Bolo", undercoverWord: "Cupcake", difficulty: "normal", category: "Comida" },
  { id: "pt-food-sorvete-picole", civilWord: "Sorvete", undercoverWord: "Picolé", difficulty: "hard", category: "Comida" },
  { id: "pt-food-batata-mandioca", civilWord: "Batata frita", undercoverWord: "Mandioca frita", difficulty: "hard", category: "Comida" },
  { id: "pt-food-queijo-manteiga", civilWord: "Queijo", undercoverWord: "Manteiga", difficulty: "normal", category: "Comida" },
  { id: "pt-food-doce-chocolate", civilWord: "Doce", undercoverWord: "Chocolate", difficulty: "easy", category: "Comida" },
  { id: "pt-food-taco-burrito", civilWord: "Taco", undercoverWord: "Burrito", difficulty: "hard", category: "Comida" },
  { id: "pt-food-macarrao-espaguete", civilWord: "Macarrão", undercoverWord: "Espaguete", difficulty: "hard", category: "Comida" },
  { id: "pt-food-brigadeiro-trufa", civilWord: "Brigadeiro", undercoverWord: "Trufa", difficulty: "hard", category: "Comida" },
  { id: "pt-food-acai-smoothie", civilWord: "Açaí", undercoverWord: "Smoothie", difficulty: "normal", category: "Comida" },
  { id: "pt-food-churrasco-costela", civilWord: "Churrasco", undercoverWord: "Costela", difficulty: "normal", category: "Comida" },
  { id: "pt-food-tapioca-crepe", civilWord: "Tapioca", undercoverWord: "Crepe", difficulty: "normal", category: "Comida" },
  { id: "pt-food-ovo-omelete", civilWord: "Ovo frito", undercoverWord: "Omelete", difficulty: "normal", category: "Comida" },
  { id: "pt-food-pipoca-amendoim", civilWord: "Pipoca", undercoverWord: "Amendoim", difficulty: "normal", category: "Comida" },
  { id: "pt-food-salada-sopa", civilWord: "Salada", undercoverWord: "Sopa", difficulty: "easy", category: "Comida" },
  { id: "pt-food-rosquinha-pretzel", civilWord: "Rosquinha", undercoverWord: "Pretzel", difficulty: "normal", category: "Comida" },

  // ─── Bebidas (15) ───
  { id: "pt-drink-cafe-cha", civilWord: "Café", undercoverWord: "Chá", difficulty: "easy", category: "Bebidas" },
  { id: "pt-drink-suco-vitamina", civilWord: "Suco", undercoverWord: "Vitamina", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-coca-guarana", civilWord: "Coca-Cola", undercoverWord: "Guaraná", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-leite-iogurte", civilWord: "Leite", undercoverWord: "Iogurte", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-agua-gelo", civilWord: "Água", undercoverWord: "Gelo", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-chocolate-cappuccino", civilWord: "Chocolate quente", undercoverWord: "Cappuccino", difficulty: "hard", category: "Bebidas" },
  { id: "pt-drink-limonada-laranjada", civilWord: "Limonada", undercoverWord: "Laranjada", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-cerveja-chopp", civilWord: "Cerveja", undercoverWord: "Chopp", difficulty: "hard", category: "Bebidas" },
  { id: "pt-drink-caipirinha-mojito", civilWord: "Caipirinha", undercoverWord: "Mojito", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-mate-chimarrao", civilWord: "Mate", undercoverWord: "Chimarrão", difficulty: "hard", category: "Bebidas" },
  { id: "pt-drink-milkshake-frappe", civilWord: "Milkshake", undercoverWord: "Frappé", difficulty: "hard", category: "Bebidas" },
  { id: "pt-drink-agua-coco-suco-laranja", civilWord: "Água de coco", undercoverWord: "Suco de laranja", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-vinho-sangria", civilWord: "Vinho", undercoverWord: "Sangria", difficulty: "normal", category: "Bebidas" },
  { id: "pt-drink-energetico-isotronico", civilWord: "Energético", undercoverWord: "Isotônico", difficulty: "hard", category: "Bebidas" },
  { id: "pt-drink-refrigerante-suco-caixa", civilWord: "Refrigerante", undercoverWord: "Suco de caixa", difficulty: "normal", category: "Bebidas" },

  // ─── Animais (20) ───
  { id: "pt-animal-gato-tigre", civilWord: "Gato", undercoverWord: "Tigre", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-cachorro-lobo", civilWord: "Cachorro", undercoverWord: "Lobo", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-cavalo-zebra", civilWord: "Cavalo", undercoverWord: "Zebra", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-coelho-lebre", civilWord: "Coelho", undercoverWord: "Lebre", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-golfinho-baleia", civilWord: "Golfinho", undercoverWord: "Baleia", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-aguia-falcao", civilWord: "Águia", undercoverWord: "Falcão", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-sapo-ra", civilWord: "Sapo", undercoverWord: "Rã", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-macaco-gorila", civilWord: "Macaco", undercoverWord: "Gorila", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-rato-hamster", civilWord: "Rato", undercoverWord: "Hamster", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-leao-leopardo", civilWord: "Leão", undercoverWord: "Leopardo", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-tubarao-peixe-espada", civilWord: "Tubarão", undercoverWord: "Peixe-espada", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-borboleta-mariposa", civilWord: "Borboleta", undercoverWord: "Mariposa", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-pinguim-pato", civilWord: "Pinguim", undercoverWord: "Pato", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-cobra-minhoca", civilWord: "Cobra", undercoverWord: "Minhoca", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-tartaruga-caracol", civilWord: "Tartaruga", undercoverWord: "Caracol", difficulty: "normal", category: "Animais" },
  { id: "pt-animal-urso-panda", civilWord: "Urso", undercoverWord: "Panda", difficulty: "easy", category: "Animais" },
  { id: "pt-animal-papagaio-arara", civilWord: "Papagaio", undercoverWord: "Arara", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-jacare-crocodilo", civilWord: "Jacaré", undercoverWord: "Crocodilo", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-abelha-vespa", civilWord: "Abelha", undercoverWord: "Vespa", difficulty: "hard", category: "Animais" },
  { id: "pt-animal-camelo-lhama", civilWord: "Camelo", undercoverWord: "Lhama", difficulty: "normal", category: "Animais" },

  // ─── Objetos (15) ───
  { id: "pt-obj-celular-tablet", civilWord: "Celular", undercoverWord: "Tablet", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-chave-cadeado", civilWord: "Chave", undercoverWord: "Cadeado", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-livro-revista", civilWord: "Livro", undercoverWord: "Revista", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-oculos-lupa", civilWord: "Óculos", undercoverWord: "Lupa", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-guarda-chuva-sombrinha", civilWord: "Guarda-chuva", undercoverWord: "Sombrinha", difficulty: "hard", category: "Objetos" },
  { id: "pt-obj-vela-abajur", civilWord: "Vela", undercoverWord: "Abajur", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-relogio-despertador", civilWord: "Relógio", undercoverWord: "Despertador", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-faca-espada", civilWord: "Faca", undercoverWord: "Espada", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-violao-guitarra", civilWord: "Violão", undercoverWord: "Guitarra", difficulty: "hard", category: "Objetos" },
  { id: "pt-obj-camera-binoculo", civilWord: "Câmera", undercoverWord: "Binóculo", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-tesoura-alicate", civilWord: "Tesoura", undercoverWord: "Alicate", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-mochila-mala", civilWord: "Mochila", undercoverWord: "Mala", difficulty: "easy", category: "Objetos" },
  { id: "pt-obj-martelo-machado", civilWord: "Martelo", undercoverWord: "Machado", difficulty: "normal", category: "Objetos" },
  { id: "pt-obj-copo-caneca", civilWord: "Copo", undercoverWord: "Caneca", difficulty: "hard", category: "Objetos" },
  { id: "pt-obj-vassoura-rodo", civilWord: "Vassoura", undercoverWord: "Rodo", difficulty: "normal", category: "Objetos" },

  // ─── Esportes (15) ───
  { id: "pt-sport-futebol-rugby", civilWord: "Futebol", undercoverWord: "Rugby", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-basquete-volei", civilWord: "Basquete", undercoverWord: "Vôlei", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-tenis-badminton", civilWord: "Tênis", undercoverWord: "Badminton", difficulty: "hard", category: "Esportes" },
  { id: "pt-sport-natacao-mergulho", civilWord: "Natação", undercoverWord: "Mergulho", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-esqui-snowboard", civilWord: "Esqui", undercoverWord: "Snowboard", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-boxe-luta", civilWord: "Boxe", undercoverWord: "Luta livre", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-surf-caiaque", civilWord: "Surf", undercoverWord: "Caiaque", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-skate-patins", civilWord: "Skate", undercoverWord: "Patins", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-capoeira-judo", civilWord: "Capoeira", undercoverWord: "Judô", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-escalada-trilha", civilWord: "Escalada", undercoverWord: "Trilha", difficulty: "hard", category: "Esportes" },
  { id: "pt-sport-golfe-boliche", civilWord: "Golfe", undercoverWord: "Boliche", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-ciclismo-motocross", civilWord: "Ciclismo", undercoverWord: "Motocross", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-ginastica-ballet", civilWord: "Ginástica", undercoverWord: "Ballet", difficulty: "normal", category: "Esportes" },
  { id: "pt-sport-pingpong-tenis", civilWord: "Pingue-pongue", undercoverWord: "Tênis", difficulty: "hard", category: "Esportes" },
  { id: "pt-sport-arco-flecha-tiro", civilWord: "Arco e flecha", undercoverWord: "Tiro ao alvo", difficulty: "normal", category: "Esportes" },

  // ─── Cultura Pop (15) ───
  { id: "pt-pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Cultura Pop" },
  { id: "pt-pop-batman-homem-aranha", civilWord: "Batman", undercoverWord: "Homem-Aranha", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-pikachu-eevee", civilWord: "Pikachu", undercoverWord: "Eevee", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-elsa-rapunzel", civilWord: "Elsa", undercoverWord: "Rapunzel", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-goku-naruto", civilWord: "Goku", undercoverWord: "Naruto", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-bob-esponja-patrick", civilWord: "Bob Esponja", undercoverWord: "Patrick", difficulty: "easy", category: "Cultura Pop" },
  { id: "pt-pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-amongus-lobisomem", civilWord: "Among Us", undercoverWord: "Lobisomem", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-harry-frodo", civilWord: "Harry Potter", undercoverWord: "Frodo", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-homem-ferro-capitao", civilWord: "Homem de Ferro", undercoverWord: "Capitão América", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-shrek-hulk", civilWord: "Shrek", undercoverWord: "Hulk", difficulty: "easy", category: "Cultura Pop" },
  { id: "pt-pop-darth-vader-voldemort", civilWord: "Darth Vader", undercoverWord: "Voldemort", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-mickey-pernalonga", civilWord: "Mickey", undercoverWord: "Pernalonga", difficulty: "normal", category: "Cultura Pop" },
  { id: "pt-pop-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "hard", category: "Cultura Pop" },
  { id: "pt-pop-superman-thor", civilWord: "Superman", undercoverWord: "Thor", difficulty: "normal", category: "Cultura Pop" },

  // ─── Lugares (20) ───
  { id: "pt-lugar-praia-piscina", civilWord: "Praia", undercoverWord: "Piscina", difficulty: "easy", category: "Lugares" },
  { id: "pt-lugar-castelo-palacio", civilWord: "Castelo", undercoverWord: "Palácio", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-igreja-catedral", civilWord: "Igreja", undercoverWord: "Catedral", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-escola-universidade", civilWord: "Escola", undercoverWord: "Universidade", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-hospital-farmacia", civilWord: "Hospital", undercoverWord: "Farmácia", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-cinema-teatro", civilWord: "Cinema", undercoverWord: "Teatro", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-parque-jardim", civilWord: "Parque", undercoverWord: "Jardim", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-aeroporto-rodoviaria", civilWord: "Aeroporto", undercoverWord: "Rodoviária", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-supermercado-feira", civilWord: "Supermercado", undercoverWord: "Feira", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-montanha-vulcao", civilWord: "Montanha", undercoverWord: "Vulcão", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-deserto-savana", civilWord: "Deserto", undercoverWord: "Savana", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-caverna-tunel", civilWord: "Caverna", undercoverWord: "Túnel", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-ilha-peninsula", civilWord: "Ilha", undercoverWord: "Península", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-estadio-ginasio", civilWord: "Estádio", undercoverWord: "Ginásio", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-farol-torre", civilWord: "Farol", undercoverWord: "Torre", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-zoologico-aquario", civilWord: "Zoológico", undercoverWord: "Aquário", difficulty: "normal", category: "Lugares" },
  { id: "pt-lugar-padaria-confeitaria", civilWord: "Padaria", undercoverWord: "Confeitaria", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-biblioteca-livraria", civilWord: "Biblioteca", undercoverWord: "Livraria", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-ponte-viaduto", civilWord: "Ponte", undercoverWord: "Viaduto", difficulty: "hard", category: "Lugares" },
  { id: "pt-lugar-praca-calcadao", civilWord: "Praça", undercoverWord: "Calçadão", difficulty: "normal", category: "Lugares" },

  // ─── Natureza (20) ───
  { id: "pt-nat-arvore-arbusto", civilWord: "Árvore", undercoverWord: "Arbusto", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-flor-cacto", civilWord: "Flor", undercoverWord: "Cacto", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-rio-cachoeira", civilWord: "Rio", undercoverWord: "Cachoeira", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-lago-lagoa", civilWord: "Lago", undercoverWord: "Lagoa", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-sol-lua", civilWord: "Sol", undercoverWord: "Lua", difficulty: "easy", category: "Natureza" },
  { id: "pt-nat-estrela-cometa", civilWord: "Estrela", undercoverWord: "Cometa", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-nuvem-neblina", civilWord: "Nuvem", undercoverWord: "Neblina", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-arco-iris-aurora", civilWord: "Arco-íris", undercoverWord: "Aurora boreal", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-folha-petala", civilWord: "Folha", undercoverWord: "Pétala", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-pedra-cristal", civilWord: "Pedra", undercoverWord: "Cristal", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-floresta-selva", civilWord: "Floresta", undercoverWord: "Selva", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-mar-oceano", civilWord: "Mar", undercoverWord: "Oceano", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-cogumelo-tronco", civilWord: "Cogumelo", undercoverWord: "Tronco", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-semente-fruta", civilWord: "Semente", undercoverWord: "Fruta", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-rosa-girassol", civilWord: "Rosa", undercoverWord: "Girassol", difficulty: "easy", category: "Natureza" },
  { id: "pt-nat-coral-alga", civilWord: "Coral", undercoverWord: "Alga", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-teia-ninho", civilWord: "Teia", undercoverWord: "Ninho", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-vulcao-geyser", civilWord: "Vulcão", undercoverWord: "Gêiser", difficulty: "normal", category: "Natureza" },
  { id: "pt-nat-onda-mare", civilWord: "Onda", undercoverWord: "Maré", difficulty: "hard", category: "Natureza" },
  { id: "pt-nat-palmeira-coqueiro", civilWord: "Palmeira", undercoverWord: "Coqueiro", difficulty: "hard", category: "Natureza" },

  // ─── Corpo Humano (15) ───
  { id: "pt-corpo-mao-pe", civilWord: "Mão", undercoverWord: "Pé", difficulty: "easy", category: "Corpo Humano" },
  { id: "pt-corpo-olho-nariz", civilWord: "Olho", undercoverWord: "Nariz", difficulty: "easy", category: "Corpo Humano" },
  { id: "pt-corpo-orelha-boca", civilWord: "Orelha", undercoverWord: "Boca", difficulty: "easy", category: "Corpo Humano" },
  { id: "pt-corpo-dedo-polegar", civilWord: "Dedo", undercoverWord: "Polegar", difficulty: "hard", category: "Corpo Humano" },
  { id: "pt-corpo-braco-perna", civilWord: "Braço", undercoverWord: "Perna", difficulty: "easy", category: "Corpo Humano" },
  { id: "pt-corpo-dente-lingua", civilWord: "Dente", undercoverWord: "Língua", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-cabelo-barba", civilWord: "Cabelo", undercoverWord: "Barba", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-coracao-pulmao", civilWord: "Coração", undercoverWord: "Pulmão", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-cerebro-estomago", civilWord: "Cérebro", undercoverWord: "Estômago", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-ombro-cotovelo", civilWord: "Ombro", undercoverWord: "Cotovelo", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-joelho-tornozelo", civilWord: "Joelho", undercoverWord: "Tornozelo", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-sobrancelha-cilios", civilWord: "Sobrancelha", undercoverWord: "Cílios", difficulty: "hard", category: "Corpo Humano" },
  { id: "pt-corpo-unha-cutícula", civilWord: "Unha", undercoverWord: "Cutícula", difficulty: "hard", category: "Corpo Humano" },
  { id: "pt-corpo-osso-musculo", civilWord: "Osso", undercoverWord: "Músculo", difficulty: "normal", category: "Corpo Humano" },
  { id: "pt-corpo-punho-palma", civilWord: "Punho", undercoverWord: "Palma", difficulty: "hard", category: "Corpo Humano" },

  // ─── Roupas (15) ───
  { id: "pt-roupa-camiseta-camisa", civilWord: "Camiseta", undercoverWord: "Camisa", difficulty: "hard", category: "Roupas" },
  { id: "pt-roupa-calca-bermuda", civilWord: "Calça", undercoverWord: "Bermuda", difficulty: "easy", category: "Roupas" },
  { id: "pt-roupa-tenis-sandalia", civilWord: "Tênis", undercoverWord: "Sandália", difficulty: "easy", category: "Roupas" },
  { id: "pt-roupa-bone-chapeu", civilWord: "Boné", undercoverWord: "Chapéu", difficulty: "hard", category: "Roupas" },
  { id: "pt-roupa-vestido-saia", civilWord: "Vestido", undercoverWord: "Saia", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-luva-meia", civilWord: "Luva", undercoverWord: "Meia", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-jaqueta-colete", civilWord: "Jaqueta", undercoverWord: "Colete", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-cachecol-gravata", civilWord: "Cachecol", undercoverWord: "Gravata", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-bota-chinelo", civilWord: "Bota", undercoverWord: "Chinelo", difficulty: "easy", category: "Roupas" },
  { id: "pt-roupa-pijama-roupao", civilWord: "Pijama", undercoverWord: "Roupão", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-biquini-maio", civilWord: "Biquíni", undercoverWord: "Maiô", difficulty: "hard", category: "Roupas" },
  { id: "pt-roupa-cinto-suspensorio", civilWord: "Cinto", undercoverWord: "Suspensório", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-moletom-casaco", civilWord: "Moletom", undercoverWord: "Casaco", difficulty: "hard", category: "Roupas" },
  { id: "pt-roupa-sapatilha-salto", civilWord: "Sapatilha", undercoverWord: "Salto alto", difficulty: "normal", category: "Roupas" },
  { id: "pt-roupa-avental-uniforme", civilWord: "Avental", undercoverWord: "Uniforme", difficulty: "normal", category: "Roupas" },

  // ─── Veículos (15) ───
  { id: "pt-veiculo-carro-caminhonete", civilWord: "Carro", undercoverWord: "Caminhonete", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-moto-bicicleta", civilWord: "Moto", undercoverWord: "Bicicleta", difficulty: "easy", category: "Veículos" },
  { id: "pt-veiculo-onibus-van", civilWord: "Ônibus", undercoverWord: "Van", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-aviao-helicoptero", civilWord: "Avião", undercoverWord: "Helicóptero", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-navio-barco", civilWord: "Navio", undercoverWord: "Barco", difficulty: "hard", category: "Veículos" },
  { id: "pt-veiculo-trem-metro", civilWord: "Trem", undercoverWord: "Metrô", difficulty: "hard", category: "Veículos" },
  { id: "pt-veiculo-caminhao-trator", civilWord: "Caminhão", undercoverWord: "Trator", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-ambulancia-bombeiro", civilWord: "Ambulância", undercoverWord: "Carro de bombeiro", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-canoa-caiaque", civilWord: "Canoa", undercoverWord: "Caiaque", difficulty: "hard", category: "Veículos" },
  { id: "pt-veiculo-foguete-satelite", civilWord: "Foguete", undercoverWord: "Satélite", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-patinete-skate", civilWord: "Patinete", undercoverWord: "Skate", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-jipe-quadriciclo", civilWord: "Jipe", undercoverWord: "Quadriciclo", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-veleiro-lancha", civilWord: "Veleiro", undercoverWord: "Lancha", difficulty: "normal", category: "Veículos" },
  { id: "pt-veiculo-taxi-uber", civilWord: "Táxi", undercoverWord: "Uber", difficulty: "hard", category: "Veículos" },
  { id: "pt-veiculo-balao-dirigivel", civilWord: "Balão", undercoverWord: "Dirigível", difficulty: "normal", category: "Veículos" },

  // ─── Profissões (15) ───
  { id: "pt-prof-medico-enfermeiro", civilWord: "Médico", undercoverWord: "Enfermeiro", difficulty: "hard", category: "Profissões" },
  { id: "pt-prof-bombeiro-policial", civilWord: "Bombeiro", undercoverWord: "Policial", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-professor-cientista", civilWord: "Professor", undercoverWord: "Cientista", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-cozinheiro-padeiro", civilWord: "Cozinheiro", undercoverWord: "Padeiro", difficulty: "hard", category: "Profissões" },
  { id: "pt-prof-pintor-escultor", civilWord: "Pintor", undercoverWord: "Escultor", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-astronauta-piloto", civilWord: "Astronauta", undercoverWord: "Piloto", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-pirata-ninja", civilWord: "Pirata", undercoverWord: "Ninja", difficulty: "easy", category: "Profissões" },
  { id: "pt-prof-rei-imperador", civilWord: "Rei", undercoverWord: "Imperador", difficulty: "hard", category: "Profissões" },
  { id: "pt-prof-mago-bruxo", civilWord: "Mago", undercoverWord: "Bruxo", difficulty: "hard", category: "Profissões" },
  { id: "pt-prof-fotografo-cinegrafista", civilWord: "Fotógrafo", undercoverWord: "Cinegrafista", difficulty: "hard", category: "Profissões" },
  { id: "pt-prof-detetive-espiao", civilWord: "Detetive", undercoverWord: "Espião", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-pedreiro-carpinteiro", civilWord: "Pedreiro", undercoverWord: "Carpinteiro", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-veterinario-biologo", civilWord: "Veterinário", undercoverWord: "Biólogo", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-dentista-medico", civilWord: "Dentista", undercoverWord: "Cirurgião", difficulty: "normal", category: "Profissões" },
  { id: "pt-prof-palhaço-magico", civilWord: "Palhaço", undercoverWord: "Mágico", difficulty: "normal", category: "Profissões" },

  // ─── Instrumentos (15) ───
  { id: "pt-inst-violao-ukulele", civilWord: "Violão", undercoverWord: "Ukulele", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-piano-teclado", civilWord: "Piano", undercoverWord: "Teclado", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-bateria-pandeiro", civilWord: "Bateria", undercoverWord: "Pandeiro", difficulty: "normal", category: "Instrumentos" },
  { id: "pt-inst-flauta-clarinete", civilWord: "Flauta", undercoverWord: "Clarinete", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-trompete-trombone", civilWord: "Trompete", undercoverWord: "Trombone", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-violino-violoncelo", civilWord: "Violino", undercoverWord: "Violoncelo", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-harpa-lira", civilWord: "Harpa", undercoverWord: "Lira", difficulty: "normal", category: "Instrumentos" },
  { id: "pt-inst-sanfona-acordeao", civilWord: "Sanfona", undercoverWord: "Acordeão", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-gaita-flauta-doce", civilWord: "Gaita", undercoverWord: "Flauta doce", difficulty: "normal", category: "Instrumentos" },
  { id: "pt-inst-tambor-bongo", civilWord: "Tambor", undercoverWord: "Bongô", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-saxofone-clarinete", civilWord: "Saxofone", undercoverWord: "Oboé", difficulty: "normal", category: "Instrumentos" },
  { id: "pt-inst-triangulo-sino", civilWord: "Triângulo", undercoverWord: "Sino", difficulty: "normal", category: "Instrumentos" },
  { id: "pt-inst-maracas-chocalho", civilWord: "Maracas", undercoverWord: "Chocalho", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-xilofone-metalofone", civilWord: "Xilofone", undercoverWord: "Metalofone", difficulty: "hard", category: "Instrumentos" },
  { id: "pt-inst-guitarra-baixo", civilWord: "Guitarra", undercoverWord: "Baixo", difficulty: "hard", category: "Instrumentos" },

  // ─── Tecnologia (15) ───
  { id: "pt-tech-computador-notebook", civilWord: "Computador", undercoverWord: "Notebook", difficulty: "hard", category: "Tecnologia" },
  { id: "pt-tech-mouse-teclado", civilWord: "Mouse", undercoverWord: "Teclado", difficulty: "easy", category: "Tecnologia" },
  { id: "pt-tech-tv-monitor", civilWord: "TV", undercoverWord: "Monitor", difficulty: "hard", category: "Tecnologia" },
  { id: "pt-tech-fone-caixa-som", civilWord: "Fone de ouvido", undercoverWord: "Caixa de som", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-pendrive-cartao-memoria", civilWord: "Pendrive", undercoverWord: "Cartão de memória", difficulty: "hard", category: "Tecnologia" },
  { id: "pt-tech-impressora-scanner", civilWord: "Impressora", undercoverWord: "Scanner", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-robo-drone", civilWord: "Robô", undercoverWord: "Drone", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-controle-joystick", civilWord: "Controle", undercoverWord: "Joystick", difficulty: "hard", category: "Tecnologia" },
  { id: "pt-tech-webcam-camera", civilWord: "Webcam", undercoverWord: "Câmera", difficulty: "hard", category: "Tecnologia" },
  { id: "pt-tech-smartwatch-relogio", civilWord: "Smartwatch", undercoverWord: "Relógio", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-projetor-tela", civilWord: "Projetor", undercoverWord: "Tela", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-carregador-tomada", civilWord: "Carregador", undercoverWord: "Tomada", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-microfone-megafone", civilWord: "Microfone", undercoverWord: "Megafone", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-console-arcade", civilWord: "Console", undercoverWord: "Arcade", difficulty: "normal", category: "Tecnologia" },
  { id: "pt-tech-lampada-lanterna", civilWord: "Lâmpada", undercoverWord: "Lanterna", difficulty: "normal", category: "Tecnologia" },

  // ─── Escola (15) ───
  { id: "pt-escola-lapis-caneta", civilWord: "Lápis", undercoverWord: "Caneta", difficulty: "easy", category: "Escola" },
  { id: "pt-escola-caderno-agenda", civilWord: "Caderno", undercoverWord: "Agenda", difficulty: "hard", category: "Escola" },
  { id: "pt-escola-borracha-corretivo", civilWord: "Borracha", undercoverWord: "Corretivo", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-mochila-estojo", civilWord: "Mochila", undercoverWord: "Estojo", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-quadro-lousa", civilWord: "Quadro", undercoverWord: "Lousa", difficulty: "hard", category: "Escola" },
  { id: "pt-escola-regua-compasso", civilWord: "Régua", undercoverWord: "Compasso", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-giz-pincel", civilWord: "Giz", undercoverWord: "Pincel", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-globo-mapa", civilWord: "Globo", undercoverWord: "Mapa", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-cola-fita", civilWord: "Cola", undercoverWord: "Fita adesiva", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-calculadora-abaco", civilWord: "Calculadora", undercoverWord: "Ábaco", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-apontador-estilete", civilWord: "Apontador", undercoverWord: "Estilete", difficulty: "normal", category: "Escola" },
  { id: "pt-escola-carteira-mesa", civilWord: "Carteira", undercoverWord: "Mesa", difficulty: "hard", category: "Escola" },
  { id: "pt-escola-tinta-aquarela", civilWord: "Tinta", undercoverWord: "Aquarela", difficulty: "hard", category: "Escola" },
  { id: "pt-escola-lapis-cor-giz-cera", civilWord: "Lápis de cor", undercoverWord: "Giz de cera", difficulty: "hard", category: "Escola" },
  { id: "pt-escola-microscópio-telescopio", civilWord: "Microscópio", undercoverWord: "Telescópio", difficulty: "normal", category: "Escola" },

  // ─── Casa (15) ───
  { id: "pt-casa-sofa-poltrona", civilWord: "Sofá", undercoverWord: "Poltrona", difficulty: "hard", category: "Casa" },
  { id: "pt-casa-cama-rede", civilWord: "Cama", undercoverWord: "Rede", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-chuveiro-banheira", civilWord: "Chuveiro", undercoverWord: "Banheira", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-geladeira-freezer", civilWord: "Geladeira", undercoverWord: "Freezer", difficulty: "hard", category: "Casa" },
  { id: "pt-casa-fogao-forno", civilWord: "Fogão", undercoverWord: "Forno", difficulty: "hard", category: "Casa" },
  { id: "pt-casa-janela-porta", civilWord: "Janela", undercoverWord: "Porta", difficulty: "easy", category: "Casa" },
  { id: "pt-casa-escada-elevador", civilWord: "Escada", undercoverWord: "Elevador", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-tapete-cortina", civilWord: "Tapete", undercoverWord: "Cortina", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-travesseiro-cobertor", civilWord: "Travesseiro", undercoverWord: "Cobertor", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-mesa-cadeira", civilWord: "Mesa", undercoverWord: "Cadeira", difficulty: "easy", category: "Casa" },
  { id: "pt-casa-espelho-quadro", civilWord: "Espelho", undercoverWord: "Quadro", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-ventilador-ar-condicionado", civilWord: "Ventilador", undercoverWord: "Ar-condicionado", difficulty: "normal", category: "Casa" },
  { id: "pt-casa-lustre-luminaria", civilWord: "Lustre", undercoverWord: "Luminária", difficulty: "hard", category: "Casa" },
  { id: "pt-casa-prateleira-estante", civilWord: "Prateleira", undercoverWord: "Estante", difficulty: "hard", category: "Casa" },
  { id: "pt-casa-privada-pia", civilWord: "Privada", undercoverWord: "Pia", difficulty: "normal", category: "Casa" },

  // ─── Clima/Tempo (15) ───
  { id: "pt-clima-chuva-neve", civilWord: "Chuva", undercoverWord: "Neve", difficulty: "easy", category: "Clima" },
  { id: "pt-clima-raio-trovao", civilWord: "Raio", undercoverWord: "Trovão", difficulty: "hard", category: "Clima" },
  { id: "pt-clima-tornado-furacao", civilWord: "Tornado", undercoverWord: "Furacão", difficulty: "hard", category: "Clima" },
  { id: "pt-clima-granizo-saraiva", civilWord: "Granizo", undercoverWord: "Geada", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-vento-brisa", civilWord: "Vento", undercoverWord: "Brisa", difficulty: "hard", category: "Clima" },
  { id: "pt-clima-sol-calor", civilWord: "Sol", undercoverWord: "Calor", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-nevoeiro-fumaca", civilWord: "Nevoeiro", undercoverWord: "Fumaça", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-tempestade-chuva", civilWord: "Tempestade", undercoverWord: "Garoa", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-seca-deserto", civilWord: "Seca", undercoverWord: "Deserto", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-enchente-tsunami", civilWord: "Enchente", undercoverWord: "Tsunami", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-iceberg-geleira", civilWord: "Iceberg", undercoverWord: "Geleira", difficulty: "hard", category: "Clima" },
  { id: "pt-clima-avalanche-deslizamento", civilWord: "Avalanche", undercoverWord: "Deslizamento", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-por-do-sol-nascer-sol", civilWord: "Pôr do sol", undercoverWord: "Nascer do sol", difficulty: "hard", category: "Clima" },
  { id: "pt-clima-orvalho-gota", civilWord: "Orvalho", undercoverWord: "Gota", difficulty: "normal", category: "Clima" },
  { id: "pt-clima-floco-neve-cristal-gelo", civilWord: "Floco de neve", undercoverWord: "Cristal de gelo", difficulty: "hard", category: "Clima" },

  // ─── Fantasia (15) ───
  { id: "pt-fantasia-dragao-dinossauro", civilWord: "Dragão", undercoverWord: "Dinossauro", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-unicornio-pegaso", civilWord: "Unicórnio", undercoverWord: "Pégaso", difficulty: "hard", category: "Fantasia" },
  { id: "pt-fantasia-fada-anjo", civilWord: "Fada", undercoverWord: "Anjo", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-vampiro-zumbi", civilWord: "Vampiro", undercoverWord: "Zumbi", difficulty: "easy", category: "Fantasia" },
  { id: "pt-fantasia-bruxa-feiticeiro", civilWord: "Bruxa", undercoverWord: "Feiticeiro", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-fantasma-esqueleto", civilWord: "Fantasma", undercoverWord: "Esqueleto", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-sereia-tritao", civilWord: "Sereia", undercoverWord: "Tritão", difficulty: "hard", category: "Fantasia" },
  { id: "pt-fantasia-lobisomem-yeti", civilWord: "Lobisomem", undercoverWord: "Yeti", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-duende-gnomo", civilWord: "Duende", undercoverWord: "Gnomo", difficulty: "hard", category: "Fantasia" },
  { id: "pt-fantasia-ciclope-gigante", civilWord: "Ciclope", undercoverWord: "Gigante", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-fenix-grifo", civilWord: "Fênix", undercoverWord: "Grifo", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-mumia-zumbi", civilWord: "Múmia", undercoverWord: "Zumbi", difficulty: "hard", category: "Fantasia" },
  { id: "pt-fantasia-genio-espirito", civilWord: "Gênio", undercoverWord: "Espírito", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-cavaleiro-samurai", civilWord: "Cavaleiro", undercoverWord: "Samurai", difficulty: "normal", category: "Fantasia" },
  { id: "pt-fantasia-troll-ogro", civilWord: "Troll", undercoverWord: "Ogro", difficulty: "hard", category: "Fantasia" },

  // ─── Espaço (15) ───
  { id: "pt-espaco-planeta-estrela", civilWord: "Planeta", undercoverWord: "Estrela", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-lua-asteroide", civilWord: "Lua", undercoverWord: "Asteroide", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-foguete-nave", civilWord: "Foguete", undercoverWord: "Nave espacial", difficulty: "hard", category: "Espaço" },
  { id: "pt-espaco-astronauta-alienigena", civilWord: "Astronauta", undercoverWord: "Alienígena", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-saturno-jupiter", civilWord: "Saturno", undercoverWord: "Júpiter", difficulty: "hard", category: "Espaço" },
  { id: "pt-espaco-sol-buraco-negro", civilWord: "Sol", undercoverWord: "Buraco negro", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-cometa-meteoro", civilWord: "Cometa", undercoverWord: "Meteoro", difficulty: "hard", category: "Espaço" },
  { id: "pt-espaco-galaxia-nebulosa", civilWord: "Galáxia", undercoverWord: "Nebulosa", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-telescopio-observatorio", civilWord: "Telescópio", undercoverWord: "Observatório", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-satelite-estacao", civilWord: "Satélite", undercoverWord: "Estação espacial", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-ovni-disco-voador", civilWord: "OVNI", undercoverWord: "Disco voador", difficulty: "hard", category: "Espaço" },
  { id: "pt-espaco-terra-marte", civilWord: "Terra", undercoverWord: "Marte", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-eclipse-constelacao", civilWord: "Eclipse", undercoverWord: "Constelação", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-crater-vulcao", civilWord: "Cratera", undercoverWord: "Vulcão", difficulty: "normal", category: "Espaço" },
  { id: "pt-espaco-robo-espacial-rover", civilWord: "Robô espacial", undercoverWord: "Rover", difficulty: "hard", category: "Espaço" },

  // ─── Praia (15) ───
  { id: "pt-praia-prancha-bodyboard", civilWord: "Prancha de surf", undercoverWord: "Bodyboard", difficulty: "hard", category: "Praia" },
  { id: "pt-praia-concha-estrela-mar", civilWord: "Concha", undercoverWord: "Estrela-do-mar", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-balde-pa", civilWord: "Balde", undercoverWord: "Pá", difficulty: "easy", category: "Praia" },
  { id: "pt-praia-castelo-areia-escultura", civilWord: "Castelo de areia", undercoverWord: "Escultura de areia", difficulty: "hard", category: "Praia" },
  { id: "pt-praia-guarda-sol-barraca", civilWord: "Guarda-sol", undercoverWord: "Barraca", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-boia-colchao", civilWord: "Boia", undercoverWord: "Colchão inflável", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-oculos-sol-viseira", civilWord: "Óculos de sol", undercoverWord: "Viseira", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-protetor-bronzeador", civilWord: "Protetor solar", undercoverWord: "Bronzeador", difficulty: "hard", category: "Praia" },
  { id: "pt-praia-toalha-canga", civilWord: "Toalha", undercoverWord: "Canga", difficulty: "hard", category: "Praia" },
  { id: "pt-praia-caranguejo-siri", civilWord: "Caranguejo", undercoverWord: "Siri", difficulty: "hard", category: "Praia" },
  { id: "pt-praia-gaivota-pelicano", civilWord: "Gaivota", undercoverWord: "Pelicano", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-ancora-boia-sinalizacao", civilWord: "Âncora", undercoverWord: "Boia", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-jet-ski-banana-boat", civilWord: "Jet ski", undercoverWord: "Banana boat", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-snorkel-mergulho", civilWord: "Snorkel", undercoverWord: "Mergulho", difficulty: "normal", category: "Praia" },
  { id: "pt-praia-agua-viva-medusa", civilWord: "Água-viva", undercoverWord: "Medusa", difficulty: "hard", category: "Praia" },

  // ─── Festa (15) ───
  { id: "pt-festa-balao-pipa", civilWord: "Balão", undercoverWord: "Pipa", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-bolo-torta", civilWord: "Bolo de festa", undercoverWord: "Torta", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-mascara-fantasia", civilWord: "Máscara", undercoverWord: "Fantasia", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-confete-serpentina", civilWord: "Confete", undercoverWord: "Serpentina", difficulty: "hard", category: "Festa" },
  { id: "pt-festa-vela-lamparina", civilWord: "Vela de aniversário", undercoverWord: "Lamparina", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-chapeu-coroa", civilWord: "Chapéu de festa", undercoverWord: "Coroa", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-presente-caixa", civilWord: "Presente", undercoverWord: "Caixa", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-fogos-artificio-sinalizador", civilWord: "Fogos de artifício", undercoverWord: "Sinalizador", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-pinhata-boneco", civilWord: "Pinhata", undercoverWord: "Boneco", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-dj-banda", civilWord: "DJ", undercoverWord: "Banda", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-karaoke-microfone", civilWord: "Karaokê", undercoverWord: "Microfone", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-convite-cartao", civilWord: "Convite", undercoverWord: "Cartão", difficulty: "hard", category: "Festa" },
  { id: "pt-festa-palco-pista", civilWord: "Palco", undercoverWord: "Pista de dança", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-touca-peruca", civilWord: "Touca", undercoverWord: "Peruca", difficulty: "normal", category: "Festa" },
  { id: "pt-festa-espuma-bolha-sabao", civilWord: "Espuma", undercoverWord: "Bolha de sabão", difficulty: "normal", category: "Festa" },

  // ─── Cozinha (15) ───
  { id: "pt-cozinha-panela-frigideira", civilWord: "Panela", undercoverWord: "Frigideira", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-garfo-colher", civilWord: "Garfo", undercoverWord: "Colher", difficulty: "easy", category: "Cozinha" },
  { id: "pt-cozinha-prato-tigela", civilWord: "Prato", undercoverWord: "Tigela", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-liquidificador-batedeira", civilWord: "Liquidificador", undercoverWord: "Batedeira", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-forno-micro-ondas", civilWord: "Forno", undercoverWord: "Micro-ondas", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-tabua-rolo", civilWord: "Tábua de corte", undercoverWord: "Rolo de massa", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-chaleira-cafeteira", civilWord: "Chaleira", undercoverWord: "Cafeteira", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-espátula-concha", civilWord: "Espátula", undercoverWord: "Concha", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-ralador-espremedor", civilWord: "Ralador", undercoverWord: "Espremedor", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-peneira-escorredor", civilWord: "Peneira", undercoverWord: "Escorredor", difficulty: "hard", category: "Cozinha" },
  { id: "pt-cozinha-abridor-saca-rolhas", civilWord: "Abridor", undercoverWord: "Saca-rolhas", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-torradeira-sanduicheira", civilWord: "Torradeira", undercoverWord: "Sanduicheira", difficulty: "hard", category: "Cozinha" },
  { id: "pt-cozinha-jarra-garrafa", civilWord: "Jarra", undercoverWord: "Garrafa", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-avental-luva-forno", civilWord: "Avental", undercoverWord: "Luva de forno", difficulty: "normal", category: "Cozinha" },
  { id: "pt-cozinha-forma-assadeira", civilWord: "Forma", undercoverWord: "Assadeira", difficulty: "hard", category: "Cozinha" },

  // ─── Jardim (15) ───
  { id: "pt-jardim-regador-mangueira", civilWord: "Regador", undercoverWord: "Mangueira", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-vaso-jardineira", civilWord: "Vaso", undercoverWord: "Jardineira", difficulty: "hard", category: "Jardim" },
  { id: "pt-jardim-pa-enxada", civilWord: "Pá", undercoverWord: "Enxada", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-cerca-muro", civilWord: "Cerca", undercoverWord: "Muro", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-gramado-canteiro", civilWord: "Gramado", undercoverWord: "Canteiro", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-tesoura-podador", civilWord: "Tesoura de poda", undercoverWord: "Podador", difficulty: "hard", category: "Jardim" },
  { id: "pt-jardim-espantalho-boneco", civilWord: "Espantalho", undercoverWord: "Boneco", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-carrinho-mao-balde", civilWord: "Carrinho de mão", undercoverWord: "Balde", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-semente-muda", civilWord: "Semente", undercoverWord: "Muda", difficulty: "hard", category: "Jardim" },
  { id: "pt-jardim-joaninha-formiga", civilWord: "Joaninha", undercoverWord: "Formiga", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-fonte-chafariz", civilWord: "Fonte", undercoverWord: "Chafariz", difficulty: "hard", category: "Jardim" },
  { id: "pt-jardim-rede-balanco", civilWord: "Rede", undercoverWord: "Balanço", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-gnomo-estatua", civilWord: "Gnomo", undercoverWord: "Estátua", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-composteira-lixeira", civilWord: "Composteira", undercoverWord: "Lixeira", difficulty: "normal", category: "Jardim" },
  { id: "pt-jardim-girassol-margarida", civilWord: "Girassol", undercoverWord: "Margarida", difficulty: "normal", category: "Jardim" },

  // ─── Brinquedos (15) ───
  { id: "pt-brinquedo-boneca-boneco", civilWord: "Boneca", undercoverWord: "Boneco de ação", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-carrinho-pista", civilWord: "Carrinho", undercoverWord: "Pista de corrida", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-lego-quebra-cabeca", civilWord: "Lego", undercoverWord: "Quebra-cabeça", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-piao-ioio", civilWord: "Pião", undercoverWord: "Ioiô", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-bola-peteca", civilWord: "Bola", undercoverWord: "Peteca", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-pipa-frisbee", civilWord: "Pipa", undercoverWord: "Frisbee", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-pelucia-almofada", civilWord: "Pelúcia", undercoverWord: "Almofada", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-massinha-slime", civilWord: "Massinha", undercoverWord: "Slime", difficulty: "hard", category: "Brinquedos" },
  { id: "pt-brinquedo-dado-roleta", civilWord: "Dado", undercoverWord: "Roleta", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-balanco-escorregador", civilWord: "Balanço", undercoverWord: "Escorregador", difficulty: "easy", category: "Brinquedos" },
  { id: "pt-brinquedo-triciclo-patinete", civilWord: "Triciclo", undercoverWord: "Patinete", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-marionete-fantoche", civilWord: "Marionete", undercoverWord: "Fantoche", difficulty: "hard", category: "Brinquedos" },
  { id: "pt-brinquedo-bolha-sabao-balao", civilWord: "Bolha de sabão", undercoverWord: "Balão", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-domino-jogo-cartas", civilWord: "Dominó", undercoverWord: "Jogo de cartas", difficulty: "normal", category: "Brinquedos" },
  { id: "pt-brinquedo-cubo-magico-tangram", civilWord: "Cubo mágico", undercoverWord: "Tangram", difficulty: "normal", category: "Brinquedos" }
];

export const PT_WORD_CATEGORIES = [
  "Tudo",
  "Comida",
  "Bebidas",
  "Animais",
  "Objetos",
  "Esportes",
  "Cultura Pop",
  "Lugares",
  "Natureza",
  "Corpo Humano",
  "Roupas",
  "Veículos",
  "Profissões",
  "Instrumentos",
  "Tecnologia",
  "Escola",
  "Casa",
  "Clima",
  "Fantasia",
  "Espaço",
  "Praia",
  "Festa",
  "Cozinha",
  "Jardim",
  "Brinquedos"
];
