import type { WordPair } from "./protocol.js";

export const BASE_WORD_PAIRS: WordPair[] = [
  // ─── Nourriture (15) ───
  { id: "food-pizza-galette", civilWord: "Pizza", undercoverWord: "Galette", difficulty: "normal", category: "Nourriture" },
  { id: "food-sushi-onigiri", civilWord: "Sushi", undercoverWord: "Onigiri", difficulty: "hard", category: "Nourriture" },
  { id: "food-croissant-bretzel", civilWord: "Croissant", undercoverWord: "Bretzel", difficulty: "normal", category: "Nourriture" },
  { id: "food-hamburger-sandwich", civilWord: "Hamburger", undercoverWord: "Sandwich", difficulty: "easy", category: "Nourriture" },
  { id: "food-icecream-cupcake", civilWord: "Glace", undercoverWord: "Cupcake", difficulty: "normal", category: "Nourriture" },
  { id: "food-spaghetti-ramen", civilWord: "Spaghetti", undercoverWord: "Ramen", difficulty: "hard", category: "Nourriture" },
  { id: "food-baguette-baton", civilWord: "Baguette", undercoverWord: "Bâton de pain", difficulty: "hard", category: "Nourriture" },
  { id: "food-pancake-crepe", civilWord: "Pancake", undercoverWord: "Crêpe", difficulty: "hard", category: "Nourriture" },
  { id: "food-donut-bagel", civilWord: "Donut", undercoverWord: "Bagel", difficulty: "normal", category: "Nourriture" },
  { id: "food-popcorn-cereales", civilWord: "Popcorn", undercoverWord: "Céréales", difficulty: "normal", category: "Nourriture" },
  { id: "food-frites-potatoes", civilWord: "Frites", undercoverWord: "Potatoes", difficulty: "normal", category: "Nourriture" },
  { id: "food-tacos-burrito", civilWord: "Tacos", undercoverWord: "Burrito", difficulty: "hard", category: "Nourriture" },
  { id: "food-fromage-beurre", civilWord: "Fromage", undercoverWord: "Beurre", difficulty: "normal", category: "Nourriture" },
  { id: "food-gateau-tarte", civilWord: "Gâteau", undercoverWord: "Tarte", difficulty: "normal", category: "Nourriture" },
  { id: "food-bonbon-chocolat", civilWord: "Bonbon", undercoverWord: "Chocolat", difficulty: "easy", category: "Nourriture" },
  { id: "food-kebab-hotdog", civilWord: "Kebab", undercoverWord: "Hot-dog", difficulty: "normal", category: "Nourriture" },
  { id: "food-cookie-macaron", civilWord: "Cookie", undercoverWord: "Macaron", difficulty: "normal", category: "Nourriture" },
  { id: "food-churros-beignet", civilWord: "Churros", undercoverWord: "Beignet", difficulty: "normal", category: "Nourriture" },
  { id: "food-ravioli-dumpling", civilWord: "Ravioli", undercoverWord: "Dumpling", difficulty: "hard", category: "Nourriture" },
  { id: "food-nuggets-cordonbleu", civilWord: "Nuggets", undercoverWord: "Cordon bleu", difficulty: "normal", category: "Nourriture" },
  { id: "food-waffle-gaufre", civilWord: "Gaufre", undercoverWord: "Pancake", difficulty: "hard", category: "Nourriture" },

  // ─── Boissons (10) ───
  { id: "drink-cafe-the", civilWord: "Café", undercoverWord: "Thé", difficulty: "easy", category: "Boissons" },
  { id: "drink-jus-smoothie", civilWord: "Jus d'orange", undercoverWord: "Smoothie", difficulty: "normal", category: "Boissons" },
  { id: "drink-coca-pepsi", civilWord: "Coca", undercoverWord: "Pepsi", difficulty: "hard", category: "Boissons" },
  { id: "drink-lait-yaourt", civilWord: "Lait", undercoverWord: "Yaourt", difficulty: "normal", category: "Boissons" },
  { id: "drink-eau-glacon", civilWord: "Eau", undercoverWord: "Glaçon", difficulty: "normal", category: "Boissons" },
  { id: "drink-chocolatchaud-capuccino", civilWord: "Chocolat chaud", undercoverWord: "Cappuccino", difficulty: "hard", category: "Boissons" },
  { id: "drink-limonade-orangina", civilWord: "Limonade", undercoverWord: "Orangina", difficulty: "normal", category: "Boissons" },
  { id: "drink-milkshake-frappuccino", civilWord: "Milkshake", undercoverWord: "Frappuccino", difficulty: "hard", category: "Boissons" },
  { id: "drink-sirop-miel", civilWord: "Sirop", undercoverWord: "Miel", difficulty: "normal", category: "Boissons" },
  { id: "drink-biere-cidre", civilWord: "Bière", undercoverWord: "Cidre", difficulty: "normal", category: "Boissons" },
  { id: "drink-bubbletea-granite", civilWord: "Bubble tea", undercoverWord: "Granité", difficulty: "normal", category: "Boissons" },
  { id: "drink-soda-eaugazeuse", civilWord: "Soda", undercoverWord: "Eau gazeuse", difficulty: "normal", category: "Boissons" },
  { id: "drink-tisane-infusion", civilWord: "Tisane", undercoverWord: "Infusion", difficulty: "hard", category: "Boissons" },
  { id: "drink-juspomme-compote", civilWord: "Jus de pomme", undercoverWord: "Compote", difficulty: "normal", category: "Boissons" },

  // ─── Animaux (15) ───
  { id: "animal-chat-tigre", civilWord: "Chat", undercoverWord: "Tigre", difficulty: "easy", category: "Animaux" },
  { id: "animal-chien-loup", civilWord: "Chien", undercoverWord: "Loup", difficulty: "normal", category: "Animaux" },
  { id: "animal-pingouin-canard", civilWord: "Pingouin", undercoverWord: "Canard", difficulty: "normal", category: "Animaux" },
  { id: "animal-tortue-escargot", civilWord: "Tortue", undercoverWord: "Escargot", difficulty: "normal", category: "Animaux" },
  { id: "animal-requin-dauphin", civilWord: "Requin", undercoverWord: "Dauphin", difficulty: "easy", category: "Animaux" },
  { id: "animal-abeille-guepe", civilWord: "Abeille", undercoverWord: "Guêpe", difficulty: "hard", category: "Animaux" },
  { id: "animal-crocodile-lezard", civilWord: "Crocodile", undercoverWord: "Lézard", difficulty: "normal", category: "Animaux" },
  { id: "animal-panda-ours", civilWord: "Panda", undercoverWord: "Ours", difficulty: "normal", category: "Animaux" },
  { id: "animal-papillon-libellule", civilWord: "Papillon", undercoverWord: "Libellule", difficulty: "normal", category: "Animaux" },
  { id: "animal-pieuvre-meduse", civilWord: "Pieuvre", undercoverWord: "Méduse", difficulty: "normal", category: "Animaux" },
  { id: "animal-aigle-faucon", civilWord: "Aigle", undercoverWord: "Faucon", difficulty: "hard", category: "Animaux" },
  { id: "animal-cheval-zebre", civilWord: "Cheval", undercoverWord: "Zèbre", difficulty: "easy", category: "Animaux" },
  { id: "animal-souris-hamster", civilWord: "Souris", undercoverWord: "Hamster", difficulty: "normal", category: "Animaux" },
  { id: "animal-lion-leopard", civilWord: "Lion", undercoverWord: "Léopard", difficulty: "hard", category: "Animaux" },
  { id: "animal-poule-dinde", civilWord: "Poule", undercoverWord: "Dinde", difficulty: "normal", category: "Animaux" },
  { id: "animal-koala-paresseux", civilWord: "Koala", undercoverWord: "Paresseux", difficulty: "normal", category: "Animaux" },
  { id: "animal-flamant-perroquet", civilWord: "Flamant rose", undercoverWord: "Perroquet", difficulty: "normal", category: "Animaux" },
  { id: "animal-araignee-scorpion", civilWord: "Araignée", undercoverWord: "Scorpion", difficulty: "normal", category: "Animaux" },
  { id: "animal-herisson-porcepic", civilWord: "Hérisson", undercoverWord: "Porc-épic", difficulty: "hard", category: "Animaux" },
  { id: "animal-renard-coyote", civilWord: "Renard", undercoverWord: "Coyote", difficulty: "hard", category: "Animaux" },
  { id: "animal-girafe-autruche", civilWord: "Girafe", undercoverWord: "Autruche", difficulty: "easy", category: "Animaux" },
  { id: "animal-phoque-morse", civilWord: "Phoque", undercoverWord: "Morse", difficulty: "hard", category: "Animaux" },

  // ─── Objets (15) ───
  { id: "object-chaise-tabouret", civilWord: "Chaise", undercoverWord: "Tabouret", difficulty: "normal", category: "Objets" },
  { id: "object-velo-trottinette", civilWord: "Vélo", undercoverWord: "Trottinette", difficulty: "easy", category: "Objets" },
  { id: "object-lunettes-jumelles", civilWord: "Lunettes", undercoverWord: "Jumelles", difficulty: "normal", category: "Objets" },
  { id: "object-parapluie-parasol", civilWord: "Parapluie", undercoverWord: "Parasol", difficulty: "hard", category: "Objets" },
  { id: "object-guitare-violon", civilWord: "Guitare", undercoverWord: "Violon", difficulty: "normal", category: "Objets" },
  { id: "object-telephone-telecommande", civilWord: "Téléphone", undercoverWord: "Télécommande", difficulty: "normal", category: "Objets" },
  { id: "object-bougie-lampe", civilWord: "Bougie", undercoverWord: "Lampe", difficulty: "easy", category: "Objets" },
  { id: "object-epee-couteau", civilWord: "Épée", undercoverWord: "Couteau", difficulty: "normal", category: "Objets" },
  { id: "object-cle-serrure", civilWord: "Clé", undercoverWord: "Serrure", difficulty: "normal", category: "Objets" },
  { id: "object-livre-tablette", civilWord: "Livre", undercoverWord: "Tablette", difficulty: "normal", category: "Objets" },
  { id: "object-montre-horloge", civilWord: "Montre", undercoverWord: "Horloge", difficulty: "easy", category: "Objets" },
  { id: "object-valise-sacados", civilWord: "Valise", undercoverWord: "Sac à dos", difficulty: "normal", category: "Objets" },
  { id: "object-ciseaux-tondeuse", civilWord: "Ciseaux", undercoverWord: "Tondeuse", difficulty: "normal", category: "Objets" },
  { id: "object-miroir-vitre", civilWord: "Miroir", undercoverWord: "Vitre", difficulty: "hard", category: "Objets" },
  { id: "object-balai-aspirateur", civilWord: "Balai", undercoverWord: "Aspirateur", difficulty: "normal", category: "Objets" },
  { id: "object-aimant-boussole", civilWord: "Aimant", undercoverWord: "Boussole", difficulty: "normal", category: "Objets" },
  { id: "object-de-domino", civilWord: "Dé", undercoverWord: "Domino", difficulty: "easy", category: "Objets" },
  { id: "object-oreiller-coussin", civilWord: "Oreiller", undercoverWord: "Coussin", difficulty: "hard", category: "Objets" },
  { id: "object-loupe-telescope", civilWord: "Loupe", undercoverWord: "Télescope", difficulty: "normal", category: "Objets" },
  { id: "object-pinceau-rouleau", civilWord: "Pinceau", undercoverWord: "Rouleau", difficulty: "normal", category: "Objets" },

  // ─── Lieux (15) ───
  { id: "place-toureiffel-liberte", civilWord: "Tour Eiffel", undercoverWord: "Statue de la Liberté", difficulty: "easy", category: "Lieux" },
  { id: "place-pyramide-montagne", civilWord: "Pyramide", undercoverWord: "Montagne", difficulty: "normal", category: "Lieux" },
  { id: "place-hopital-pharmacie", civilWord: "Hôpital", undercoverWord: "Pharmacie", difficulty: "hard", category: "Lieux" },
  { id: "place-ecole-prison", civilWord: "École", undercoverWord: "Prison", difficulty: "normal", category: "Lieux" },
  { id: "place-plage-desert", civilWord: "Plage", undercoverWord: "Désert", difficulty: "normal", category: "Lieux" },
  { id: "place-chateau-eglise", civilWord: "Château", undercoverWord: "Église", difficulty: "normal", category: "Lieux" },
  { id: "place-piscine-lac", civilWord: "Piscine", undercoverWord: "Lac", difficulty: "normal", category: "Lieux" },
  { id: "place-fusee-avion", civilWord: "Fusée", undercoverWord: "Avion", difficulty: "easy", category: "Lieux" },
  { id: "place-stade-cirque", civilWord: "Stade", undercoverWord: "Cirque", difficulty: "normal", category: "Lieux" },
  { id: "place-cinema-theatre", civilWord: "Cinéma", undercoverWord: "Théâtre", difficulty: "hard", category: "Lieux" },
  { id: "place-resto-cantine", civilWord: "Restaurant", undercoverWord: "Cantine", difficulty: "normal", category: "Lieux" },
  { id: "place-foret-jungle", civilWord: "Forêt", undercoverWord: "Jungle", difficulty: "hard", category: "Lieux" },
  { id: "place-grotte-tunnel", civilWord: "Grotte", undercoverWord: "Tunnel", difficulty: "normal", category: "Lieux" },
  { id: "place-ile-continent", civilWord: "Île", undercoverWord: "Continent", difficulty: "hard", category: "Lieux" },
  { id: "place-zoo-aquarium", civilWord: "Zoo", undercoverWord: "Aquarium", difficulty: "easy", category: "Lieux" },
  { id: "place-phare-tour", civilWord: "Phare", undercoverWord: "Tour", difficulty: "normal", category: "Lieux" },
  { id: "place-igloo-tipi", civilWord: "Igloo", undercoverWord: "Tipi", difficulty: "easy", category: "Lieux" },
  { id: "place-labyrinthe-grotte2", civilWord: "Labyrinthe", undercoverWord: "Grotte", difficulty: "normal", category: "Lieux" },
  { id: "place-volcan-montagne2", civilWord: "Volcan", undercoverWord: "Montagne", difficulty: "easy", category: "Lieux" },
  { id: "place-camping-cabane", civilWord: "Camping", undercoverWord: "Cabane", difficulty: "normal", category: "Lieux" },

  // ─── Sports (15) ───
  { id: "sport-foot-rugby", civilWord: "Football", undercoverWord: "Rugby", difficulty: "easy", category: "Sports" },
  { id: "sport-basket-handball", civilWord: "Basketball", undercoverWord: "Handball", difficulty: "normal", category: "Sports" },
  { id: "sport-tennis-badminton", civilWord: "Tennis", undercoverWord: "Badminton", difficulty: "normal", category: "Sports" },
  { id: "sport-ski-snowboard", civilWord: "Ski", undercoverWord: "Snowboard", difficulty: "normal", category: "Sports" },
  { id: "sport-boxe-karate", civilWord: "Boxe", undercoverWord: "Karaté", difficulty: "normal", category: "Sports" },
  { id: "sport-natation-plongee", civilWord: "Natation", undercoverWord: "Plongée", difficulty: "normal", category: "Sports" },
  { id: "sport-surf-wakeboard", civilWord: "Surf", undercoverWord: "Wakeboard", difficulty: "hard", category: "Sports" },
  { id: "sport-escalade-randonnee", civilWord: "Escalade", undercoverWord: "Randonnée", difficulty: "normal", category: "Sports" },
  { id: "sport-golf-billard", civilWord: "Golf", undercoverWord: "Billard", difficulty: "normal", category: "Sports" },
  { id: "sport-velo-moto", civilWord: "Cyclisme", undercoverWord: "Moto", difficulty: "easy", category: "Sports" },
  { id: "sport-danse-gym", civilWord: "Danse", undercoverWord: "Gymnastique", difficulty: "normal", category: "Sports" },
  { id: "sport-skate-roller", civilWord: "Skateboard", undercoverWord: "Roller", difficulty: "normal", category: "Sports" },
  { id: "sport-catch-judo", civilWord: "Catch", undercoverWord: "Judo", difficulty: "hard", category: "Sports" },
  { id: "sport-ping-pong-squash", civilWord: "Ping-pong", undercoverWord: "Squash", difficulty: "hard", category: "Sports" },
  { id: "sport-arc-flechettes", civilWord: "Tir à l'arc", undercoverWord: "Fléchettes", difficulty: "normal", category: "Sports" },
  { id: "sport-yoga-pilates", civilWord: "Yoga", undercoverWord: "Pilates", difficulty: "hard", category: "Sports" },
  { id: "sport-escrime-sabre", civilWord: "Escrime", undercoverWord: "Sabre", difficulty: "normal", category: "Sports" },
  { id: "sport-parachute-deltaplane", civilWord: "Parachute", undercoverWord: "Deltaplane", difficulty: "normal", category: "Sports" },
  { id: "sport-musculation-fitness", civilWord: "Musculation", undercoverWord: "Fitness", difficulty: "hard", category: "Sports" },
  { id: "sport-trampoline-toboggan", civilWord: "Trampoline", undercoverWord: "Toboggan", difficulty: "easy", category: "Sports" },

  // ─── Métiers (12) ───
  { id: "job-pompier-policier", civilWord: "Pompier", undercoverWord: "Policier", difficulty: "easy", category: "Métiers" },
  { id: "job-medecin-infirmier", civilWord: "Médecin", undercoverWord: "Infirmier", difficulty: "normal", category: "Métiers" },
  { id: "job-prof-directeur", civilWord: "Professeur", undercoverWord: "Directeur", difficulty: "normal", category: "Métiers" },
  { id: "job-cuisinier-boulanger", civilWord: "Cuisinier", undercoverWord: "Boulanger", difficulty: "normal", category: "Métiers" },
  { id: "job-pilote-chauffeur", civilWord: "Pilote", undercoverWord: "Chauffeur", difficulty: "normal", category: "Métiers" },
  { id: "job-astronaute-plongeur", civilWord: "Astronaute", undercoverWord: "Plongeur", difficulty: "normal", category: "Métiers" },
  { id: "job-dentiste-chirurgien", civilWord: "Dentiste", undercoverWord: "Chirurgien", difficulty: "hard", category: "Métiers" },
  { id: "job-photographe-cameraman", civilWord: "Photographe", undercoverWord: "Caméraman", difficulty: "hard", category: "Métiers" },
  { id: "job-magicien-clown", civilWord: "Magicien", undercoverWord: "Clown", difficulty: "easy", category: "Métiers" },
  { id: "job-pirate-viking", civilWord: "Pirate", undercoverWord: "Viking", difficulty: "normal", category: "Métiers" },
  { id: "job-espion-detective", civilWord: "Espion", undercoverWord: "Détective", difficulty: "normal", category: "Métiers" },
  { id: "job-ninja-samourai", civilWord: "Ninja", undercoverWord: "Samouraï", difficulty: "normal", category: "Métiers" },
  { id: "job-veterinaire-docteur", civilWord: "Vétérinaire", undercoverWord: "Docteur", difficulty: "normal", category: "Métiers" },
  { id: "job-facteur-livreur", civilWord: "Facteur", undercoverWord: "Livreur", difficulty: "normal", category: "Métiers" },
  { id: "job-fermier-jardinier", civilWord: "Fermier", undercoverWord: "Jardinier", difficulty: "easy", category: "Métiers" },
  { id: "job-artiste-sculpteur", civilWord: "Artiste", undercoverWord: "Sculpteur", difficulty: "normal", category: "Métiers" },
  { id: "job-serveur-barman", civilWord: "Serveur", undercoverWord: "Barman", difficulty: "normal", category: "Métiers" },

  // ─── Vêtements & Mode (10) ───
  { id: "cloth-chapeau-casquette", civilWord: "Chapeau", undercoverWord: "Casquette", difficulty: "easy", category: "Vêtements" },
  { id: "cloth-chaussure-botte", civilWord: "Chaussure", undercoverWord: "Botte", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-pull-gilet", civilWord: "Pull", undercoverWord: "Gilet", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-robe-jupe", civilWord: "Robe", undercoverWord: "Jupe", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-cravate-noeudpap", civilWord: "Cravate", undercoverWord: "Noeud papillon", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-gant-moufle", civilWord: "Gant", undercoverWord: "Moufle", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-echarpe-foulard", civilWord: "Écharpe", undercoverWord: "Foulard", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-short-pantalon", civilWord: "Short", undercoverWord: "Pantalon", difficulty: "easy", category: "Vêtements" },
  { id: "cloth-tong-sandale", civilWord: "Tong", undercoverWord: "Sandale", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-costume-pyjama", civilWord: "Costume", undercoverWord: "Pyjama", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-manteau-impermeable", civilWord: "Manteau", undercoverWord: "Imperméable", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-ceinture-bretelles", civilWord: "Ceinture", undercoverWord: "Bretelles", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-maillot-short", civilWord: "Maillot de bain", undercoverWord: "Short de bain", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-bonnet-cagoule", civilWord: "Bonnet", undercoverWord: "Cagoule", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-lunettes-soleil-visiere", civilWord: "Lunettes de soleil", undercoverWord: "Visière", difficulty: "normal", category: "Vêtements" },

  // ─── Transport (10) ───
  { id: "trans-voiture-camion", civilWord: "Voiture", undercoverWord: "Camion", difficulty: "easy", category: "Transport" },
  { id: "trans-train-metro", civilWord: "Train", undercoverWord: "Métro", difficulty: "normal", category: "Transport" },
  { id: "trans-bateau-canoe", civilWord: "Bateau", undercoverWord: "Canoë", difficulty: "normal", category: "Transport" },
  { id: "trans-helico-drone", civilWord: "Hélicoptère", undercoverWord: "Drone", difficulty: "normal", category: "Transport" },
  { id: "trans-bus-tramway", civilWord: "Bus", undercoverWord: "Tramway", difficulty: "normal", category: "Transport" },
  { id: "trans-sousmarin-bateau", civilWord: "Sous-marin", undercoverWord: "Navire", difficulty: "normal", category: "Transport" },
  { id: "trans-ambulance-pompier", civilWord: "Ambulance", undercoverWord: "Camion de pompier", difficulty: "normal", category: "Transport" },
  { id: "trans-tank-bulldozer", civilWord: "Tank", undercoverWord: "Bulldozer", difficulty: "normal", category: "Transport" },
  { id: "trans-mongolfiere-parachute", civilWord: "Montgolfière", undercoverWord: "Parachute", difficulty: "normal", category: "Transport" },
  { id: "trans-quad-motoneige", civilWord: "Quad", undercoverWord: "Motoneige", difficulty: "hard", category: "Transport" },
  { id: "trans-jetski-canoe", civilWord: "Jet ski", undercoverWord: "Canoë", difficulty: "normal", category: "Transport" },
  { id: "trans-trottinette-skate", civilWord: "Trottinette", undercoverWord: "Skateboard", difficulty: "easy", category: "Transport" },
  { id: "trans-telepherique-funiculaire", civilWord: "Téléphérique", undercoverWord: "Funiculaire", difficulty: "hard", category: "Transport" },
  { id: "trans-caravane-campingcar", civilWord: "Caravane", undercoverWord: "Camping-car", difficulty: "hard", category: "Transport" },

  // ─── Nature (10) ───
  { id: "nat-soleil-lune", civilWord: "Soleil", undercoverWord: "Lune", difficulty: "easy", category: "Nature" },
  { id: "nat-arc-en-ciel-aurore", civilWord: "Arc-en-ciel", undercoverWord: "Aurore boréale", difficulty: "normal", category: "Nature" },
  { id: "nat-volcan-geyser", civilWord: "Volcan", undercoverWord: "Geyser", difficulty: "normal", category: "Nature" },
  { id: "nat-cascade-fontaine", civilWord: "Cascade", undercoverWord: "Fontaine", difficulty: "normal", category: "Nature" },
  { id: "nat-nuage-brouillard", civilWord: "Nuage", undercoverWord: "Brouillard", difficulty: "hard", category: "Nature" },
  { id: "nat-fleur-cactus", civilWord: "Fleur", undercoverWord: "Cactus", difficulty: "easy", category: "Nature" },
  { id: "nat-foudre-tonnerre", civilWord: "Éclair", undercoverWord: "Tonnerre", difficulty: "hard", category: "Nature" },
  { id: "nat-riviere-fleuve", civilWord: "Rivière", undercoverWord: "Fleuve", difficulty: "hard", category: "Nature" },
  { id: "nat-etoile-comete", civilWord: "Étoile", undercoverWord: "Comète", difficulty: "normal", category: "Nature" },
  { id: "nat-arbre-buisson", civilWord: "Arbre", undercoverWord: "Buisson", difficulty: "easy", category: "Nature" },
  { id: "nat-tornade-cyclone", civilWord: "Tornade", undercoverWord: "Cyclone", difficulty: "hard", category: "Nature" },
  { id: "nat-glacier-iceberg", civilWord: "Glacier", undercoverWord: "Iceberg", difficulty: "normal", category: "Nature" },
  { id: "nat-desert-oasis", civilWord: "Désert", undercoverWord: "Oasis", difficulty: "normal", category: "Nature" },
  { id: "nat-corail-algue", civilWord: "Corail", undercoverWord: "Algue", difficulty: "normal", category: "Nature" },
  { id: "nat-champignon-mousse", civilWord: "Champignon", undercoverWord: "Mousse", difficulty: "hard", category: "Nature" },

  // ─── Technologie (10) ───
  { id: "tech-ordi-laptop", civilWord: "Ordinateur", undercoverWord: "Laptop", difficulty: "hard", category: "Technologie" },
  { id: "tech-robot-ia", civilWord: "Robot", undercoverWord: "Intelligence artificielle", difficulty: "hard", category: "Technologie" },
  { id: "tech-casquevr-lunettes3d", civilWord: "Casque VR", undercoverWord: "Lunettes 3D", difficulty: "normal", category: "Technologie" },
  { id: "tech-manette-joystick", civilWord: "Manette", undercoverWord: "Joystick", difficulty: "normal", category: "Technologie" },
  { id: "tech-clavier-piano", civilWord: "Clavier", undercoverWord: "Piano", difficulty: "normal", category: "Technologie" },
  { id: "tech-wifi-bluetooth", civilWord: "WiFi", undercoverWord: "Bluetooth", difficulty: "hard", category: "Technologie" },
  { id: "tech-usb-prise", civilWord: "Clé USB", undercoverWord: "Prise électrique", difficulty: "normal", category: "Technologie" },
  { id: "tech-camera-webcam", civilWord: "Caméra", undercoverWord: "Webcam", difficulty: "normal", category: "Technologie" },
  { id: "tech-enceinte-micro", civilWord: "Enceinte", undercoverWord: "Microphone", difficulty: "normal", category: "Technologie" },
  { id: "tech-imprimante-scanner", civilWord: "Imprimante", undercoverWord: "Scanner", difficulty: "normal", category: "Technologie" },
  { id: "tech-qrcode-codebarres", civilWord: "QR code", undercoverWord: "Code-barres", difficulty: "normal", category: "Technologie" },
  { id: "tech-smartwatch-montre", civilWord: "Smartwatch", undercoverWord: "Montre connectée", difficulty: "hard", category: "Technologie" },
  { id: "tech-gps-boussole", civilWord: "GPS", undercoverWord: "Boussole", difficulty: "normal", category: "Technologie" },
  { id: "tech-ecran-projecteur", civilWord: "Écran", undercoverWord: "Projecteur", difficulty: "normal", category: "Technologie" },

  // ─── Musique & Instruments (10) ───
  { id: "music-piano-orgue", civilWord: "Piano", undercoverWord: "Orgue", difficulty: "normal", category: "Musique" },
  { id: "music-batterie-tam-tam", civilWord: "Batterie", undercoverWord: "Tam-tam", difficulty: "normal", category: "Musique" },
  { id: "music-trompette-saxophone", civilWord: "Trompette", undercoverWord: "Saxophone", difficulty: "normal", category: "Musique" },
  { id: "music-flute-clarinette", civilWord: "Flûte", undercoverWord: "Clarinette", difficulty: "hard", category: "Musique" },
  { id: "music-harpe-lyre", civilWord: "Harpe", undercoverWord: "Lyre", difficulty: "hard", category: "Musique" },
  { id: "music-accordeon-harmonica", civilWord: "Accordéon", undercoverWord: "Harmonica", difficulty: "normal", category: "Musique" },
  { id: "music-dj-chef-orchestre", civilWord: "DJ", undercoverWord: "Chef d'orchestre", difficulty: "normal", category: "Musique" },
  { id: "music-rap-slam", civilWord: "Rap", undercoverWord: "Slam", difficulty: "hard", category: "Musique" },
  { id: "music-concert-festival", civilWord: "Concert", undercoverWord: "Festival", difficulty: "normal", category: "Musique" },
  { id: "music-karaoke-chorale", civilWord: "Karaoké", undercoverWord: "Chorale", difficulty: "normal", category: "Musique" },
  { id: "music-guitare-ukulele", civilWord: "Guitare", undercoverWord: "Ukulélé", difficulty: "normal", category: "Musique" },
  { id: "music-violon-violoncelle", civilWord: "Violon", undercoverWord: "Violoncelle", difficulty: "hard", category: "Musique" },
  { id: "music-xylophone-marimba", civilWord: "Xylophone", undercoverWord: "Marimba", difficulty: "hard", category: "Musique" },
  { id: "music-tambour-djembe", civilWord: "Tambour", undercoverWord: "Djembé", difficulty: "normal", category: "Musique" },
  { id: "music-banjo-mandoline", civilWord: "Banjo", undercoverWord: "Mandoline", difficulty: "hard", category: "Musique" },

  // ─── Pop Culture & Jeux vidéo (20) ───
  { id: "pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-batman-zorro", civilWord: "Batman", undercoverWord: "Zorro", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-pikachu-raichu", civilWord: "Pikachu", undercoverWord: "Raichu", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-tiktok-instagram", civilWord: "TikTok", undercoverWord: "Instagram", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-fortnite-pubg", civilWord: "Fortnite", undercoverWord: "PUBG", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-naruto-goku", civilWord: "Naruto", undercoverWord: "Goku", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-shrek-hulk", civilWord: "Shrek", undercoverWord: "Hulk", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-spongebob-patrick", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-thanos-villain", civilWord: "Thanos", undercoverWord: "Dark Vador", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-spiderman-superman", civilWord: "Spider-Man", undercoverWord: "Superman", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-elsa-cendrillon", civilWord: "Elsa", undercoverWord: "Cendrillon", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-harry-gandalf", civilWord: "Harry Potter", undercoverWord: "Gandalf", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-gta-cyberpunk", civilWord: "GTA", undercoverWord: "Cyberpunk", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-among-us-loup-garou", civilWord: "Among Us", undercoverWord: "Loup-Garou", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-mickey-bugs-bunny", civilWord: "Mickey", undercoverWord: "Bugs Bunny", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-totoro-pikachu2", civilWord: "Totoro", undercoverWord: "Snorlax", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-ironman-optimus", civilWord: "Iron Man", undercoverWord: "Optimus Prime", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-yoda-dumbledore", civilWord: "Yoda", undercoverWord: "Dumbledore", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-stitch-babyyoda", civilWord: "Stitch", undercoverWord: "Baby Yoda", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-deadpool-wolverine", civilWord: "Deadpool", undercoverWord: "Wolverine", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-avengers-justiceleague", civilWord: "Avengers", undercoverWord: "Justice League", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-groot-baymax", civilWord: "Groot", undercoverWord: "Baymax", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-neo-morpheus", civilWord: "Neo", undercoverWord: "Morpheus", difficulty: "hard", category: "Pop Culture" },

  // ─── Maison & Meubles (10) ───
  { id: "home-lit-canape", civilWord: "Lit", undercoverWord: "Canapé", difficulty: "easy", category: "Maison" },
  { id: "home-douche-baignoire", civilWord: "Douche", undercoverWord: "Baignoire", difficulty: "normal", category: "Maison" },
  { id: "home-fenetre-porte", civilWord: "Fenêtre", undercoverWord: "Porte", difficulty: "easy", category: "Maison" },
  { id: "home-four-micro-ondes", civilWord: "Four", undercoverWord: "Micro-ondes", difficulty: "normal", category: "Maison" },
  { id: "home-frigo-congelateur", civilWord: "Frigo", undercoverWord: "Congélateur", difficulty: "hard", category: "Maison" },
  { id: "home-escalier-ascenseur", civilWord: "Escalier", undercoverWord: "Ascenseur", difficulty: "normal", category: "Maison" },
  { id: "home-tele-projecteur", civilWord: "Télévision", undercoverWord: "Projecteur", difficulty: "normal", category: "Maison" },
  { id: "home-tapis-moquette", civilWord: "Tapis", undercoverWord: "Moquette", difficulty: "hard", category: "Maison" },
  { id: "home-rideau-store", civilWord: "Rideau", undercoverWord: "Store", difficulty: "hard", category: "Maison" },
  { id: "home-evier-lavabo", civilWord: "Évier", undercoverWord: "Lavabo", difficulty: "hard", category: "Maison" },
  { id: "home-cheminee-radiateur", civilWord: "Cheminée", undercoverWord: "Radiateur", difficulty: "normal", category: "Maison" },
  { id: "home-aquarium-terrarium", civilWord: "Aquarium", undercoverWord: "Terrarium", difficulty: "hard", category: "Maison" },
  { id: "home-ventilateur-climatiseur", civilWord: "Ventilateur", undercoverWord: "Climatiseur", difficulty: "normal", category: "Maison" },
  { id: "home-poubelle-compost", civilWord: "Poubelle", undercoverWord: "Compost", difficulty: "normal", category: "Maison" },

  // ─── École & Savoir (10) ───
  { id: "school-crayon-stylo", civilWord: "Crayon", undercoverWord: "Stylo", difficulty: "easy", category: "École" },
  { id: "school-cahier-classeur", civilWord: "Cahier", undercoverWord: "Classeur", difficulty: "normal", category: "École" },
  { id: "school-tableau-ecran", civilWord: "Tableau", undercoverWord: "Écran", difficulty: "normal", category: "École" },
  { id: "school-gomme-correcteur", civilWord: "Gomme", undercoverWord: "Correcteur", difficulty: "normal", category: "École" },
  { id: "school-regle-equerre", civilWord: "Règle", undercoverWord: "Équerre", difficulty: "hard", category: "École" },
  { id: "school-globe-carte", civilWord: "Globe", undercoverWord: "Carte", difficulty: "normal", category: "École" },
  { id: "school-sac-trousse", civilWord: "Sac d'école", undercoverWord: "Trousse", difficulty: "normal", category: "École" },
  { id: "school-calcul-geometrie", civilWord: "Calcul", undercoverWord: "Géométrie", difficulty: "hard", category: "École" },
  { id: "school-examen-controle", civilWord: "Examen", undercoverWord: "Contrôle", difficulty: "hard", category: "École" },
  { id: "school-recreation-sieste", civilWord: "Récréation", undercoverWord: "Sieste", difficulty: "normal", category: "École" },
  { id: "school-dictionnaire-encyclopedie", civilWord: "Dictionnaire", undercoverWord: "Encyclopédie", difficulty: "hard", category: "École" },
  { id: "school-compas-rapporteur", civilWord: "Compas", undercoverWord: "Rapporteur", difficulty: "hard", category: "École" },
  { id: "school-colle-scotch", civilWord: "Colle", undercoverWord: "Scotch", difficulty: "easy", category: "École" },
  { id: "school-labo-salleclasse", civilWord: "Laboratoire", undercoverWord: "Salle de classe", difficulty: "normal", category: "École" },

  // ─── Fêtes & Événements (10) ───
  { id: "fete-noel-halloween", civilWord: "Noël", undercoverWord: "Halloween", difficulty: "easy", category: "Fêtes" },
  { id: "fete-anniversaire-mariage", civilWord: "Anniversaire", undercoverWord: "Mariage", difficulty: "normal", category: "Fêtes" },
  { id: "fete-carnaval-deguisement", civilWord: "Carnaval", undercoverWord: "Déguisement", difficulty: "normal", category: "Fêtes" },
  { id: "fete-feu-artifice-petard", civilWord: "Feu d'artifice", undercoverWord: "Pétard", difficulty: "normal", category: "Fêtes" },
  { id: "fete-cadeau-surprise", civilWord: "Cadeau", undercoverWord: "Surprise", difficulty: "normal", category: "Fêtes" },
  { id: "fete-pere-noel-lutin", civilWord: "Père Noël", undercoverWord: "Lutin", difficulty: "normal", category: "Fêtes" },
  { id: "fete-fantome-sorciere", civilWord: "Fantôme", undercoverWord: "Sorcière", difficulty: "easy", category: "Fêtes" },
  { id: "fete-oeuf-paques-lapin", civilWord: "Oeuf de Pâques", undercoverWord: "Lapin de Pâques", difficulty: "hard", category: "Fêtes" },
  { id: "fete-sapin-guirlande", civilWord: "Sapin", undercoverWord: "Guirlande", difficulty: "normal", category: "Fêtes" },
  { id: "fete-gateau-bougie-anniv", civilWord: "Gâteau d'anniversaire", undercoverWord: "Bougie d'anniversaire", difficulty: "hard", category: "Fêtes" },
  { id: "fete-confetti-serpentin", civilWord: "Confetti", undercoverWord: "Serpentin", difficulty: "normal", category: "Fêtes" },
  { id: "fete-bonhomme-igloo", civilWord: "Bonhomme de neige", undercoverWord: "Igloo", difficulty: "easy", category: "Fêtes" },
  { id: "fete-citrouille-lanterne", civilWord: "Citrouille", undercoverWord: "Lanterne", difficulty: "normal", category: "Fêtes" },
  { id: "fete-couronne-galette", civilWord: "Couronne", undercoverWord: "Galette des rois", difficulty: "normal", category: "Fêtes" },

  // ─── Corps humain (10) ───
  { id: "body-oeil-oreille", civilWord: "Oeil", undercoverWord: "Oreille", difficulty: "easy", category: "Corps" },
  { id: "body-main-pied", civilWord: "Main", undercoverWord: "Pied", difficulty: "easy", category: "Corps" },
  { id: "body-cerveau-coeur", civilWord: "Cerveau", undercoverWord: "Coeur", difficulty: "normal", category: "Corps" },
  { id: "body-dent-os", civilWord: "Dent", undercoverWord: "Os", difficulty: "normal", category: "Corps" },
  { id: "body-muscle-tendon", civilWord: "Muscle", undercoverWord: "Tendon", difficulty: "hard", category: "Corps" },
  { id: "body-cheveux-barbe", civilWord: "Cheveux", undercoverWord: "Barbe", difficulty: "normal", category: "Corps" },
  { id: "body-doigt-orteil", civilWord: "Doigt", undercoverWord: "Orteil", difficulty: "normal", category: "Corps" },
  { id: "body-nez-bouche", civilWord: "Nez", undercoverWord: "Bouche", difficulty: "easy", category: "Corps" },
  { id: "body-crane-squelette", civilWord: "Crâne", undercoverWord: "Squelette", difficulty: "normal", category: "Corps" },
  { id: "body-poumon-estomac", civilWord: "Poumon", undercoverWord: "Estomac", difficulty: "hard", category: "Corps" },
  { id: "body-genou-coude", civilWord: "Genou", undercoverWord: "Coude", difficulty: "normal", category: "Corps" },
  { id: "body-langue-levre", civilWord: "Langue", undercoverWord: "Lèvre", difficulty: "normal", category: "Corps" },
  { id: "body-sourcil-cil", civilWord: "Sourcil", undercoverWord: "Cil", difficulty: "hard", category: "Corps" },
  { id: "body-pouce-index", civilWord: "Pouce", undercoverWord: "Index", difficulty: "hard", category: "Corps" },

  // ─── Émotions & Expressions (10) ───
  { id: "emo-rire-pleurer", civilWord: "Rire", undercoverWord: "Pleurer", difficulty: "easy", category: "Émotions" },
  { id: "emo-colere-frustration", civilWord: "Colère", undercoverWord: "Frustration", difficulty: "hard", category: "Émotions" },
  { id: "emo-peur-angoisse", civilWord: "Peur", undercoverWord: "Angoisse", difficulty: "hard", category: "Émotions" },
  { id: "emo-joie-bonheur", civilWord: "Joie", undercoverWord: "Bonheur", difficulty: "hard", category: "Émotions" },
  { id: "emo-dormir-ronfler", civilWord: "Dormir", undercoverWord: "Ronfler", difficulty: "normal", category: "Émotions" },
  { id: "emo-crier-chuchoter", civilWord: "Crier", undercoverWord: "Chuchoter", difficulty: "normal", category: "Émotions" },
  { id: "emo-bisou-calin", civilWord: "Bisou", undercoverWord: "Câlin", difficulty: "normal", category: "Émotions" },
  { id: "emo-timide-confiant", civilWord: "Timide", undercoverWord: "Confiant", difficulty: "hard", category: "Émotions" },
  { id: "emo-ennui-paresse", civilWord: "Ennui", undercoverWord: "Paresse", difficulty: "hard", category: "Émotions" },
  { id: "emo-surprise-choc", civilWord: "Surprise", undercoverWord: "Choc", difficulty: "hard", category: "Émotions" },
  { id: "emo-jalousie-envie", civilWord: "Jalousie", undercoverWord: "Envie", difficulty: "hard", category: "Émotions" },
  { id: "emo-courage-temerite", civilWord: "Courage", undercoverWord: "Témérité", difficulty: "hard", category: "Émotions" },
  { id: "emo-amour-passion", civilWord: "Amour", undercoverWord: "Passion", difficulty: "hard", category: "Émotions" },

  // ─── Chaos / Concepts abstraits (15) ───
  { id: "abs-amour-amitie", civilWord: "Amour", undercoverWord: "Amitié", difficulty: "hard", category: "Chaos" },
  { id: "abs-lundi-vendredi", civilWord: "Lundi", undercoverWord: "Vendredi", difficulty: "normal", category: "Chaos" },
  { id: "abs-bruit-silence", civilWord: "Bruit", undercoverWord: "Silence", difficulty: "hard", category: "Chaos" },
  { id: "abs-reve-cauchemar", civilWord: "Rêve", undercoverWord: "Cauchemar", difficulty: "normal", category: "Chaos" },
  { id: "abs-chaud-froid", civilWord: "Chaud", undercoverWord: "Froid", difficulty: "easy", category: "Chaos" },
  { id: "abs-hier-demain", civilWord: "Hier", undercoverWord: "Demain", difficulty: "hard", category: "Chaos" },
  { id: "abs-chance-malchance", civilWord: "Chance", undercoverWord: "Malchance", difficulty: "hard", category: "Chaos" },
  { id: "abs-vie-mort", civilWord: "Vie", undercoverWord: "Mort", difficulty: "normal", category: "Chaos" },
  { id: "abs-riche-pauvre", civilWord: "Riche", undercoverWord: "Pauvre", difficulty: "normal", category: "Chaos" },
  { id: "abs-ete-hiver", civilWord: "Été", undercoverWord: "Hiver", difficulty: "easy", category: "Chaos" },
  { id: "abs-guerre-paix", civilWord: "Guerre", undercoverWord: "Paix", difficulty: "normal", category: "Chaos" },
  { id: "abs-rapide-lent", civilWord: "Rapide", undercoverWord: "Lent", difficulty: "easy", category: "Chaos" },
  { id: "abs-lumiere-ombre", civilWord: "Lumière", undercoverWord: "Ombre", difficulty: "normal", category: "Chaos" },
  { id: "abs-genie-idiot", civilWord: "Génie", undercoverWord: "Idiot", difficulty: "normal", category: "Chaos" },
  { id: "abs-gravite-apesanteur", civilWord: "Gravité", undercoverWord: "Apesanteur", difficulty: "hard", category: "Chaos" },
  { id: "abs-infini-zero", civilWord: "Infini", undercoverWord: "Zéro", difficulty: "hard", category: "Chaos" },
  { id: "abs-paradis-enfer", civilWord: "Paradis", undercoverWord: "Enfer", difficulty: "normal", category: "Chaos" },
  { id: "abs-debut-fin", civilWord: "Début", undercoverWord: "Fin", difficulty: "easy", category: "Chaos" },
  { id: "abs-nord-sud", civilWord: "Nord", undercoverWord: "Sud", difficulty: "easy", category: "Chaos" },
  { id: "abs-vrai-faux", civilWord: "Vrai", undercoverWord: "Faux", difficulty: "hard", category: "Chaos" },

  // ─── Espace & Science-fiction (10) ───
  { id: "space-terre-mars", civilWord: "Terre", undercoverWord: "Mars", difficulty: "normal", category: "Espace" },
  { id: "space-alien-fantome2", civilWord: "Alien", undercoverWord: "Fantôme", difficulty: "normal", category: "Espace" },
  { id: "space-meteorite-asteroide", civilWord: "Météorite", undercoverWord: "Astéroïde", difficulty: "hard", category: "Espace" },
  { id: "space-telescope-microscope", civilWord: "Télescope", undercoverWord: "Microscope", difficulty: "normal", category: "Espace" },
  { id: "space-ovni-satellite", civilWord: "OVNI", undercoverWord: "Satellite", difficulty: "normal", category: "Espace" },
  { id: "space-galaxie-nebuleuse", civilWord: "Galaxie", undercoverWord: "Nébuleuse", difficulty: "hard", category: "Espace" },
  { id: "space-astronaute2-cosmonaute", civilWord: "Astronaute", undercoverWord: "Cosmonaute", difficulty: "hard", category: "Espace" },
  { id: "space-blackhole-tornado", civilWord: "Trou noir", undercoverWord: "Tornade", difficulty: "normal", category: "Espace" },
  { id: "space-sabre-laser-epee", civilWord: "Sabre laser", undercoverWord: "Épée magique", difficulty: "normal", category: "Espace" },
  { id: "space-vaisseau-fusee", civilWord: "Vaisseau spatial", undercoverWord: "Fusée", difficulty: "normal", category: "Espace" },
  { id: "space-station-iss", civilWord: "Station spatiale", undercoverWord: "Satellite", difficulty: "normal", category: "Espace" },
  { id: "space-lune-saturne", civilWord: "Lune", undercoverWord: "Saturne", difficulty: "normal", category: "Espace" },
  { id: "space-rover-robot2", civilWord: "Rover", undercoverWord: "Robot", difficulty: "normal", category: "Espace" },
  { id: "space-comete-etoilefilante", civilWord: "Comète", undercoverWord: "Étoile filante", difficulty: "hard", category: "Espace" },

  // ─── Contes & Légendes (10) ───
  { id: "tale-dragon-dinosaure", civilWord: "Dragon", undercoverWord: "Dinosaure", difficulty: "easy", category: "Contes" },
  { id: "tale-licorne-pegase", civilWord: "Licorne", undercoverWord: "Pégase", difficulty: "normal", category: "Contes" },
  { id: "tale-sirene-triton", civilWord: "Sirène", undercoverWord: "Triton", difficulty: "normal", category: "Contes" },
  { id: "tale-fee-ange", civilWord: "Fée", undercoverWord: "Ange", difficulty: "normal", category: "Contes" },
  { id: "tale-vampire-zombie", civilWord: "Vampire", undercoverWord: "Zombie", difficulty: "easy", category: "Contes" },
  { id: "tale-ogre-troll", civilWord: "Ogre", undercoverWord: "Troll", difficulty: "normal", category: "Contes" },
  { id: "tale-prince-roi", civilWord: "Prince", undercoverWord: "Roi", difficulty: "normal", category: "Contes" },
  { id: "tale-tresor-coffre", civilWord: "Trésor", undercoverWord: "Coffre", difficulty: "normal", category: "Contes" },
  { id: "tale-chateau-tour", civilWord: "Château fort", undercoverWord: "Tour de garde", difficulty: "hard", category: "Contes" },
  { id: "tale-baguette-magique-baton", civilWord: "Baguette magique", undercoverWord: "Bâton de sorcier", difficulty: "hard", category: "Contes" },
  { id: "tale-minotaure-centaure", civilWord: "Minotaure", undercoverWord: "Centaure", difficulty: "normal", category: "Contes" },
  { id: "tale-phoenix-griffon", civilWord: "Phénix", undercoverWord: "Griffon", difficulty: "hard", category: "Contes" },
  { id: "tale-lutin-farfadet", civilWord: "Lutin", undercoverWord: "Farfadet", difficulty: "hard", category: "Contes" },
  { id: "tale-gobelin-nain", civilWord: "Gobelin", undercoverWord: "Nain", difficulty: "normal", category: "Contes" },
  { id: "tale-sorciere-magicien", civilWord: "Sorcière", undercoverWord: "Magicien", difficulty: "easy", category: "Contes" },

  // ─── Manga / Anime (18) ───
  { id: "anime-naruto-luffy", civilWord: "Naruto", undercoverWord: "Luffy", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-goku-vegeta", civilWord: "Goku", undercoverWord: "Vegeta", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-sasuke-itachi", civilWord: "Sasuke", undercoverWord: "Itachi", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-totoro-noiraude", civilWord: "Totoro", undercoverWord: "Noiraude", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-pikachu-evoli", civilWord: "Pikachu", undercoverWord: "Évoli", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-sailor-moon-cardcaptor", civilWord: "Sailor Moon", undercoverWord: "Cardcaptor Sakura", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-onepiece-bateau", civilWord: "One Piece", undercoverWord: "Bateau pirate", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-spirited-away-howl", civilWord: "Chihiro", undercoverWord: "Howl", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-akatsuki-anbu", civilWord: "Akatsuki", undercoverWord: "ANBU", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-shinigami-hollow", civilWord: "Shinigami", undercoverWord: "Hollow", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-titan-colossal", civilWord: "Titan", undercoverWord: "Titan colossal", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-deku-bakugo", civilWord: "Deku", undercoverWord: "Bakugo", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-gojo-sukuna", civilWord: "Gojo", undercoverWord: "Sukuna", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-tanjiro-zenitsu", civilWord: "Tanjiro", undercoverWord: "Zenitsu", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-nezuko-shinobu", civilWord: "Nezuko", undercoverWord: "Shinobu", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-pokemon-pokeball", civilWord: "Pokémon", undercoverWord: "Poké Ball", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-mecha-gundam", civilWord: "Mecha", undercoverWord: "Gundam", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-ramen-bento", civilWord: "Ramen", undercoverWord: "Bento", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-zoro-sanji", civilWord: "Zoro", undercoverWord: "Sanji", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-kakashi-jiraiya", civilWord: "Kakashi", undercoverWord: "Jiraiya", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-light-l", civilWord: "Light Yagami", undercoverWord: "L", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-eren-mikasa", civilWord: "Eren", undercoverWord: "Mikasa", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-saitama-genos", civilWord: "Saitama", undercoverWord: "Genos", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-killua-gon", civilWord: "Killua", undercoverWord: "Gon", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-asta-yuno", civilWord: "Asta", undercoverWord: "Yuno", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-lelouch-suzaku", civilWord: "Lelouch", undercoverWord: "Suzaku", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-senku-chrome", civilWord: "Senku", undercoverWord: "Chrome", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-goku-freezer", civilWord: "Goku", undercoverWord: "Freezer", difficulty: "easy", category: "Manga / Anime" },

  // ─── Jeux vidéo (18) ───
  { id: "game-mario-luigi", civilWord: "Mario", undercoverWord: "Luigi", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-creeper-zombie", civilWord: "Creeper", undercoverWord: "Zombie", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-fortnite-apex", civilWord: "Fortnite", undercoverWord: "Apex Legends", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-pacman-ghost", civilWord: "Pac-Man", undercoverWord: "Fantôme", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-sonic-shadow", civilWord: "Sonic", undercoverWord: "Shadow", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-masterchief-doomguy", civilWord: "Master Chief", undercoverWord: "Doom Slayer", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-tetris-puyo", civilWord: "Tetris", undercoverWord: "Puyo Puyo", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-roblox-minecraft", civilWord: "Roblox", undercoverWord: "Minecraft", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-pokeball-masterball", civilWord: "Poké Ball", undercoverWord: "Master Ball", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-kirby-yoshi", civilWord: "Kirby", undercoverWord: "Yoshi", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-bowser-wario", civilWord: "Bowser", undercoverWord: "Wario", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-kratos-thor", civilWord: "Kratos", undercoverWord: "Thor", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-overcooked-plateup", civilWord: "Overcooked", undercoverWord: "PlateUp!", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-amongus-impostor", civilWord: "Among Us", undercoverWord: "Imposteur", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-potion-elixir", civilWord: "Potion", undercoverWord: "Élixir", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-joystick-console", civilWord: "Joystick", undercoverWord: "Console", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-speedrun-checkpoint", civilWord: "Speedrun", undercoverWord: "Checkpoint", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-steve-alex", civilWord: "Steve", undercoverWord: "Alex", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-pikachu-mewtwo", civilWord: "Pikachu", undercoverWord: "Mewtwo", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-lara-nathan", civilWord: "Lara Croft", undercoverWord: "Nathan Drake", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-megaman-astroboy", civilWord: "Mega Man", undercoverWord: "Astro Boy", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-ganondorf-bowser2", civilWord: "Ganondorf", undercoverWord: "Bowser", difficulty: "normal", category: "Jeux vidéo" },

  // ─── Cinéma / Séries (18) ───
  { id: "screen-harry-hermione", civilWord: "Harry Potter", undercoverWord: "Hermione", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-batman-joker", civilWord: "Batman", undercoverWord: "Joker", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-vador-yoda", civilWord: "Dark Vador", undercoverWord: "Yoda", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-spiderman-venom", civilWord: "Spider-Man", undercoverWord: "Venom", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-sherlock-watson", civilWord: "Sherlock", undercoverWord: "Watson", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-hobbit-elf", civilWord: "Hobbit", undercoverWord: "Elfe", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-minion-groot", civilWord: "Minion", undercoverWord: "Groot", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-thor-loki", civilWord: "Thor", undercoverWord: "Loki", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-elsa-anna", civilWord: "Elsa", undercoverWord: "Anna", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-simba-mufasa", civilWord: "Simba", undercoverWord: "Mufasa", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-r2d2-c3po", civilWord: "R2-D2", undercoverWord: "C-3PO", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-wednesday-enid", civilWord: "Wednesday", undercoverWord: "Enid", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-stranger-demogorgon", civilWord: "Stranger Things", undercoverWord: "Demogorgon", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-marvel-avengers", civilWord: "Marvel", undercoverWord: "Avengers", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-kungfu-panda-shifu", civilWord: "Po", undercoverWord: "Shifu", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-spongebob-patrick-series", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-rick-morty", civilWord: "Rick", undercoverWord: "Morty", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-gandalf-saruman", civilWord: "Gandalf", undercoverWord: "Saroumane", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-bond-bourne", civilWord: "James Bond", undercoverWord: "Jason Bourne", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-shrek-fiona", civilWord: "Shrek", undercoverWord: "Fiona", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-hagrid-dobby", civilWord: "Hagrid", undercoverWord: "Dobby", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-jackpearl-barbossa", civilWord: "Jack Sparrow", undercoverWord: "Barbossa", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-eleven-dustin", civilWord: "Eleven", undercoverWord: "Dustin", difficulty: "normal", category: "Cinéma / Séries" },

  // ─── Fruits & Legumes (18) ───
  { id: "fruit-pomme-poire", civilWord: "Pomme", undercoverWord: "Poire", difficulty: "easy", category: "Fruits & Légumes" },
  { id: "fruit-banane-plantain", civilWord: "Banane", undercoverWord: "Banane plantain", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "fruit-fraise-framboise", civilWord: "Fraise", undercoverWord: "Framboise", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "fruit-raisin-myrtille", civilWord: "Raisin", undercoverWord: "Myrtille", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "fruit-pasteque-melon", civilWord: "Pastèque", undercoverWord: "Melon", difficulty: "easy", category: "Fruits & Légumes" },
  { id: "fruit-orange-clémentine", civilWord: "Orange", undercoverWord: "Clémentine", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "fruit-citron-lime", civilWord: "Citron", undercoverWord: "Citron vert", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "fruit-ananas-mangue", civilWord: "Ananas", undercoverWord: "Mangue", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "fruit-kiwi-avocat", civilWord: "Kiwi", undercoverWord: "Avocat", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "fruit-cerise-prune", civilWord: "Cerise", undercoverWord: "Prune", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-carotte-navet", civilWord: "Carotte", undercoverWord: "Navet", difficulty: "easy", category: "Fruits & Légumes" },
  { id: "veg-tomate-poivron", civilWord: "Tomate", undercoverWord: "Poivron", difficulty: "easy", category: "Fruits & Légumes" },
  { id: "veg-concombre-courgette", civilWord: "Concombre", undercoverWord: "Courgette", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-oignon-ail", civilWord: "Oignon", undercoverWord: "Ail", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-salade-chou", civilWord: "Salade", undercoverWord: "Chou", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-brocoli-choufleur", civilWord: "Brocoli", undercoverWord: "Chou-fleur", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-patate-douce", civilWord: "Pomme de terre", undercoverWord: "Patate douce", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "veg-champignon-truffe", civilWord: "Champignon", undercoverWord: "Truffe", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "fruit-abricot-peche", civilWord: "Abricot", undercoverWord: "Pêche", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "fruit-litchi-grenade", civilWord: "Litchi", undercoverWord: "Grenade", difficulty: "hard", category: "Fruits & Légumes" },
  { id: "veg-poireau-asperge", civilWord: "Poireau", undercoverWord: "Asperge", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-betterave-radis", civilWord: "Betterave", undercoverWord: "Radis", difficulty: "normal", category: "Fruits & Légumes" },
  { id: "veg-haricot-petitpois", civilWord: "Haricot", undercoverWord: "Petit pois", difficulty: "normal", category: "Fruits & Légumes" },

  // ─── Cuisine (18) ───
  { id: "cook-poele-casserole", civilWord: "Poêle", undercoverWord: "Casserole", difficulty: "easy", category: "Cuisine" },
  { id: "cook-four-grillepain", civilWord: "Four", undercoverWord: "Grille-pain", difficulty: "easy", category: "Cuisine" },
  { id: "cook-fouet-spatule", civilWord: "Fouet", undercoverWord: "Spatule", difficulty: "normal", category: "Cuisine" },
  { id: "cook-couteau-econome", civilWord: "Couteau", undercoverWord: "Économe", difficulty: "normal", category: "Cuisine" },
  { id: "cook-frigo-placard", civilWord: "Frigo", undercoverWord: "Placard", difficulty: "normal", category: "Cuisine" },
  { id: "cook-assiette-bol", civilWord: "Assiette", undercoverWord: "Bol", difficulty: "easy", category: "Cuisine" },
  { id: "cook-verre-tasse", civilWord: "Verre", undercoverWord: "Tasse", difficulty: "easy", category: "Cuisine" },
  { id: "cook-fourchette-cuillere", civilWord: "Fourchette", undercoverWord: "Cuillère", difficulty: "easy", category: "Cuisine" },
  { id: "cook-sel-poivre", civilWord: "Sel", undercoverWord: "Poivre", difficulty: "easy", category: "Cuisine" },
  { id: "cook-ketchup-mayo", civilWord: "Ketchup", undercoverWord: "Mayonnaise", difficulty: "normal", category: "Cuisine" },
  { id: "cook-omelette-crepe", civilWord: "Omelette", undercoverWord: "Crêpe", difficulty: "normal", category: "Cuisine" },
  { id: "cook-soupe-puree", civilWord: "Soupe", undercoverWord: "Purée", difficulty: "normal", category: "Cuisine" },
  { id: "cook-riz-pates", civilWord: "Riz", undercoverWord: "Pâtes", difficulty: "easy", category: "Cuisine" },
  { id: "cook-fromage-yaourt", civilWord: "Fromage", undercoverWord: "Yaourt", difficulty: "normal", category: "Cuisine" },
  { id: "cook-beurre-confiture", civilWord: "Beurre", undercoverWord: "Confiture", difficulty: "normal", category: "Cuisine" },
  { id: "cook-pain-brioche", civilWord: "Pain", undercoverWord: "Brioche", difficulty: "normal", category: "Cuisine" },
  { id: "cook-gateau-biscuit", civilWord: "Gâteau", undercoverWord: "Biscuit", difficulty: "easy", category: "Cuisine" },
  { id: "cook-pizza-lasagne", civilWord: "Pizza", undercoverWord: "Lasagnes", difficulty: "normal", category: "Cuisine" },
  { id: "cook-cocotte-marmite", civilWord: "Cocotte", undercoverWord: "Marmite", difficulty: "hard", category: "Cuisine" },
  { id: "cook-tablier-torchon", civilWord: "Tablier", undercoverWord: "Torchon", difficulty: "normal", category: "Cuisine" },
  { id: "cook-rouleau-moule", civilWord: "Rouleau à pâtisserie", undercoverWord: "Moule", difficulty: "normal", category: "Cuisine" },
  { id: "cook-passoire-tamis", civilWord: "Passoire", undercoverWord: "Tamis", difficulty: "hard", category: "Cuisine" },

  // ─── Objets du quotidien (18) ───
  { id: "daily-clef-badge", civilWord: "Clé", undercoverWord: "Badge", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-portefeuille-pochette", civilWord: "Portefeuille", undercoverWord: "Pochette", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-sac-valise", civilWord: "Sac", undercoverWord: "Valise", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-brosse-peigne", civilWord: "Brosse", undercoverWord: "Peigne", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-savon-shampoing", civilWord: "Savon", undercoverWord: "Shampoing", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-serviette-mouchoir", civilWord: "Serviette", undercoverWord: "Mouchoir", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-pile-batterie", civilWord: "Pile", undercoverWord: "Batterie", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-cable-chargeur", civilWord: "Câble", undercoverWord: "Chargeur", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-ampoule-bougie", civilWord: "Ampoule", undercoverWord: "Bougie", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-stylo-marqueur", civilWord: "Stylo", undercoverWord: "Marqueur", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-carnet-agenda", civilWord: "Carnet", undercoverWord: "Agenda", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-livre-journal", civilWord: "Livre", undercoverWord: "Journal", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-telecommande-manette", civilWord: "Télécommande", undercoverWord: "Manette", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-lampe-reveil", civilWord: "Lampe", undercoverWord: "Réveil", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-cadenas-serrure", civilWord: "Cadenas", undercoverWord: "Serrure", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-parapluie-kway", civilWord: "Parapluie", undercoverWord: "K-way", difficulty: "hard", category: "Objets du quotidien" },
  { id: "daily-lunettes-masque", civilWord: "Lunettes", undercoverWord: "Masque", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-bouteille-gourde", civilWord: "Bouteille", undercoverWord: "Gourde", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-coussin-couverture", civilWord: "Coussin", undercoverWord: "Couverture", difficulty: "easy", category: "Objets du quotidien" },
  { id: "daily-cintre-etendoir", civilWord: "Cintre", undercoverWord: "Étendoir", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-reveil-minuteur", civilWord: "Réveil", undercoverWord: "Minuteur", difficulty: "normal", category: "Objets du quotidien" },
  { id: "daily-ciseaux-scotch2", civilWord: "Ciseaux", undercoverWord: "Scotch", difficulty: "easy", category: "Objets du quotidien" },

  // ─── Ville & Commerce (18) ───
  { id: "city-boulangerie-patisserie", civilWord: "Boulangerie", undercoverWord: "Pâtisserie", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-supermarche-epicerie", civilWord: "Supermarché", undercoverWord: "Épicerie", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-pharmacie-hopital", civilWord: "Pharmacie", undercoverWord: "Hôpital", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-ecole-college", civilWord: "École", undercoverWord: "Collège", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-gare-station", civilWord: "Gare", undercoverWord: "Station de métro", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-restaurant-cafe", civilWord: "Restaurant", undercoverWord: "Café", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-banque-mairie", civilWord: "Banque", undercoverWord: "Mairie", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-cinema-theatre2", civilWord: "Cinéma", undercoverWord: "Théâtre", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-bibliotheque-librairie", civilWord: "Bibliothèque", undercoverWord: "Librairie", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-zoo-musee", civilWord: "Zoo", undercoverWord: "Musée", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-hotel-auberge", civilWord: "Hôtel", undercoverWord: "Auberge", difficulty: "hard", category: "Ville & Commerce" },
  { id: "city-plage-port", civilWord: "Plage", undercoverWord: "Port", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-parc-jardin", civilWord: "Parc", undercoverWord: "Jardin", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-piscine-patinoire", civilWord: "Piscine", undercoverWord: "Patinoire", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-stade-gymnase", civilWord: "Stade", undercoverWord: "Gymnase", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-camping-hotel", civilWord: "Camping", undercoverWord: "Hôtel", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-marche-brocante", civilWord: "Marché", undercoverWord: "Brocante", difficulty: "hard", category: "Ville & Commerce" },
  { id: "city-bus-tram", civilWord: "Bus", undercoverWord: "Tram", difficulty: "easy", category: "Ville & Commerce" },
  { id: "city-poste-boiteauxlettres", civilWord: "Poste", undercoverWord: "Boîte aux lettres", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-fontaine-statue", civilWord: "Fontaine", undercoverWord: "Statue", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-pont-tunnel2", civilWord: "Pont", undercoverWord: "Tunnel", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-aeroport-port", civilWord: "Aéroport", undercoverWord: "Port", difficulty: "normal", category: "Ville & Commerce" },
  { id: "city-gratteciel-tour", civilWord: "Gratte-ciel", undercoverWord: "Tour", difficulty: "easy", category: "Ville & Commerce" },

  // ─── Manga / Anime — suite (18) ───
  { id: "cartoon-mickey-minnie", civilWord: "Mickey", undercoverWord: "Minnie", difficulty: "easy", category: "Manga / Anime" },
  { id: "cartoon-tom-jerry", civilWord: "Tom", undercoverWord: "Jerry", difficulty: "easy", category: "Manga / Anime" },
  { id: "cartoon-spongebob-patrick2", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "easy", category: "Manga / Anime" },
  { id: "cartoon-bugs-daffy", civilWord: "Bugs Bunny", undercoverWord: "Daffy Duck", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-scooby-shaggy", civilWord: "Scooby-Doo", undercoverWord: "Sammy", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-finn-jake", civilWord: "Finn", undercoverWord: "Jake", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-gumball-darwin", civilWord: "Gumball", undercoverWord: "Darwin", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-simba-nala", civilWord: "Simba", undercoverWord: "Nala", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-elsa-olaf", civilWord: "Elsa", undercoverWord: "Olaf", difficulty: "easy", category: "Manga / Anime" },
  { id: "cartoon-buzz-woody", civilWord: "Buzz l'Éclair", undercoverWord: "Woody", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-po-shifu", civilWord: "Po", undercoverWord: "Shifu", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-shrek-ane", civilWord: "Shrek", undercoverWord: "Âne", difficulty: "easy", category: "Manga / Anime" },
  { id: "cartoon-peter-lois", civilWord: "Peter Griffin", undercoverWord: "Lois", difficulty: "hard", category: "Manga / Anime" },
  { id: "cartoon-rick-morty2", civilWord: "Rick", undercoverWord: "Morty", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-marinette-chatnoir", civilWord: "Marinette", undercoverWord: "Chat Noir", difficulty: "hard", category: "Manga / Anime" },
  { id: "cartoon-aladdin-genie", civilWord: "Aladdin", undercoverWord: "Génie", difficulty: "normal", category: "Manga / Anime" },
  { id: "cartoon-hercule-pegase", civilWord: "Hercule", undercoverWord: "Pégase", difficulty: "hard", category: "Manga / Anime" },
  { id: "cartoon-vaiana-maui", civilWord: "Vaiana", undercoverWord: "Maui", difficulty: "normal", category: "Manga / Anime" },

  // ─── Vacances & Loisirs (18) ───
  { id: "leisure-plage-piscine", civilWord: "Plage", undercoverWord: "Piscine", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-camping-randonnee", civilWord: "Camping", undercoverWord: "Randonnée", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-velo-rollers", civilWord: "Vélo", undercoverWord: "Rollers", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-photo-selfie", civilWord: "Photo", undercoverWord: "Selfie", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-pique-nique-barbecue", civilWord: "Pique-nique", undercoverWord: "Barbecue", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-karaoke-concert", civilWord: "Karaoké", undercoverWord: "Concert", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-cinema-popcorn", civilWord: "Cinéma", undercoverWord: "Popcorn", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-jeuxsociete-carte", civilWord: "Jeu de société", undercoverWord: "Jeu de cartes", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-puzzle-lego", civilWord: "Puzzle", undercoverWord: "Lego", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-bowling-billard", civilWord: "Bowling", undercoverWord: "Billard", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-ski-luge", civilWord: "Ski", undercoverWord: "Luge", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-peche-plongee", civilWord: "Pêche", undercoverWord: "Plongée", difficulty: "hard", category: "Vacances & Loisirs" },
  { id: "leisure-lecture-dessin", civilWord: "Lecture", undercoverWord: "Dessin", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-casque-ecouteurs", civilWord: "Casque audio", undercoverWord: "Écouteurs", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-valise-passeport", civilWord: "Valise", undercoverWord: "Passeport", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-hotel-camping2", civilWord: "Hôtel", undercoverWord: "Camping", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-soleil-cremesolaire", civilWord: "Soleil", undercoverWord: "Crème solaire", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-cerfvolant-drone", civilWord: "Cerf-volant", undercoverWord: "Drone", difficulty: "hard", category: "Vacances & Loisirs" },
  { id: "leisure-hamac-transat", civilWord: "Hamac", undercoverWord: "Transat", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-chateausable-seau", civilWord: "Château de sable", undercoverWord: "Seau", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-trampoline-toboggan2", civilWord: "Trampoline", undercoverWord: "Toboggan", difficulty: "easy", category: "Vacances & Loisirs" },
  { id: "leisure-feudecamp-barbecue2", civilWord: "Feu de camp", undercoverWord: "Barbecue", difficulty: "normal", category: "Vacances & Loisirs" },
  { id: "leisure-tuba-masqueplongee", civilWord: "Tuba", undercoverWord: "Masque de plongée", difficulty: "hard", category: "Vacances & Loisirs" }
];

export const WORD_CATEGORIES = [...new Set(BASE_WORD_PAIRS.map((pair) => pair.category))].sort(
  (left, right) => left.localeCompare(right, "fr")
);
