import type { WordPair } from "./protocol.js";

export const BASE_WORD_PAIRS: WordPair[] = [
  // ─── Nourriture (15) ───
  { id: "food-pizza-galette", civilWord: "Pizza", undercoverWord: "Galette", difficulty: "normal", category: "Nourriture" },
  { id: "food-sushi-onigiri", civilWord: "Sushi", undercoverWord: "Onigiri", difficulty: "hard", category: "Nourriture" },
  { id: "food-croissant-bretzel", civilWord: "Croissant", undercoverWord: "Bretzel", difficulty: "normal", category: "Nourriture" },
  { id: "food-hamburger-sandwich", civilWord: "Hamburger", undercoverWord: "Sandwich", difficulty: "easy", category: "Nourriture" },
  { id: "food-icecream-cupcake", civilWord: "Glace", undercoverWord: "Cupcake", difficulty: "normal", category: "Nourriture" },
  { id: "food-spaghetti-ramen", civilWord: "Spaghetti", undercoverWord: "Ramen", difficulty: "hard", category: "Nourriture" },
  { id: "food-baguette-baton", civilWord: "Baguette", undercoverWord: "Bâton de pain", difficulty: "hard", category: "Nourriture" },
  { id: "food-pancake-crepe", civilWord: "Pancake", undercoverWord: "Crêpe", difficulty: "hard", category: "Nourriture" },
  { id: "food-donut-bagel", civilWord: "Donut", undercoverWord: "Bagel", difficulty: "normal", category: "Nourriture" },
  { id: "food-popcorn-cereales", civilWord: "Popcorn", undercoverWord: "Céréales", difficulty: "normal", category: "Nourriture" },
  { id: "food-frites-potatoes", civilWord: "Frites", undercoverWord: "Potatoes", difficulty: "normal", category: "Nourriture" },
  { id: "food-tacos-burrito", civilWord: "Tacos", undercoverWord: "Burrito", difficulty: "hard", category: "Nourriture" },
  { id: "food-fromage-beurre", civilWord: "Fromage", undercoverWord: "Beurre", difficulty: "normal", category: "Nourriture" },
  { id: "food-gateau-tarte", civilWord: "Gâteau", undercoverWord: "Tarte", difficulty: "normal", category: "Nourriture" },
  { id: "food-bonbon-chocolat", civilWord: "Bonbon", undercoverWord: "Chocolat", difficulty: "easy", category: "Nourriture" },

  // ─── Boissons (10) ───
  { id: "drink-cafe-the", civilWord: "Café", undercoverWord: "Thé", difficulty: "easy", category: "Boissons" },
  { id: "drink-jus-smoothie", civilWord: "Jus d'orange", undercoverWord: "Smoothie", difficulty: "normal", category: "Boissons" },
  { id: "drink-coca-pepsi", civilWord: "Coca", undercoverWord: "Pepsi", difficulty: "hard", category: "Boissons" },
  { id: "drink-lait-yaourt", civilWord: "Lait", undercoverWord: "Yaourt", difficulty: "normal", category: "Boissons" },
  { id: "drink-eau-glacon", civilWord: "Eau", undercoverWord: "Glaçon", difficulty: "normal", category: "Boissons" },
  { id: "drink-chocolatchaud-capuccino", civilWord: "Chocolat chaud", undercoverWord: "Cappuccino", difficulty: "hard", category: "Boissons" },
  { id: "drink-limonade-orangina", civilWord: "Limonade", undercoverWord: "Orangina", difficulty: "normal", category: "Boissons" },
  { id: "drink-milkshake-frappuccino", civilWord: "Milkshake", undercoverWord: "Frappuccino", difficulty: "hard", category: "Boissons" },
  { id: "drink-sirop-miel", civilWord: "Sirop", undercoverWord: "Miel", difficulty: "normal", category: "Boissons" },
  { id: "drink-biere-cidre", civilWord: "Bière", undercoverWord: "Cidre", difficulty: "normal", category: "Boissons" },

  // ─── Animaux (15) ───
  { id: "animal-chat-tigre", civilWord: "Chat", undercoverWord: "Tigre", difficulty: "easy", category: "Animaux" },
  { id: "animal-chien-loup", civilWord: "Chien", undercoverWord: "Loup", difficulty: "normal", category: "Animaux" },
  { id: "animal-pingouin-canard", civilWord: "Pingouin", undercoverWord: "Canard", difficulty: "normal", category: "Animaux" },
  { id: "animal-tortue-escargot", civilWord: "Tortue", undercoverWord: "Escargot", difficulty: "normal", category: "Animaux" },
  { id: "animal-requin-dauphin", civilWord: "Requin", undercoverWord: "Dauphin", difficulty: "easy", category: "Animaux" },
  { id: "animal-abeille-guepe", civilWord: "Abeille", undercoverWord: "Guêpe", difficulty: "hard", category: "Animaux" },
  { id: "animal-crocodile-lezard", civilWord: "Crocodile", undercoverWord: "Lézard", difficulty: "normal", category: "Animaux" },
  { id: "animal-panda-ours", civilWord: "Panda", undercoverWord: "Ours", difficulty: "normal", category: "Animaux" },
  { id: "animal-papillon-libellule", civilWord: "Papillon", undercoverWord: "Libellule", difficulty: "normal", category: "Animaux" },
  { id: "animal-pieuvre-meduse", civilWord: "Pieuvre", undercoverWord: "Méduse", difficulty: "normal", category: "Animaux" },
  { id: "animal-aigle-faucon", civilWord: "Aigle", undercoverWord: "Faucon", difficulty: "hard", category: "Animaux" },
  { id: "animal-cheval-zebre", civilWord: "Cheval", undercoverWord: "Zèbre", difficulty: "easy", category: "Animaux" },
  { id: "animal-souris-hamster", civilWord: "Souris", undercoverWord: "Hamster", difficulty: "normal", category: "Animaux" },
  { id: "animal-lion-leopard", civilWord: "Lion", undercoverWord: "Léopard", difficulty: "hard", category: "Animaux" },
  { id: "animal-poule-dinde", civilWord: "Poule", undercoverWord: "Dinde", difficulty: "normal", category: "Animaux" },

  // ─── Objets (15) ───
  { id: "object-chaise-tabouret", civilWord: "Chaise", undercoverWord: "Tabouret", difficulty: "normal", category: "Objets" },
  { id: "object-velo-trottinette", civilWord: "Vélo", undercoverWord: "Trottinette", difficulty: "easy", category: "Objets" },
  { id: "object-lunettes-jumelles", civilWord: "Lunettes", undercoverWord: "Jumelles", difficulty: "normal", category: "Objets" },
  { id: "object-parapluie-parasol", civilWord: "Parapluie", undercoverWord: "Parasol", difficulty: "hard", category: "Objets" },
  { id: "object-guitare-violon", civilWord: "Guitare", undercoverWord: "Violon", difficulty: "normal", category: "Objets" },
  { id: "object-telephone-telecommande", civilWord: "Téléphone", undercoverWord: "Télécommande", difficulty: "normal", category: "Objets" },
  { id: "object-bougie-lampe", civilWord: "Bougie", undercoverWord: "Lampe", difficulty: "easy", category: "Objets" },
  { id: "object-epee-couteau", civilWord: "Épée", undercoverWord: "Couteau", difficulty: "normal", category: "Objets" },
  { id: "object-cle-serrure", civilWord: "Clé", undercoverWord: "Serrure", difficulty: "normal", category: "Objets" },
  { id: "object-livre-tablette", civilWord: "Livre", undercoverWord: "Tablette", difficulty: "normal", category: "Objets" },
  { id: "object-montre-horloge", civilWord: "Montre", undercoverWord: "Horloge", difficulty: "easy", category: "Objets" },
  { id: "object-valise-sacados", civilWord: "Valise", undercoverWord: "Sac à dos", difficulty: "normal", category: "Objets" },
  { id: "object-ciseaux-tondeuse", civilWord: "Ciseaux", undercoverWord: "Tondeuse", difficulty: "normal", category: "Objets" },
  { id: "object-miroir-vitre", civilWord: "Miroir", undercoverWord: "Vitre", difficulty: "hard", category: "Objets" },
  { id: "object-balai-aspirateur", civilWord: "Balai", undercoverWord: "Aspirateur", difficulty: "normal", category: "Objets" },

  // ─── Lieux (15) ───
  { id: "place-toureiffel-liberte", civilWord: "Tour Eiffel", undercoverWord: "Statue de la Liberté", difficulty: "easy", category: "Lieux" },
  { id: "place-pyramide-montagne", civilWord: "Pyramide", undercoverWord: "Montagne", difficulty: "normal", category: "Lieux" },
  { id: "place-hopital-pharmacie", civilWord: "Hôpital", undercoverWord: "Pharmacie", difficulty: "hard", category: "Lieux" },
  { id: "place-ecole-prison", civilWord: "École", undercoverWord: "Prison", difficulty: "normal", category: "Lieux" },
  { id: "place-plage-desert", civilWord: "Plage", undercoverWord: "Désert", difficulty: "normal", category: "Lieux" },
  { id: "place-chateau-eglise", civilWord: "Château", undercoverWord: "Église", difficulty: "normal", category: "Lieux" },
  { id: "place-piscine-lac", civilWord: "Piscine", undercoverWord: "Lac", difficulty: "normal", category: "Lieux" },
  { id: "place-fusee-avion", civilWord: "Fusée", undercoverWord: "Avion", difficulty: "easy", category: "Lieux" },
  { id: "place-stade-cirque", civilWord: "Stade", undercoverWord: "Cirque", difficulty: "normal", category: "Lieux" },
  { id: "place-cinema-theatre", civilWord: "Cinéma", undercoverWord: "Théâtre", difficulty: "hard", category: "Lieux" },
  { id: "place-resto-cantine", civilWord: "Restaurant", undercoverWord: "Cantine", difficulty: "normal", category: "Lieux" },
  { id: "place-foret-jungle", civilWord: "Forêt", undercoverWord: "Jungle", difficulty: "hard", category: "Lieux" },
  { id: "place-grotte-tunnel", civilWord: "Grotte", undercoverWord: "Tunnel", difficulty: "normal", category: "Lieux" },
  { id: "place-ile-continent", civilWord: "Île", undercoverWord: "Continent", difficulty: "hard", category: "Lieux" },
  { id: "place-zoo-aquarium", civilWord: "Zoo", undercoverWord: "Aquarium", difficulty: "easy", category: "Lieux" },

  // ─── Sports (15) ───
  { id: "sport-foot-rugby", civilWord: "Football", undercoverWord: "Rugby", difficulty: "easy", category: "Sports" },
  { id: "sport-basket-handball", civilWord: "Basketball", undercoverWord: "Handball", difficulty: "normal", category: "Sports" },
  { id: "sport-tennis-badminton", civilWord: "Tennis", undercoverWord: "Badminton", difficulty: "normal", category: "Sports" },
  { id: "sport-ski-snowboard", civilWord: "Ski", undercoverWord: "Snowboard", difficulty: "normal", category: "Sports" },
  { id: "sport-boxe-karate", civilWord: "Boxe", undercoverWord: "Karaté", difficulty: "normal", category: "Sports" },
  { id: "sport-natation-plongee", civilWord: "Natation", undercoverWord: "Plongée", difficulty: "normal", category: "Sports" },
  { id: "sport-surf-wakeboard", civilWord: "Surf", undercoverWord: "Wakeboard", difficulty: "hard", category: "Sports" },
  { id: "sport-escalade-randonnee", civilWord: "Escalade", undercoverWord: "Randonnée", difficulty: "normal", category: "Sports" },
  { id: "sport-golf-billard", civilWord: "Golf", undercoverWord: "Billard", difficulty: "normal", category: "Sports" },
  { id: "sport-velo-moto", civilWord: "Cyclisme", undercoverWord: "Moto", difficulty: "easy", category: "Sports" },
  { id: "sport-danse-gym", civilWord: "Danse", undercoverWord: "Gymnastique", difficulty: "normal", category: "Sports" },
  { id: "sport-skate-roller", civilWord: "Skateboard", undercoverWord: "Roller", difficulty: "normal", category: "Sports" },
  { id: "sport-catch-judo", civilWord: "Catch", undercoverWord: "Judo", difficulty: "hard", category: "Sports" },
  { id: "sport-ping-pong-squash", civilWord: "Ping-pong", undercoverWord: "Squash", difficulty: "hard", category: "Sports" },
  { id: "sport-arc-flechettes", civilWord: "Tir à l'arc", undercoverWord: "Fléchettes", difficulty: "normal", category: "Sports" },

  // ─── Métiers (12) ───
  { id: "job-pompier-policier", civilWord: "Pompier", undercoverWord: "Policier", difficulty: "easy", category: "Métiers" },
  { id: "job-medecin-infirmier", civilWord: "Médecin", undercoverWord: "Infirmier", difficulty: "normal", category: "Métiers" },
  { id: "job-prof-directeur", civilWord: "Professeur", undercoverWord: "Directeur", difficulty: "normal", category: "Métiers" },
  { id: "job-cuisinier-boulanger", civilWord: "Cuisinier", undercoverWord: "Boulanger", difficulty: "normal", category: "Métiers" },
  { id: "job-pilote-chauffeur", civilWord: "Pilote", undercoverWord: "Chauffeur", difficulty: "normal", category: "Métiers" },
  { id: "job-astronaute-plongeur", civilWord: "Astronaute", undercoverWord: "Plongeur", difficulty: "normal", category: "Métiers" },
  { id: "job-dentiste-chirurgien", civilWord: "Dentiste", undercoverWord: "Chirurgien", difficulty: "hard", category: "Métiers" },
  { id: "job-photographe-cameraman", civilWord: "Photographe", undercoverWord: "Caméraman", difficulty: "hard", category: "Métiers" },
  { id: "job-magicien-clown", civilWord: "Magicien", undercoverWord: "Clown", difficulty: "easy", category: "Métiers" },
  { id: "job-pirate-viking", civilWord: "Pirate", undercoverWord: "Viking", difficulty: "normal", category: "Métiers" },
  { id: "job-espion-detective", civilWord: "Espion", undercoverWord: "Détective", difficulty: "normal", category: "Métiers" },
  { id: "job-ninja-samourai", civilWord: "Ninja", undercoverWord: "Samouraï", difficulty: "normal", category: "Métiers" },

  // ─── Vêtements & Mode (10) ───
  { id: "cloth-chapeau-casquette", civilWord: "Chapeau", undercoverWord: "Casquette", difficulty: "easy", category: "Vêtements" },
  { id: "cloth-chaussure-botte", civilWord: "Chaussure", undercoverWord: "Botte", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-pull-gilet", civilWord: "Pull", undercoverWord: "Gilet", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-robe-jupe", civilWord: "Robe", undercoverWord: "Jupe", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-cravate-noeudpap", civilWord: "Cravate", undercoverWord: "Noeud papillon", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-gant-moufle", civilWord: "Gant", undercoverWord: "Moufle", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-echarpe-foulard", civilWord: "Écharpe", undercoverWord: "Foulard", difficulty: "hard", category: "Vêtements" },
  { id: "cloth-short-pantalon", civilWord: "Short", undercoverWord: "Pantalon", difficulty: "easy", category: "Vêtements" },
  { id: "cloth-tong-sandale", civilWord: "Tong", undercoverWord: "Sandale", difficulty: "normal", category: "Vêtements" },
  { id: "cloth-costume-pyjama", civilWord: "Costume", undercoverWord: "Pyjama", difficulty: "normal", category: "Vêtements" },

  // ─── Transport (10) ───
  { id: "trans-voiture-camion", civilWord: "Voiture", undercoverWord: "Camion", difficulty: "easy", category: "Transport" },
  { id: "trans-train-metro", civilWord: "Train", undercoverWord: "Métro", difficulty: "normal", category: "Transport" },
  { id: "trans-bateau-canoe", civilWord: "Bateau", undercoverWord: "Canoë", difficulty: "normal", category: "Transport" },
  { id: "trans-helico-drone", civilWord: "Hélicoptère", undercoverWord: "Drone", difficulty: "normal", category: "Transport" },
  { id: "trans-bus-tramway", civilWord: "Bus", undercoverWord: "Tramway", difficulty: "normal", category: "Transport" },
  { id: "trans-sousmarin-bateau", civilWord: "Sous-marin", undercoverWord: "Navire", difficulty: "normal", category: "Transport" },
  { id: "trans-ambulance-pompier", civilWord: "Ambulance", undercoverWord: "Camion de pompier", difficulty: "normal", category: "Transport" },
  { id: "trans-tank-bulldozer", civilWord: "Tank", undercoverWord: "Bulldozer", difficulty: "normal", category: "Transport" },
  { id: "trans-mongolfiere-parachute", civilWord: "Montgolfière", undercoverWord: "Parachute", difficulty: "normal", category: "Transport" },
  { id: "trans-quad-motoneige", civilWord: "Quad", undercoverWord: "Motoneige", difficulty: "hard", category: "Transport" },

  // ─── Nature (10) ───
  { id: "nat-soleil-lune", civilWord: "Soleil", undercoverWord: "Lune", difficulty: "easy", category: "Nature" },
  { id: "nat-arc-en-ciel-aurore", civilWord: "Arc-en-ciel", undercoverWord: "Aurore boréale", difficulty: "normal", category: "Nature" },
  { id: "nat-volcan-geyser", civilWord: "Volcan", undercoverWord: "Geyser", difficulty: "normal", category: "Nature" },
  { id: "nat-cascade-fontaine", civilWord: "Cascade", undercoverWord: "Fontaine", difficulty: "normal", category: "Nature" },
  { id: "nat-nuage-brouillard", civilWord: "Nuage", undercoverWord: "Brouillard", difficulty: "hard", category: "Nature" },
  { id: "nat-fleur-cactus", civilWord: "Fleur", undercoverWord: "Cactus", difficulty: "easy", category: "Nature" },
  { id: "nat-foudre-tonnerre", civilWord: "Éclair", undercoverWord: "Tonnerre", difficulty: "hard", category: "Nature" },
  { id: "nat-riviere-fleuve", civilWord: "Rivière", undercoverWord: "Fleuve", difficulty: "hard", category: "Nature" },
  { id: "nat-etoile-comete", civilWord: "Étoile", undercoverWord: "Comète", difficulty: "normal", category: "Nature" },
  { id: "nat-arbre-buisson", civilWord: "Arbre", undercoverWord: "Buisson", difficulty: "easy", category: "Nature" },

  // ─── Technologie (10) ───
  { id: "tech-ordi-laptop", civilWord: "Ordinateur", undercoverWord: "Laptop", difficulty: "hard", category: "Technologie" },
  { id: "tech-robot-ia", civilWord: "Robot", undercoverWord: "Intelligence artificielle", difficulty: "hard", category: "Technologie" },
  { id: "tech-casquevr-lunettes3d", civilWord: "Casque VR", undercoverWord: "Lunettes 3D", difficulty: "normal", category: "Technologie" },
  { id: "tech-manette-joystick", civilWord: "Manette", undercoverWord: "Joystick", difficulty: "normal", category: "Technologie" },
  { id: "tech-clavier-piano", civilWord: "Clavier", undercoverWord: "Piano", difficulty: "normal", category: "Technologie" },
  { id: "tech-wifi-bluetooth", civilWord: "WiFi", undercoverWord: "Bluetooth", difficulty: "hard", category: "Technologie" },
  { id: "tech-usb-prise", civilWord: "Clé USB", undercoverWord: "Prise électrique", difficulty: "normal", category: "Technologie" },
  { id: "tech-camera-webcam", civilWord: "Caméra", undercoverWord: "Webcam", difficulty: "normal", category: "Technologie" },
  { id: "tech-enceinte-micro", civilWord: "Enceinte", undercoverWord: "Microphone", difficulty: "normal", category: "Technologie" },
  { id: "tech-imprimante-scanner", civilWord: "Imprimante", undercoverWord: "Scanner", difficulty: "normal", category: "Technologie" },

  // ─── Musique & Instruments (10) ───
  { id: "music-piano-orgue", civilWord: "Piano", undercoverWord: "Orgue", difficulty: "normal", category: "Musique" },
  { id: "music-batterie-tam-tam", civilWord: "Batterie", undercoverWord: "Tam-tam", difficulty: "normal", category: "Musique" },
  { id: "music-trompette-saxophone", civilWord: "Trompette", undercoverWord: "Saxophone", difficulty: "normal", category: "Musique" },
  { id: "music-flute-clarinette", civilWord: "Flûte", undercoverWord: "Clarinette", difficulty: "hard", category: "Musique" },
  { id: "music-harpe-lyre", civilWord: "Harpe", undercoverWord: "Lyre", difficulty: "hard", category: "Musique" },
  { id: "music-accordeon-harmonica", civilWord: "Accordéon", undercoverWord: "Harmonica", difficulty: "normal", category: "Musique" },
  { id: "music-dj-chef-orchestre", civilWord: "DJ", undercoverWord: "Chef d'orchestre", difficulty: "normal", category: "Musique" },
  { id: "music-rap-slam", civilWord: "Rap", undercoverWord: "Slam", difficulty: "hard", category: "Musique" },
  { id: "music-concert-festival", civilWord: "Concert", undercoverWord: "Festival", difficulty: "normal", category: "Musique" },
  { id: "music-karaoke-chorale", civilWord: "Karaoké", undercoverWord: "Chorale", difficulty: "normal", category: "Musique" },

  // ─── Pop Culture & Jeux vidéo (20) ───
  { id: "pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-batman-zorro", civilWord: "Batman", undercoverWord: "Zorro", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-pikachu-raichu", civilWord: "Pikachu", undercoverWord: "Raichu", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-tiktok-instagram", civilWord: "TikTok", undercoverWord: "Instagram", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-fortnite-pubg", civilWord: "Fortnite", undercoverWord: "PUBG", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-naruto-goku", civilWord: "Naruto", undercoverWord: "Goku", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-shrek-hulk", civilWord: "Shrek", undercoverWord: "Hulk", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-spongebob-patrick", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-thanos-villain", civilWord: "Thanos", undercoverWord: "Dark Vador", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-spiderman-superman", civilWord: "Spider-Man", undercoverWord: "Superman", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-elsa-cendrillon", civilWord: "Elsa", undercoverWord: "Cendrillon", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-harry-gandalf", civilWord: "Harry Potter", undercoverWord: "Gandalf", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-gta-cyberpunk", civilWord: "GTA", undercoverWord: "Cyberpunk", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-among-us-loup-garou", civilWord: "Among Us", undercoverWord: "Loup-Garou", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-mickey-bugs-bunny", civilWord: "Mickey", undercoverWord: "Bugs Bunny", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-totoro-pikachu2", civilWord: "Totoro", undercoverWord: "Snorlax", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-ironman-optimus", civilWord: "Iron Man", undercoverWord: "Optimus Prime", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-yoda-dumbledore", civilWord: "Yoda", undercoverWord: "Dumbledore", difficulty: "normal", category: "Pop Culture" },

  // ─── Maison & Meubles (10) ───
  { id: "home-lit-canape", civilWord: "Lit", undercoverWord: "Canapé", difficulty: "easy", category: "Maison" },
  { id: "home-douche-baignoire", civilWord: "Douche", undercoverWord: "Baignoire", difficulty: "normal", category: "Maison" },
  { id: "home-fenetre-porte", civilWord: "Fenêtre", undercoverWord: "Porte", difficulty: "easy", category: "Maison" },
  { id: "home-four-micro-ondes", civilWord: "Four", undercoverWord: "Micro-ondes", difficulty: "normal", category: "Maison" },
  { id: "home-frigo-congelateur", civilWord: "Frigo", undercoverWord: "Congélateur", difficulty: "hard", category: "Maison" },
  { id: "home-escalier-ascenseur", civilWord: "Escalier", undercoverWord: "Ascenseur", difficulty: "normal", category: "Maison" },
  { id: "home-tele-projecteur", civilWord: "Télévision", undercoverWord: "Projecteur", difficulty: "normal", category: "Maison" },
  { id: "home-tapis-moquette", civilWord: "Tapis", undercoverWord: "Moquette", difficulty: "hard", category: "Maison" },
  { id: "home-rideau-store", civilWord: "Rideau", undercoverWord: "Store", difficulty: "hard", category: "Maison" },
  { id: "home-evier-lavabo", civilWord: "Évier", undercoverWord: "Lavabo", difficulty: "hard", category: "Maison" },

  // ─── École & Savoir (10) ───
  { id: "school-crayon-stylo", civilWord: "Crayon", undercoverWord: "Stylo", difficulty: "easy", category: "École" },
  { id: "school-cahier-classeur", civilWord: "Cahier", undercoverWord: "Classeur", difficulty: "normal", category: "École" },
  { id: "school-tableau-ecran", civilWord: "Tableau", undercoverWord: "Écran", difficulty: "normal", category: "École" },
  { id: "school-gomme-correcteur", civilWord: "Gomme", undercoverWord: "Correcteur", difficulty: "normal", category: "École" },
  { id: "school-regle-equerre", civilWord: "Règle", undercoverWord: "Équerre", difficulty: "hard", category: "École" },
  { id: "school-globe-carte", civilWord: "Globe", undercoverWord: "Carte", difficulty: "normal", category: "École" },
  { id: "school-sac-trousse", civilWord: "Sac d'école", undercoverWord: "Trousse", difficulty: "normal", category: "École" },
  { id: "school-calcul-geometrie", civilWord: "Calcul", undercoverWord: "Géométrie", difficulty: "hard", category: "École" },
  { id: "school-examen-controle", civilWord: "Examen", undercoverWord: "Contrôle", difficulty: "hard", category: "École" },
  { id: "school-recreation-sieste", civilWord: "Récréation", undercoverWord: "Sieste", difficulty: "normal", category: "École" },

  // ─── Fêtes & Événements (10) ───
  { id: "fete-noel-halloween", civilWord: "Noël", undercoverWord: "Halloween", difficulty: "easy", category: "Fêtes" },
  { id: "fete-anniversaire-mariage", civilWord: "Anniversaire", undercoverWord: "Mariage", difficulty: "normal", category: "Fêtes" },
  { id: "fete-carnaval-deguisement", civilWord: "Carnaval", undercoverWord: "Déguisement", difficulty: "normal", category: "Fêtes" },
  { id: "fete-feu-artifice-petard", civilWord: "Feu d'artifice", undercoverWord: "Pétard", difficulty: "normal", category: "Fêtes" },
  { id: "fete-cadeau-surprise", civilWord: "Cadeau", undercoverWord: "Surprise", difficulty: "normal", category: "Fêtes" },
  { id: "fete-pere-noel-lutin", civilWord: "Père Noël", undercoverWord: "Lutin", difficulty: "normal", category: "Fêtes" },
  { id: "fete-fantome-sorciere", civilWord: "Fantôme", undercoverWord: "Sorcière", difficulty: "easy", category: "Fêtes" },
  { id: "fete-oeuf-paques-lapin", civilWord: "Oeuf de Pâques", undercoverWord: "Lapin de Pâques", difficulty: "hard", category: "Fêtes" },
  { id: "fete-sapin-guirlande", civilWord: "Sapin", undercoverWord: "Guirlande", difficulty: "normal", category: "Fêtes" },
  { id: "fete-gateau-bougie-anniv", civilWord: "Gâteau d'anniversaire", undercoverWord: "Bougie d'anniversaire", difficulty: "hard", category: "Fêtes" },

  // ─── Corps humain (10) ───
  { id: "body-oeil-oreille", civilWord: "Oeil", undercoverWord: "Oreille", difficulty: "easy", category: "Corps" },
  { id: "body-main-pied", civilWord: "Main", undercoverWord: "Pied", difficulty: "easy", category: "Corps" },
  { id: "body-cerveau-coeur", civilWord: "Cerveau", undercoverWord: "Coeur", difficulty: "normal", category: "Corps" },
  { id: "body-dent-os", civilWord: "Dent", undercoverWord: "Os", difficulty: "normal", category: "Corps" },
  { id: "body-muscle-tendon", civilWord: "Muscle", undercoverWord: "Tendon", difficulty: "hard", category: "Corps" },
  { id: "body-cheveux-barbe", civilWord: "Cheveux", undercoverWord: "Barbe", difficulty: "normal", category: "Corps" },
  { id: "body-doigt-orteil", civilWord: "Doigt", undercoverWord: "Orteil", difficulty: "normal", category: "Corps" },
  { id: "body-nez-bouche", civilWord: "Nez", undercoverWord: "Bouche", difficulty: "easy", category: "Corps" },
  { id: "body-crane-squelette", civilWord: "Crâne", undercoverWord: "Squelette", difficulty: "normal", category: "Corps" },
  { id: "body-poumon-estomac", civilWord: "Poumon", undercoverWord: "Estomac", difficulty: "hard", category: "Corps" },

  // ─── Émotions & Expressions (10) ───
  { id: "emo-rire-pleurer", civilWord: "Rire", undercoverWord: "Pleurer", difficulty: "easy", category: "Émotions" },
  { id: "emo-colere-frustration", civilWord: "Colère", undercoverWord: "Frustration", difficulty: "hard", category: "Émotions" },
  { id: "emo-peur-angoisse", civilWord: "Peur", undercoverWord: "Angoisse", difficulty: "hard", category: "Émotions" },
  { id: "emo-joie-bonheur", civilWord: "Joie", undercoverWord: "Bonheur", difficulty: "hard", category: "Émotions" },
  { id: "emo-dormir-ronfler", civilWord: "Dormir", undercoverWord: "Ronfler", difficulty: "normal", category: "Émotions" },
  { id: "emo-crier-chuchoter", civilWord: "Crier", undercoverWord: "Chuchoter", difficulty: "normal", category: "Émotions" },
  { id: "emo-bisou-calin", civilWord: "Bisou", undercoverWord: "Câlin", difficulty: "normal", category: "Émotions" },
  { id: "emo-timide-confiant", civilWord: "Timide", undercoverWord: "Confiant", difficulty: "hard", category: "Émotions" },
  { id: "emo-ennui-paresse", civilWord: "Ennui", undercoverWord: "Paresse", difficulty: "hard", category: "Émotions" },
  { id: "emo-surprise-choc", civilWord: "Surprise", undercoverWord: "Choc", difficulty: "hard", category: "Émotions" },

  // ─── Chaos / Concepts abstraits (15) ───
  { id: "abs-amour-amitie", civilWord: "Amour", undercoverWord: "Amitié", difficulty: "hard", category: "Chaos" },
  { id: "abs-lundi-vendredi", civilWord: "Lundi", undercoverWord: "Vendredi", difficulty: "normal", category: "Chaos" },
  { id: "abs-bruit-silence", civilWord: "Bruit", undercoverWord: "Silence", difficulty: "hard", category: "Chaos" },
  { id: "abs-reve-cauchemar", civilWord: "Rêve", undercoverWord: "Cauchemar", difficulty: "normal", category: "Chaos" },
  { id: "abs-chaud-froid", civilWord: "Chaud", undercoverWord: "Froid", difficulty: "easy", category: "Chaos" },
  { id: "abs-hier-demain", civilWord: "Hier", undercoverWord: "Demain", difficulty: "hard", category: "Chaos" },
  { id: "abs-chance-malchance", civilWord: "Chance", undercoverWord: "Malchance", difficulty: "hard", category: "Chaos" },
  { id: "abs-vie-mort", civilWord: "Vie", undercoverWord: "Mort", difficulty: "normal", category: "Chaos" },
  { id: "abs-riche-pauvre", civilWord: "Riche", undercoverWord: "Pauvre", difficulty: "normal", category: "Chaos" },
  { id: "abs-ete-hiver", civilWord: "Été", undercoverWord: "Hiver", difficulty: "easy", category: "Chaos" },
  { id: "abs-guerre-paix", civilWord: "Guerre", undercoverWord: "Paix", difficulty: "normal", category: "Chaos" },
  { id: "abs-rapide-lent", civilWord: "Rapide", undercoverWord: "Lent", difficulty: "easy", category: "Chaos" },
  { id: "abs-lumiere-ombre", civilWord: "Lumière", undercoverWord: "Ombre", difficulty: "normal", category: "Chaos" },
  { id: "abs-genie-idiot", civilWord: "Génie", undercoverWord: "Idiot", difficulty: "normal", category: "Chaos" },
  { id: "abs-gravite-apesanteur", civilWord: "Gravité", undercoverWord: "Apesanteur", difficulty: "hard", category: "Chaos" },

  // ─── Espace & Science-fiction (10) ───
  { id: "space-terre-mars", civilWord: "Terre", undercoverWord: "Mars", difficulty: "normal", category: "Espace" },
  { id: "space-alien-fantome2", civilWord: "Alien", undercoverWord: "Fantôme", difficulty: "normal", category: "Espace" },
  { id: "space-meteorite-asteroide", civilWord: "Météorite", undercoverWord: "Astéroïde", difficulty: "hard", category: "Espace" },
  { id: "space-telescope-microscope", civilWord: "Télescope", undercoverWord: "Microscope", difficulty: "normal", category: "Espace" },
  { id: "space-ovni-satellite", civilWord: "OVNI", undercoverWord: "Satellite", difficulty: "normal", category: "Espace" },
  { id: "space-galaxie-nebuleuse", civilWord: "Galaxie", undercoverWord: "Nébuleuse", difficulty: "hard", category: "Espace" },
  { id: "space-astronaute2-cosmonaute", civilWord: "Astronaute", undercoverWord: "Cosmonaute", difficulty: "hard", category: "Espace" },
  { id: "space-blackhole-tornado", civilWord: "Trou noir", undercoverWord: "Tornade", difficulty: "normal", category: "Espace" },
  { id: "space-sabre-laser-epee", civilWord: "Sabre laser", undercoverWord: "Épée magique", difficulty: "normal", category: "Espace" },
  { id: "space-vaisseau-fusee", civilWord: "Vaisseau spatial", undercoverWord: "Fusée", difficulty: "normal", category: "Espace" },

  // ─── Contes & Légendes (10) ───
  { id: "tale-dragon-dinosaure", civilWord: "Dragon", undercoverWord: "Dinosaure", difficulty: "easy", category: "Contes" },
  { id: "tale-licorne-pegase", civilWord: "Licorne", undercoverWord: "Pégase", difficulty: "normal", category: "Contes" },
  { id: "tale-sirene-triton", civilWord: "Sirène", undercoverWord: "Triton", difficulty: "normal", category: "Contes" },
  { id: "tale-fee-ange", civilWord: "Fée", undercoverWord: "Ange", difficulty: "normal", category: "Contes" },
  { id: "tale-vampire-zombie", civilWord: "Vampire", undercoverWord: "Zombie", difficulty: "easy", category: "Contes" },
  { id: "tale-ogre-troll", civilWord: "Ogre", undercoverWord: "Troll", difficulty: "normal", category: "Contes" },
  { id: "tale-prince-roi", civilWord: "Prince", undercoverWord: "Roi", difficulty: "normal", category: "Contes" },
  { id: "tale-tresor-coffre", civilWord: "Trésor", undercoverWord: "Coffre", difficulty: "normal", category: "Contes" },
  { id: "tale-chateau-tour", civilWord: "Château fort", undercoverWord: "Tour de garde", difficulty: "hard", category: "Contes" },
  { id: "tale-baguette-magique-baton", civilWord: "Baguette magique", undercoverWord: "Bâton de sorcier", difficulty: "hard", category: "Contes" },

  // ─── Manga / Anime (18) ───
  { id: "anime-naruto-luffy", civilWord: "Naruto", undercoverWord: "Luffy", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-goku-vegeta", civilWord: "Goku", undercoverWord: "Vegeta", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-sasuke-itachi", civilWord: "Sasuke", undercoverWord: "Itachi", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-totoro-noiraude", civilWord: "Totoro", undercoverWord: "Noiraude", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-pikachu-evoli", civilWord: "Pikachu", undercoverWord: "Évoli", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-sailor-moon-cardcaptor", civilWord: "Sailor Moon", undercoverWord: "Cardcaptor Sakura", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-onepiece-bateau", civilWord: "One Piece", undercoverWord: "Bateau pirate", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-spirited-away-howl", civilWord: "Chihiro", undercoverWord: "Howl", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-akatsuki-anbu", civilWord: "Akatsuki", undercoverWord: "ANBU", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-shinigami-hollow", civilWord: "Shinigami", undercoverWord: "Hollow", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-titan-colossal", civilWord: "Titan", undercoverWord: "Titan colossal", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-deku-bakugo", civilWord: "Deku", undercoverWord: "Bakugo", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-gojo-sukuna", civilWord: "Gojo", undercoverWord: "Sukuna", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-tanjiro-zenitsu", civilWord: "Tanjiro", undercoverWord: "Zenitsu", difficulty: "normal", category: "Manga / Anime" },
  { id: "anime-nezuko-shinobu", civilWord: "Nezuko", undercoverWord: "Shinobu", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-pokemon-pokeball", civilWord: "Pokémon", undercoverWord: "Poké Ball", difficulty: "easy", category: "Manga / Anime" },
  { id: "anime-mecha-gundam", civilWord: "Mecha", undercoverWord: "Gundam", difficulty: "hard", category: "Manga / Anime" },
  { id: "anime-ramen-bento", civilWord: "Ramen", undercoverWord: "Bento", difficulty: "normal", category: "Manga / Anime" },

  // ─── Jeux vidéo (18) ───
  { id: "game-mario-luigi", civilWord: "Mario", undercoverWord: "Luigi", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-zelda-link", civilWord: "Zelda", undercoverWord: "Link", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-creeper-zombie", civilWord: "Creeper", undercoverWord: "Zombie", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-fortnite-apex", civilWord: "Fortnite", undercoverWord: "Apex Legends", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-pacman-ghost", civilWord: "Pac-Man", undercoverWord: "Fantôme", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-sonic-shadow", civilWord: "Sonic", undercoverWord: "Shadow", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-masterchief-doomguy", civilWord: "Master Chief", undercoverWord: "Doom Slayer", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-tetris-puyo", civilWord: "Tetris", undercoverWord: "Puyo Puyo", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-roblox-minecraft", civilWord: "Roblox", undercoverWord: "Minecraft", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-pokeball-masterball", civilWord: "Poké Ball", undercoverWord: "Master Ball", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-kirby-yoshi", civilWord: "Kirby", undercoverWord: "Yoshi", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-bowser-wario", civilWord: "Bowser", undercoverWord: "Wario", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-kratos-thor", civilWord: "Kratos", undercoverWord: "Thor", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-overcooked-plateup", civilWord: "Overcooked", undercoverWord: "PlateUp!", difficulty: "hard", category: "Jeux vidéo" },
  { id: "game-amongus-impostor", civilWord: "Among Us", undercoverWord: "Imposteur", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-potion-elixir", civilWord: "Potion", undercoverWord: "Élixir", difficulty: "normal", category: "Jeux vidéo" },
  { id: "game-joystick-console", civilWord: "Joystick", undercoverWord: "Console", difficulty: "easy", category: "Jeux vidéo" },
  { id: "game-speedrun-checkpoint", civilWord: "Speedrun", undercoverWord: "Checkpoint", difficulty: "hard", category: "Jeux vidéo" },

  // ─── Cinéma / Séries (18) ───
  { id: "screen-harry-hermione", civilWord: "Harry Potter", undercoverWord: "Hermione", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-batman-joker", civilWord: "Batman", undercoverWord: "Joker", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-vador-yoda", civilWord: "Dark Vador", undercoverWord: "Yoda", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-spiderman-venom", civilWord: "Spider-Man", undercoverWord: "Venom", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-sherlock-watson", civilWord: "Sherlock", undercoverWord: "Watson", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-hobbit-elf", civilWord: "Hobbit", undercoverWord: "Elfe", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-minion-groot", civilWord: "Minion", undercoverWord: "Groot", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-thor-loki", civilWord: "Thor", undercoverWord: "Loki", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-elsa-anna", civilWord: "Elsa", undercoverWord: "Anna", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-simba-mufasa", civilWord: "Simba", undercoverWord: "Mufasa", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-r2d2-c3po", civilWord: "R2-D2", undercoverWord: "C-3PO", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-wednesday-enid", civilWord: "Wednesday", undercoverWord: "Enid", difficulty: "hard", category: "Cinéma / Séries" },
  { id: "screen-stranger-demogorgon", civilWord: "Stranger Things", undercoverWord: "Demogorgon", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-marvel-avengers", civilWord: "Marvel", undercoverWord: "Avengers", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-kungfu-panda-shifu", civilWord: "Po", undercoverWord: "Shifu", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-spongebob-patrick-series", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "easy", category: "Cinéma / Séries" },
  { id: "screen-rick-morty", civilWord: "Rick", undercoverWord: "Morty", difficulty: "normal", category: "Cinéma / Séries" },
  { id: "screen-gandalf-saruman", civilWord: "Gandalf", undercoverWord: "Saroumane", difficulty: "hard", category: "Cinéma / Séries" }
];

export const WORD_CATEGORIES = [...new Set(BASE_WORD_PAIRS.map((pair) => pair.category))].sort(
  (left, right) => left.localeCompare(right, "fr")
);
