import type { WordPair } from "./protocol.js";

export const BASE_WORD_PAIRS: WordPair[] = [
  { id: "food-pizza-galette", civilWord: "Pizza", undercoverWord: "Galette", difficulty: "normal", category: "Nourriture" },
  { id: "food-sushi-onigiri", civilWord: "Sushi", undercoverWord: "Onigiri", difficulty: "hard", category: "Nourriture" },
  { id: "food-croissant-bretzel", civilWord: "Croissant", undercoverWord: "Bretzel", difficulty: "normal", category: "Nourriture" },
  { id: "food-hamburger-sandwich", civilWord: "Hamburger", undercoverWord: "Sandwich", difficulty: "easy", category: "Nourriture" },
  { id: "food-icecream-cupcake", civilWord: "Glace", undercoverWord: "Cupcake", difficulty: "normal", category: "Nourriture" },
  { id: "food-spaghetti-ramen", civilWord: "Spaghetti", undercoverWord: "Ramen", difficulty: "hard", category: "Nourriture" },
  { id: "food-baguette-baton", civilWord: "Baguette", undercoverWord: "Bâton de pain", difficulty: "hard", category: "Nourriture" },
  { id: "food-pancake-crepe", civilWord: "Pancake", undercoverWord: "Crêpe", difficulty: "hard", category: "Nourriture" },
  { id: "food-donut-bagel", civilWord: "Donut", undercoverWord: "Bagel", difficulty: "normal", category: "Nourriture" },
  { id: "food-popcorn-cereales", civilWord: "Popcorn", undercoverWord: "Céréales", difficulty: "normal", category: "Nourriture" },
  { id: "animal-chat-tigre", civilWord: "Chat", undercoverWord: "Tigre", difficulty: "easy", category: "Animaux" },
  { id: "animal-chien-loup", civilWord: "Chien", undercoverWord: "Loup", difficulty: "normal", category: "Animaux" },
  { id: "animal-pingouin-canard", civilWord: "Pingouin", undercoverWord: "Canard", difficulty: "normal", category: "Animaux" },
  { id: "animal-tortue-escargot", civilWord: "Tortue", undercoverWord: "Escargot", difficulty: "normal", category: "Animaux" },
  { id: "animal-requin-dauphin", civilWord: "Requin", undercoverWord: "Dauphin", difficulty: "easy", category: "Animaux" },
  { id: "animal-abeille-guepe", civilWord: "Abeille", undercoverWord: "Guêpe", difficulty: "hard", category: "Animaux" },
  { id: "animal-crocodile-lezard", civilWord: "Crocodile", undercoverWord: "Lézard", difficulty: "normal", category: "Animaux" },
  { id: "animal-panda-ours", civilWord: "Panda", undercoverWord: "Ours", difficulty: "normal", category: "Animaux" },
  { id: "animal-papillon-libellule", civilWord: "Papillon", undercoverWord: "Libellule", difficulty: "normal", category: "Animaux" },
  { id: "animal-pieuvre-meduse", civilWord: "Pieuvre", undercoverWord: "Méduse", difficulty: "normal", category: "Animaux" },
  { id: "object-chaise-tabouret", civilWord: "Chaise", undercoverWord: "Tabouret", difficulty: "normal", category: "Objets" },
  { id: "object-velo-trottinette", civilWord: "Vélo", undercoverWord: "Trottinette", difficulty: "easy", category: "Objets" },
  { id: "object-lunettes-jumelles", civilWord: "Lunettes", undercoverWord: "Jumelles", difficulty: "normal", category: "Objets" },
  { id: "object-parapluie-parasol", civilWord: "Parapluie", undercoverWord: "Parasol", difficulty: "hard", category: "Objets" },
  { id: "object-guitare-violon", civilWord: "Guitare", undercoverWord: "Violon", difficulty: "normal", category: "Objets" },
  { id: "object-telephone-telecommande", civilWord: "Téléphone", undercoverWord: "Télécommande", difficulty: "normal", category: "Objets" },
  { id: "object-bougie-lampe", civilWord: "Bougie", undercoverWord: "Lampe", difficulty: "easy", category: "Objets" },
  { id: "object-epee-couteau", civilWord: "Épée", undercoverWord: "Couteau", difficulty: "normal", category: "Objets" },
  { id: "object-cle-serrure", civilWord: "Clé", undercoverWord: "Serrure", difficulty: "normal", category: "Objets" },
  { id: "object-livre-tablette", civilWord: "Livre", undercoverWord: "Tablette", difficulty: "normal", category: "Objets" },
  { id: "place-toureiffel-liberte", civilWord: "Tour Eiffel", undercoverWord: "Statue de la Liberté", difficulty: "easy", category: "Lieux" },
  { id: "place-pyramide-montagne", civilWord: "Pyramide", undercoverWord: "Montagne", difficulty: "normal", category: "Lieux" },
  { id: "place-hopital-pharmacie", civilWord: "Hôpital", undercoverWord: "Pharmacie", difficulty: "hard", category: "Lieux" },
  { id: "place-ecole-prison", civilWord: "École", undercoverWord: "Prison", difficulty: "normal", category: "Lieux" },
  { id: "place-plage-desert", civilWord: "Plage", undercoverWord: "Désert", difficulty: "normal", category: "Lieux" },
  { id: "place-chateau-eglise", civilWord: "Château", undercoverWord: "Église", difficulty: "normal", category: "Lieux" },
  { id: "place-piscine-lac", civilWord: "Piscine", undercoverWord: "Lac", difficulty: "normal", category: "Lieux" },
  { id: "place-fusee-avion", civilWord: "Fusée", undercoverWord: "Avion", difficulty: "easy", category: "Lieux" },
  { id: "place-stade-cirque", civilWord: "Stade", undercoverWord: "Cirque", difficulty: "normal", category: "Lieux" },
  { id: "place-cinema-theatre", civilWord: "Cinéma", undercoverWord: "Théâtre", difficulty: "hard", category: "Lieux" },
  { id: "pop-mario-sonic", civilWord: "Mario", undercoverWord: "Sonic", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-batman-zorro", civilWord: "Batman", undercoverWord: "Zorro", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-pikachu-raichu", civilWord: "Pikachu", undercoverWord: "Raichu", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-minecraft-roblox", civilWord: "Minecraft", undercoverWord: "Roblox", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-tiktok-instagram", civilWord: "TikTok", undercoverWord: "Instagram", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-fortnite-pubg", civilWord: "Fortnite", undercoverWord: "PUBG", difficulty: "hard", category: "Pop Culture" },
  { id: "pop-naruto-goku", civilWord: "Naruto", undercoverWord: "Goku", difficulty: "easy", category: "Pop Culture" },
  { id: "pop-shrek-hulk", civilWord: "Shrek", undercoverWord: "Hulk", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-spongebob-patrick", civilWord: "SpongeBob", undercoverWord: "Patrick", difficulty: "normal", category: "Pop Culture" },
  { id: "pop-thanos-villain", civilWord: "Thanos", undercoverWord: "Méchant générique", difficulty: "hard", category: "Pop Culture" },
  { id: "abs-amour-amitie", civilWord: "Amour", undercoverWord: "Amitié", difficulty: "hard", category: "Chaos" },
  { id: "abs-lundi-vendredi", civilWord: "Lundi", undercoverWord: "Vendredi", difficulty: "normal", category: "Chaos" },
  { id: "abs-bruit-silence", civilWord: "Bruit", undercoverWord: "Silence", difficulty: "hard", category: "Chaos" },
  { id: "abs-reve-cauchemar", civilWord: "Rêve", undercoverWord: "Cauchemar", difficulty: "normal", category: "Chaos" },
  { id: "abs-chaud-froid", civilWord: "Chaud", undercoverWord: "Froid", difficulty: "easy", category: "Chaos" },
  { id: "abs-hier-demain", civilWord: "Hier", undercoverWord: "Demain", difficulty: "hard", category: "Chaos" },
  { id: "abs-chance-malchance", civilWord: "Chance", undercoverWord: "Malchance", difficulty: "hard", category: "Chaos" },
  { id: "abs-vie-mort", civilWord: "Vie", undercoverWord: "Mort", difficulty: "normal", category: "Chaos" },
  { id: "abs-riche-pauvre", civilWord: "Riche", undercoverWord: "Pauvre", difficulty: "normal", category: "Chaos" },
  { id: "abs-ete-hiver", civilWord: "Été", undercoverWord: "Hiver", difficulty: "easy", category: "Chaos" }
];
